/*
Config Store API

PostgreSQL-backed configuration storage service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configstore

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DeviceUUID type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceUUID{}

// DeviceUUID Provider-owned device identifier entry.  The class and response field names are retained for API compatibility.
type DeviceUUID struct {
	// DCIM provider device identifier
	Uuid string `json:"uuid"`
}

type _DeviceUUID DeviceUUID

// NewDeviceUUID instantiates a new DeviceUUID object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceUUID(uuid string) *DeviceUUID {
	this := DeviceUUID{}
	this.Uuid = uuid
	return &this
}

// NewDeviceUUIDWithDefaults instantiates a new DeviceUUID object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceUUIDWithDefaults() *DeviceUUID {
	this := DeviceUUID{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *DeviceUUID) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *DeviceUUID) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *DeviceUUID) SetUuid(v string) {
	o.Uuid = v
}

func (o DeviceUUID) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceUUID) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	return toSerialize, nil
}

func (o *DeviceUUID) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"uuid": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeviceUUID := _DeviceUUID{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeviceUUID)

	if err != nil {
		return err
	}

	*o = DeviceUUID(varDeviceUUID)

	return err
}

type NullableDeviceUUID struct {
	value *DeviceUUID
	isSet bool
}

func (v NullableDeviceUUID) Get() *DeviceUUID {
	return v.value
}

func (v *NullableDeviceUUID) Set(val *DeviceUUID) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceUUID) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceUUID) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceUUID(val *DeviceUUID) *NullableDeviceUUID {
	return &NullableDeviceUUID{value: val, isSet: true}
}

func (v NullableDeviceUUID) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceUUID) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
