/*
Config Store API

PostgreSQL-backed configuration storage service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configstore

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the StatsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatsResponse{}

// StatsResponse Database statistics response.
type StatsResponse struct {
	// Total storage used in bytes (compressed)
	StorageBytes int32 `json:"storage_bytes"`
	// Total storage used in MB (compressed)
	StorageMb float32 `json:"storage_mb"`
	// Total number of config file versions
	TotalConfigVersions int32 `json:"total_config_versions"`
	// Number of unique devices with configs
	UniqueDevices int32 `json:"unique_devices"`
	// Number of unique config files (device + filename)
	UniqueFiles int32 `json:"unique_files"`
}

type _StatsResponse StatsResponse

// NewStatsResponse instantiates a new StatsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatsResponse(storageBytes int32, storageMb float32, totalConfigVersions int32, uniqueDevices int32, uniqueFiles int32) *StatsResponse {
	this := StatsResponse{}
	this.StorageBytes = storageBytes
	this.StorageMb = storageMb
	this.TotalConfigVersions = totalConfigVersions
	this.UniqueDevices = uniqueDevices
	this.UniqueFiles = uniqueFiles
	return &this
}

// NewStatsResponseWithDefaults instantiates a new StatsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatsResponseWithDefaults() *StatsResponse {
	this := StatsResponse{}
	return &this
}

// GetStorageBytes returns the StorageBytes field value
func (o *StatsResponse) GetStorageBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StorageBytes
}

// GetStorageBytesOk returns a tuple with the StorageBytes field value
// and a boolean to check if the value has been set.
func (o *StatsResponse) GetStorageBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageBytes, true
}

// SetStorageBytes sets field value
func (o *StatsResponse) SetStorageBytes(v int32) {
	o.StorageBytes = v
}

// GetStorageMb returns the StorageMb field value
func (o *StatsResponse) GetStorageMb() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.StorageMb
}

// GetStorageMbOk returns a tuple with the StorageMb field value
// and a boolean to check if the value has been set.
func (o *StatsResponse) GetStorageMbOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageMb, true
}

// SetStorageMb sets field value
func (o *StatsResponse) SetStorageMb(v float32) {
	o.StorageMb = v
}

// GetTotalConfigVersions returns the TotalConfigVersions field value
func (o *StatsResponse) GetTotalConfigVersions() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalConfigVersions
}

// GetTotalConfigVersionsOk returns a tuple with the TotalConfigVersions field value
// and a boolean to check if the value has been set.
func (o *StatsResponse) GetTotalConfigVersionsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalConfigVersions, true
}

// SetTotalConfigVersions sets field value
func (o *StatsResponse) SetTotalConfigVersions(v int32) {
	o.TotalConfigVersions = v
}

// GetUniqueDevices returns the UniqueDevices field value
func (o *StatsResponse) GetUniqueDevices() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UniqueDevices
}

// GetUniqueDevicesOk returns a tuple with the UniqueDevices field value
// and a boolean to check if the value has been set.
func (o *StatsResponse) GetUniqueDevicesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UniqueDevices, true
}

// SetUniqueDevices sets field value
func (o *StatsResponse) SetUniqueDevices(v int32) {
	o.UniqueDevices = v
}

// GetUniqueFiles returns the UniqueFiles field value
func (o *StatsResponse) GetUniqueFiles() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UniqueFiles
}

// GetUniqueFilesOk returns a tuple with the UniqueFiles field value
// and a boolean to check if the value has been set.
func (o *StatsResponse) GetUniqueFilesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UniqueFiles, true
}

// SetUniqueFiles sets field value
func (o *StatsResponse) SetUniqueFiles(v int32) {
	o.UniqueFiles = v
}

func (o StatsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["storage_bytes"] = o.StorageBytes
	toSerialize["storage_mb"] = o.StorageMb
	toSerialize["total_config_versions"] = o.TotalConfigVersions
	toSerialize["unique_devices"] = o.UniqueDevices
	toSerialize["unique_files"] = o.UniqueFiles
	return toSerialize, nil
}

func (o *StatsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"storage_bytes":         false,
		"storage_mb":            false,
		"total_config_versions": false,
		"unique_devices":        false,
		"unique_files":          false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatsResponse := _StatsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStatsResponse)

	if err != nil {
		return err
	}

	*o = StatsResponse(varStatsResponse)

	return err
}

type NullableStatsResponse struct {
	value *StatsResponse
	isSet bool
}

func (v NullableStatsResponse) Get() *StatsResponse {
	return v.value
}

func (v *NullableStatsResponse) Set(val *StatsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStatsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStatsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatsResponse(val *StatsResponse) *NullableStatsResponse {
	return &NullableStatsResponse{value: val, isSet: true}
}

func (v NullableStatsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
