/*
Config Store API

PostgreSQL-backed configuration storage service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configstore

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CacheTestErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheTestErrorResponse{}

// CacheTestErrorResponse Cache test response when there's an error.
type CacheTestErrorResponse struct {
	// DCIM provider device identifier
	DeviceUuid string `json:"device_uuid"`
	// Error message
	Error string `json:"error"`
}

type _CacheTestErrorResponse CacheTestErrorResponse

// NewCacheTestErrorResponse instantiates a new CacheTestErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheTestErrorResponse(deviceUuid string, error_ string) *CacheTestErrorResponse {
	this := CacheTestErrorResponse{}
	this.DeviceUuid = deviceUuid
	this.Error = error_
	return &this
}

// NewCacheTestErrorResponseWithDefaults instantiates a new CacheTestErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheTestErrorResponseWithDefaults() *CacheTestErrorResponse {
	this := CacheTestErrorResponse{}
	return &this
}

// GetDeviceUuid returns the DeviceUuid field value
func (o *CacheTestErrorResponse) GetDeviceUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceUuid
}

// GetDeviceUuidOk returns a tuple with the DeviceUuid field value
// and a boolean to check if the value has been set.
func (o *CacheTestErrorResponse) GetDeviceUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceUuid, true
}

// SetDeviceUuid sets field value
func (o *CacheTestErrorResponse) SetDeviceUuid(v string) {
	o.DeviceUuid = v
}

// GetError returns the Error field value
func (o *CacheTestErrorResponse) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *CacheTestErrorResponse) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *CacheTestErrorResponse) SetError(v string) {
	o.Error = v
}

func (o CacheTestErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheTestErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["device_uuid"] = o.DeviceUuid
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *CacheTestErrorResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"device_uuid": false,
		"error":       false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCacheTestErrorResponse := _CacheTestErrorResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCacheTestErrorResponse)

	if err != nil {
		return err
	}

	*o = CacheTestErrorResponse(varCacheTestErrorResponse)

	return err
}

type NullableCacheTestErrorResponse struct {
	value *CacheTestErrorResponse
	isSet bool
}

func (v NullableCacheTestErrorResponse) Get() *CacheTestErrorResponse {
	return v.value
}

func (v *NullableCacheTestErrorResponse) Set(val *CacheTestErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheTestErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheTestErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheTestErrorResponse(val *CacheTestErrorResponse) *NullableCacheTestErrorResponse {
	return &NullableCacheTestErrorResponse{value: val, isSet: true}
}

func (v NullableCacheTestErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheTestErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
