/*
Config Store API

PostgreSQL-backed configuration storage service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configstore

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ConfigVersionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigVersionsResponse{}

// ConfigVersionsResponse Response with list of versions.
type ConfigVersionsResponse struct {
	// Device metadata from the selected DCIM provider
	Device NullableDeviceMetadata `json:"device,omitempty"`
	// DCIM provider device identifier
	DeviceUuid string `json:"device_uuid"`
	// File name
	Filename string `json:"filename"`
	// List of versions
	Versions []ConfigVersionResponse `json:"versions"`
}

type _ConfigVersionsResponse ConfigVersionsResponse

// NewConfigVersionsResponse instantiates a new ConfigVersionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigVersionsResponse(deviceUuid string, filename string, versions []ConfigVersionResponse) *ConfigVersionsResponse {
	this := ConfigVersionsResponse{}
	this.DeviceUuid = deviceUuid
	this.Filename = filename
	this.Versions = versions
	return &this
}

// NewConfigVersionsResponseWithDefaults instantiates a new ConfigVersionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigVersionsResponseWithDefaults() *ConfigVersionsResponse {
	this := ConfigVersionsResponse{}
	return &this
}

// GetDevice returns the Device field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConfigVersionsResponse) GetDevice() DeviceMetadata {
	if o == nil || IsNil(o.Device.Get()) {
		var ret DeviceMetadata
		return ret
	}
	return *o.Device.Get()
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *ConfigVersionsResponse) GetDeviceOk() (*DeviceMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return o.Device.Get(), o.Device.IsSet()
}

// HasDevice returns a boolean if a field has been set.
func (o *ConfigVersionsResponse) HasDevice() bool {
	if o != nil && o.Device.IsSet() {
		return true
	}

	return false
}

// SetDevice gets a reference to the given NullableDeviceMetadata and assigns it to the Device field.
func (o *ConfigVersionsResponse) SetDevice(v DeviceMetadata) {
	o.Device.Set(&v)
}

// SetDeviceNil sets the value for Device to be an explicit nil
func (o *ConfigVersionsResponse) SetDeviceNil() {
	o.Device.Set(nil)
}

// UnsetDevice ensures that no value is present for Device, not even an explicit nil
func (o *ConfigVersionsResponse) UnsetDevice() {
	o.Device.Unset()
}

// GetDeviceUuid returns the DeviceUuid field value
func (o *ConfigVersionsResponse) GetDeviceUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceUuid
}

// GetDeviceUuidOk returns a tuple with the DeviceUuid field value
// and a boolean to check if the value has been set.
func (o *ConfigVersionsResponse) GetDeviceUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceUuid, true
}

// SetDeviceUuid sets field value
func (o *ConfigVersionsResponse) SetDeviceUuid(v string) {
	o.DeviceUuid = v
}

// GetFilename returns the Filename field value
func (o *ConfigVersionsResponse) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *ConfigVersionsResponse) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *ConfigVersionsResponse) SetFilename(v string) {
	o.Filename = v
}

// GetVersions returns the Versions field value
func (o *ConfigVersionsResponse) GetVersions() []ConfigVersionResponse {
	if o == nil {
		var ret []ConfigVersionResponse
		return ret
	}

	return o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value
// and a boolean to check if the value has been set.
func (o *ConfigVersionsResponse) GetVersionsOk() ([]ConfigVersionResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Versions, true
}

// SetVersions sets field value
func (o *ConfigVersionsResponse) SetVersions(v []ConfigVersionResponse) {
	o.Versions = v
}

func (o ConfigVersionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigVersionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Device.IsSet() {
		toSerialize["device"] = o.Device.Get()
	}
	toSerialize["device_uuid"] = o.DeviceUuid
	toSerialize["filename"] = o.Filename
	toSerialize["versions"] = o.Versions
	return toSerialize, nil
}

func (o *ConfigVersionsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"device_uuid": false,
		"filename":    false,
		"versions":    false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigVersionsResponse := _ConfigVersionsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigVersionsResponse)

	if err != nil {
		return err
	}

	*o = ConfigVersionsResponse(varConfigVersionsResponse)

	return err
}

type NullableConfigVersionsResponse struct {
	value *ConfigVersionsResponse
	isSet bool
}

func (v NullableConfigVersionsResponse) Get() *ConfigVersionsResponse {
	return v.value
}

func (v *NullableConfigVersionsResponse) Set(val *ConfigVersionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigVersionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigVersionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigVersionsResponse(val *ConfigVersionsResponse) *NullableConfigVersionsResponse {
	return &NullableConfigVersionsResponse{value: val, isSet: true}
}

func (v NullableConfigVersionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigVersionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
