/*
Config Store API

PostgreSQL-backed configuration storage service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configstore

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DeleteDeviceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteDeviceResponse{}

// DeleteDeviceResponse Response for device config deletion.
type DeleteDeviceResponse struct {
	// Number of config versions deleted
	DeletedVersions int32 `json:"deleted_versions"`
	// DCIM provider device identifier
	DeviceUuid string `json:"device_uuid"`
	// Human-readable result message
	Message string `json:"message"`
}

type _DeleteDeviceResponse DeleteDeviceResponse

// NewDeleteDeviceResponse instantiates a new DeleteDeviceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteDeviceResponse(deletedVersions int32, deviceUuid string, message string) *DeleteDeviceResponse {
	this := DeleteDeviceResponse{}
	this.DeletedVersions = deletedVersions
	this.DeviceUuid = deviceUuid
	this.Message = message
	return &this
}

// NewDeleteDeviceResponseWithDefaults instantiates a new DeleteDeviceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteDeviceResponseWithDefaults() *DeleteDeviceResponse {
	this := DeleteDeviceResponse{}
	return &this
}

// GetDeletedVersions returns the DeletedVersions field value
func (o *DeleteDeviceResponse) GetDeletedVersions() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DeletedVersions
}

// GetDeletedVersionsOk returns a tuple with the DeletedVersions field value
// and a boolean to check if the value has been set.
func (o *DeleteDeviceResponse) GetDeletedVersionsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeletedVersions, true
}

// SetDeletedVersions sets field value
func (o *DeleteDeviceResponse) SetDeletedVersions(v int32) {
	o.DeletedVersions = v
}

// GetDeviceUuid returns the DeviceUuid field value
func (o *DeleteDeviceResponse) GetDeviceUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceUuid
}

// GetDeviceUuidOk returns a tuple with the DeviceUuid field value
// and a boolean to check if the value has been set.
func (o *DeleteDeviceResponse) GetDeviceUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceUuid, true
}

// SetDeviceUuid sets field value
func (o *DeleteDeviceResponse) SetDeviceUuid(v string) {
	o.DeviceUuid = v
}

// GetMessage returns the Message field value
func (o *DeleteDeviceResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *DeleteDeviceResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *DeleteDeviceResponse) SetMessage(v string) {
	o.Message = v
}

func (o DeleteDeviceResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteDeviceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deleted_versions"] = o.DeletedVersions
	toSerialize["device_uuid"] = o.DeviceUuid
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *DeleteDeviceResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"deleted_versions": false,
		"device_uuid":      false,
		"message":          false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteDeviceResponse := _DeleteDeviceResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteDeviceResponse)

	if err != nil {
		return err
	}

	*o = DeleteDeviceResponse(varDeleteDeviceResponse)

	return err
}

type NullableDeleteDeviceResponse struct {
	value *DeleteDeviceResponse
	isSet bool
}

func (v NullableDeleteDeviceResponse) Get() *DeleteDeviceResponse {
	return v.value
}

func (v *NullableDeleteDeviceResponse) Set(val *DeleteDeviceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteDeviceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteDeviceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteDeviceResponse(val *DeleteDeviceResponse) *NullableDeleteDeviceResponse {
	return &NullableDeleteDeviceResponse{value: val, isSet: true}
}

func (v NullableDeleteDeviceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteDeviceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
