/*
Config Store API

PostgreSQL-backed configuration storage service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configstore

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CacheStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheStatusResponse{}

// CacheStatusResponse Cache service status response.
type CacheStatusResponse struct {
	// Cache TTL in seconds
	CacheTtl NullableInt32 `json:"cache_ttl,omitempty"`
	// Whether the selected DCIM client is available
	DcimConnected NullableBool `json:"dcim_connected,omitempty"`
	// Whether cache service is enabled
	Enabled bool `json:"enabled"`
	// Status message if disabled
	Message NullableString `json:"message,omitempty"`
	// Legacy alias for dcim_connected
	NautobotConnected NullableBool `json:"nautobot_connected,omitempty"`
	// Whether Redis is connected
	RedisConnected NullableBool `json:"redis_connected,omitempty"`
}

type _CacheStatusResponse CacheStatusResponse

// NewCacheStatusResponse instantiates a new CacheStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheStatusResponse(enabled bool) *CacheStatusResponse {
	this := CacheStatusResponse{}
	this.Enabled = enabled
	return &this
}

// NewCacheStatusResponseWithDefaults instantiates a new CacheStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheStatusResponseWithDefaults() *CacheStatusResponse {
	this := CacheStatusResponse{}
	return &this
}

// GetCacheTtl returns the CacheTtl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CacheStatusResponse) GetCacheTtl() int32 {
	if o == nil || IsNil(o.CacheTtl.Get()) {
		var ret int32
		return ret
	}
	return *o.CacheTtl.Get()
}

// GetCacheTtlOk returns a tuple with the CacheTtl field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *CacheStatusResponse) GetCacheTtlOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CacheTtl.Get(), o.CacheTtl.IsSet()
}

// HasCacheTtl returns a boolean if a field has been set.
func (o *CacheStatusResponse) HasCacheTtl() bool {
	if o != nil && o.CacheTtl.IsSet() {
		return true
	}

	return false
}

// SetCacheTtl gets a reference to the given NullableInt32 and assigns it to the CacheTtl field.
func (o *CacheStatusResponse) SetCacheTtl(v int32) {
	o.CacheTtl.Set(&v)
}

// SetCacheTtlNil sets the value for CacheTtl to be an explicit nil
func (o *CacheStatusResponse) SetCacheTtlNil() {
	o.CacheTtl.Set(nil)
}

// UnsetCacheTtl ensures that no value is present for CacheTtl, not even an explicit nil
func (o *CacheStatusResponse) UnsetCacheTtl() {
	o.CacheTtl.Unset()
}

// GetDcimConnected returns the DcimConnected field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CacheStatusResponse) GetDcimConnected() bool {
	if o == nil || IsNil(o.DcimConnected.Get()) {
		var ret bool
		return ret
	}
	return *o.DcimConnected.Get()
}

// GetDcimConnectedOk returns a tuple with the DcimConnected field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *CacheStatusResponse) GetDcimConnectedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.DcimConnected.Get(), o.DcimConnected.IsSet()
}

// HasDcimConnected returns a boolean if a field has been set.
func (o *CacheStatusResponse) HasDcimConnected() bool {
	if o != nil && o.DcimConnected.IsSet() {
		return true
	}

	return false
}

// SetDcimConnected gets a reference to the given NullableBool and assigns it to the DcimConnected field.
func (o *CacheStatusResponse) SetDcimConnected(v bool) {
	o.DcimConnected.Set(&v)
}

// SetDcimConnectedNil sets the value for DcimConnected to be an explicit nil
func (o *CacheStatusResponse) SetDcimConnectedNil() {
	o.DcimConnected.Set(nil)
}

// UnsetDcimConnected ensures that no value is present for DcimConnected, not even an explicit nil
func (o *CacheStatusResponse) UnsetDcimConnected() {
	o.DcimConnected.Unset()
}

// GetEnabled returns the Enabled field value
func (o *CacheStatusResponse) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *CacheStatusResponse) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *CacheStatusResponse) SetEnabled(v bool) {
	o.Enabled = v
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CacheStatusResponse) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *CacheStatusResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *CacheStatusResponse) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *CacheStatusResponse) SetMessage(v string) {
	o.Message.Set(&v)
}

// SetMessageNil sets the value for Message to be an explicit nil
func (o *CacheStatusResponse) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *CacheStatusResponse) UnsetMessage() {
	o.Message.Unset()
}

// GetNautobotConnected returns the NautobotConnected field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CacheStatusResponse) GetNautobotConnected() bool {
	if o == nil || IsNil(o.NautobotConnected.Get()) {
		var ret bool
		return ret
	}
	return *o.NautobotConnected.Get()
}

// GetNautobotConnectedOk returns a tuple with the NautobotConnected field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *CacheStatusResponse) GetNautobotConnectedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.NautobotConnected.Get(), o.NautobotConnected.IsSet()
}

// HasNautobotConnected returns a boolean if a field has been set.
func (o *CacheStatusResponse) HasNautobotConnected() bool {
	if o != nil && o.NautobotConnected.IsSet() {
		return true
	}

	return false
}

// SetNautobotConnected gets a reference to the given NullableBool and assigns it to the NautobotConnected field.
func (o *CacheStatusResponse) SetNautobotConnected(v bool) {
	o.NautobotConnected.Set(&v)
}

// SetNautobotConnectedNil sets the value for NautobotConnected to be an explicit nil
func (o *CacheStatusResponse) SetNautobotConnectedNil() {
	o.NautobotConnected.Set(nil)
}

// UnsetNautobotConnected ensures that no value is present for NautobotConnected, not even an explicit nil
func (o *CacheStatusResponse) UnsetNautobotConnected() {
	o.NautobotConnected.Unset()
}

// GetRedisConnected returns the RedisConnected field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CacheStatusResponse) GetRedisConnected() bool {
	if o == nil || IsNil(o.RedisConnected.Get()) {
		var ret bool
		return ret
	}
	return *o.RedisConnected.Get()
}

// GetRedisConnectedOk returns a tuple with the RedisConnected field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *CacheStatusResponse) GetRedisConnectedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RedisConnected.Get(), o.RedisConnected.IsSet()
}

// HasRedisConnected returns a boolean if a field has been set.
func (o *CacheStatusResponse) HasRedisConnected() bool {
	if o != nil && o.RedisConnected.IsSet() {
		return true
	}

	return false
}

// SetRedisConnected gets a reference to the given NullableBool and assigns it to the RedisConnected field.
func (o *CacheStatusResponse) SetRedisConnected(v bool) {
	o.RedisConnected.Set(&v)
}

// SetRedisConnectedNil sets the value for RedisConnected to be an explicit nil
func (o *CacheStatusResponse) SetRedisConnectedNil() {
	o.RedisConnected.Set(nil)
}

// UnsetRedisConnected ensures that no value is present for RedisConnected, not even an explicit nil
func (o *CacheStatusResponse) UnsetRedisConnected() {
	o.RedisConnected.Unset()
}

func (o CacheStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CacheTtl.IsSet() {
		toSerialize["cache_ttl"] = o.CacheTtl.Get()
	}
	if o.DcimConnected.IsSet() {
		toSerialize["dcim_connected"] = o.DcimConnected.Get()
	}
	toSerialize["enabled"] = o.Enabled
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	if o.NautobotConnected.IsSet() {
		toSerialize["nautobot_connected"] = o.NautobotConnected.Get()
	}
	if o.RedisConnected.IsSet() {
		toSerialize["redis_connected"] = o.RedisConnected.Get()
	}
	return toSerialize, nil
}

func (o *CacheStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"enabled": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCacheStatusResponse := _CacheStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCacheStatusResponse)

	if err != nil {
		return err
	}

	*o = CacheStatusResponse(varCacheStatusResponse)

	return err
}

type NullableCacheStatusResponse struct {
	value *CacheStatusResponse
	isSet bool
}

func (v NullableCacheStatusResponse) Get() *CacheStatusResponse {
	return v.value
}

func (v *NullableCacheStatusResponse) Set(val *CacheStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheStatusResponse(val *CacheStatusResponse) *NullableCacheStatusResponse {
	return &NullableCacheStatusResponse{value: val, isSet: true}
}

func (v NullableCacheStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
