/*
Config Store API

PostgreSQL-backed configuration storage service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configstore

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ConfigResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigResponse{}

// ConfigResponse Response with full config data.
type ConfigResponse struct {
	// Author email
	Author string `json:"author"`
	// Commit message
	CommitMessage string `json:"commit_message"`
	// Configuration file content
	Content string `json:"content"`
	// SHA256 hash of content
	ContentHash string `json:"content_hash"`
	// Timestamp when version was created
	CreatedAt time.Time `json:"created_at"`
	// Device metadata from the selected DCIM provider
	Device NullableDeviceMetadata `json:"device,omitempty"`
	// DCIM provider device identifier
	DeviceUuid string `json:"device_uuid"`
	// Config file type (intended or backup)
	FileType FileType `json:"file_type"`
	// File name
	Filename string `json:"filename"`
	// Config file ID
	Id string `json:"id"`
	// Version number
	Version int32 `json:"version"`
}

type _ConfigResponse ConfigResponse

// NewConfigResponse instantiates a new ConfigResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigResponse(author string, commitMessage string, content string, contentHash string, createdAt time.Time, deviceUuid string, fileType FileType, filename string, id string, version int32) *ConfigResponse {
	this := ConfigResponse{}
	this.Author = author
	this.CommitMessage = commitMessage
	this.Content = content
	this.ContentHash = contentHash
	this.CreatedAt = createdAt
	this.DeviceUuid = deviceUuid
	this.FileType = fileType
	this.Filename = filename
	this.Id = id
	this.Version = version
	return &this
}

// NewConfigResponseWithDefaults instantiates a new ConfigResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigResponseWithDefaults() *ConfigResponse {
	this := ConfigResponse{}
	return &this
}

// GetAuthor returns the Author field value
func (o *ConfigResponse) GetAuthor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Author
}

// GetAuthorOk returns a tuple with the Author field value
// and a boolean to check if the value has been set.
func (o *ConfigResponse) GetAuthorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Author, true
}

// SetAuthor sets field value
func (o *ConfigResponse) SetAuthor(v string) {
	o.Author = v
}

// GetCommitMessage returns the CommitMessage field value
func (o *ConfigResponse) GetCommitMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CommitMessage
}

// GetCommitMessageOk returns a tuple with the CommitMessage field value
// and a boolean to check if the value has been set.
func (o *ConfigResponse) GetCommitMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommitMessage, true
}

// SetCommitMessage sets field value
func (o *ConfigResponse) SetCommitMessage(v string) {
	o.CommitMessage = v
}

// GetContent returns the Content field value
func (o *ConfigResponse) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *ConfigResponse) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *ConfigResponse) SetContent(v string) {
	o.Content = v
}

// GetContentHash returns the ContentHash field value
func (o *ConfigResponse) GetContentHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentHash
}

// GetContentHashOk returns a tuple with the ContentHash field value
// and a boolean to check if the value has been set.
func (o *ConfigResponse) GetContentHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentHash, true
}

// SetContentHash sets field value
func (o *ConfigResponse) SetContentHash(v string) {
	o.ContentHash = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ConfigResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ConfigResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ConfigResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetDevice returns the Device field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConfigResponse) GetDevice() DeviceMetadata {
	if o == nil || IsNil(o.Device.Get()) {
		var ret DeviceMetadata
		return ret
	}
	return *o.Device.Get()
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *ConfigResponse) GetDeviceOk() (*DeviceMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return o.Device.Get(), o.Device.IsSet()
}

// HasDevice returns a boolean if a field has been set.
func (o *ConfigResponse) HasDevice() bool {
	if o != nil && o.Device.IsSet() {
		return true
	}

	return false
}

// SetDevice gets a reference to the given NullableDeviceMetadata and assigns it to the Device field.
func (o *ConfigResponse) SetDevice(v DeviceMetadata) {
	o.Device.Set(&v)
}

// SetDeviceNil sets the value for Device to be an explicit nil
func (o *ConfigResponse) SetDeviceNil() {
	o.Device.Set(nil)
}

// UnsetDevice ensures that no value is present for Device, not even an explicit nil
func (o *ConfigResponse) UnsetDevice() {
	o.Device.Unset()
}

// GetDeviceUuid returns the DeviceUuid field value
func (o *ConfigResponse) GetDeviceUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceUuid
}

// GetDeviceUuidOk returns a tuple with the DeviceUuid field value
// and a boolean to check if the value has been set.
func (o *ConfigResponse) GetDeviceUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceUuid, true
}

// SetDeviceUuid sets field value
func (o *ConfigResponse) SetDeviceUuid(v string) {
	o.DeviceUuid = v
}

// GetFileType returns the FileType field value
func (o *ConfigResponse) GetFileType() FileType {
	if o == nil {
		var ret FileType
		return ret
	}

	return o.FileType
}

// GetFileTypeOk returns a tuple with the FileType field value
// and a boolean to check if the value has been set.
func (o *ConfigResponse) GetFileTypeOk() (*FileType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileType, true
}

// SetFileType sets field value
func (o *ConfigResponse) SetFileType(v FileType) {
	o.FileType = v
}

// GetFilename returns the Filename field value
func (o *ConfigResponse) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *ConfigResponse) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *ConfigResponse) SetFilename(v string) {
	o.Filename = v
}

// GetId returns the Id field value
func (o *ConfigResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ConfigResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ConfigResponse) SetId(v string) {
	o.Id = v
}

// GetVersion returns the Version field value
func (o *ConfigResponse) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ConfigResponse) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ConfigResponse) SetVersion(v int32) {
	o.Version = v
}

func (o ConfigResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["author"] = o.Author
	toSerialize["commit_message"] = o.CommitMessage
	toSerialize["content"] = o.Content
	toSerialize["content_hash"] = o.ContentHash
	toSerialize["created_at"] = o.CreatedAt
	if o.Device.IsSet() {
		toSerialize["device"] = o.Device.Get()
	}
	toSerialize["device_uuid"] = o.DeviceUuid
	toSerialize["file_type"] = o.FileType
	toSerialize["filename"] = o.Filename
	toSerialize["id"] = o.Id
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *ConfigResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"author":         false,
		"commit_message": false,
		"content":        false,
		"content_hash":   false,
		"created_at":     false,
		"device_uuid":    false,
		"file_type":      false,
		"filename":       false,
		"id":             false,
		"version":        false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigResponse := _ConfigResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigResponse)

	if err != nil {
		return err
	}

	*o = ConfigResponse(varConfigResponse)

	return err
}

type NullableConfigResponse struct {
	value *ConfigResponse
	isSet bool
}

func (v NullableConfigResponse) Get() *ConfigResponse {
	return v.value
}

func (v *NullableConfigResponse) Set(val *ConfigResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigResponse(val *ConfigResponse) *NullableConfigResponse {
	return &NullableConfigResponse{value: val, isSet: true}
}

func (v NullableConfigResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
