/*
Config Store API

PostgreSQL-backed configuration storage service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configstore

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DeviceLatestConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceLatestConfig{}

// DeviceLatestConfig Device with its latest config metadata.
type DeviceLatestConfig struct {
	// Whether the device is currently active in nv-config-manager
	Active *bool `json:"active,omitempty"`
	// Author of latest change
	LatestAuthor string `json:"latest_author"`
	// Commit message of latest change
	LatestMessage string `json:"latest_message"`
	// Latest config update timestamp
	LatestUpdate string `json:"latest_update"`
	// Device name
	Name string `json:"name"`
	// Site name
	Site string `json:"site"`
	// DCIM provider device identifier
	Uuid string `json:"uuid"`
}

type _DeviceLatestConfig DeviceLatestConfig

// NewDeviceLatestConfig instantiates a new DeviceLatestConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceLatestConfig(latestAuthor string, latestMessage string, latestUpdate string, name string, site string, uuid string) *DeviceLatestConfig {
	this := DeviceLatestConfig{}
	var active bool = true
	this.Active = &active
	this.LatestAuthor = latestAuthor
	this.LatestMessage = latestMessage
	this.LatestUpdate = latestUpdate
	this.Name = name
	this.Site = site
	this.Uuid = uuid
	return &this
}

// NewDeviceLatestConfigWithDefaults instantiates a new DeviceLatestConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceLatestConfigWithDefaults() *DeviceLatestConfig {
	this := DeviceLatestConfig{}
	var active bool = true
	this.Active = &active
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *DeviceLatestConfig) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *DeviceLatestConfig) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *DeviceLatestConfig) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *DeviceLatestConfig) SetActive(v bool) {
	o.Active = &v
}

// GetLatestAuthor returns the LatestAuthor field value
func (o *DeviceLatestConfig) GetLatestAuthor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LatestAuthor
}

// GetLatestAuthorOk returns a tuple with the LatestAuthor field value
// and a boolean to check if the value has been set.
func (o *DeviceLatestConfig) GetLatestAuthorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LatestAuthor, true
}

// SetLatestAuthor sets field value
func (o *DeviceLatestConfig) SetLatestAuthor(v string) {
	o.LatestAuthor = v
}

// GetLatestMessage returns the LatestMessage field value
func (o *DeviceLatestConfig) GetLatestMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LatestMessage
}

// GetLatestMessageOk returns a tuple with the LatestMessage field value
// and a boolean to check if the value has been set.
func (o *DeviceLatestConfig) GetLatestMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LatestMessage, true
}

// SetLatestMessage sets field value
func (o *DeviceLatestConfig) SetLatestMessage(v string) {
	o.LatestMessage = v
}

// GetLatestUpdate returns the LatestUpdate field value
func (o *DeviceLatestConfig) GetLatestUpdate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LatestUpdate
}

// GetLatestUpdateOk returns a tuple with the LatestUpdate field value
// and a boolean to check if the value has been set.
func (o *DeviceLatestConfig) GetLatestUpdateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LatestUpdate, true
}

// SetLatestUpdate sets field value
func (o *DeviceLatestConfig) SetLatestUpdate(v string) {
	o.LatestUpdate = v
}

// GetName returns the Name field value
func (o *DeviceLatestConfig) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DeviceLatestConfig) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DeviceLatestConfig) SetName(v string) {
	o.Name = v
}

// GetSite returns the Site field value
func (o *DeviceLatestConfig) GetSite() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Site
}

// GetSiteOk returns a tuple with the Site field value
// and a boolean to check if the value has been set.
func (o *DeviceLatestConfig) GetSiteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Site, true
}

// SetSite sets field value
func (o *DeviceLatestConfig) SetSite(v string) {
	o.Site = v
}

// GetUuid returns the Uuid field value
func (o *DeviceLatestConfig) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *DeviceLatestConfig) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *DeviceLatestConfig) SetUuid(v string) {
	o.Uuid = v
}

func (o DeviceLatestConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceLatestConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	toSerialize["latest_author"] = o.LatestAuthor
	toSerialize["latest_message"] = o.LatestMessage
	toSerialize["latest_update"] = o.LatestUpdate
	toSerialize["name"] = o.Name
	toSerialize["site"] = o.Site
	toSerialize["uuid"] = o.Uuid
	return toSerialize, nil
}

func (o *DeviceLatestConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"latest_author":  false,
		"latest_message": false,
		"latest_update":  false,
		"name":           false,
		"site":           false,
		"uuid":           false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeviceLatestConfig := _DeviceLatestConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeviceLatestConfig)

	if err != nil {
		return err
	}

	*o = DeviceLatestConfig(varDeviceLatestConfig)

	return err
}

type NullableDeviceLatestConfig struct {
	value *DeviceLatestConfig
	isSet bool
}

func (v NullableDeviceLatestConfig) Get() *DeviceLatestConfig {
	return v.value
}

func (v *NullableDeviceLatestConfig) Set(val *DeviceLatestConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceLatestConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceLatestConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceLatestConfig(val *DeviceLatestConfig) *NullableDeviceLatestConfig {
	return &NullableDeviceLatestConfig{value: val, isSet: true}
}

func (v NullableDeviceLatestConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceLatestConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
