/*
Config Store API

PostgreSQL-backed configuration storage service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configstore

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ConfigCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigCreateRequest{}

// ConfigCreateRequest Request to create/update a config file.
type ConfigCreateRequest struct {
	// Author email
	Author string `json:"author"`
	// Commit message describing the change
	CommitMessage string `json:"commit_message"`
	// Configuration file content
	Content string `json:"content"`
	// Optional timestamp for the version (defaults to current time)
	CreatedAt NullableTime `json:"created_at,omitempty"`
	// Config file type (intended or backup)
	FileType *FileType `json:"file_type,omitempty"`
}

type _ConfigCreateRequest ConfigCreateRequest

// NewConfigCreateRequest instantiates a new ConfigCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigCreateRequest(author string, commitMessage string, content string) *ConfigCreateRequest {
	this := ConfigCreateRequest{}
	this.Author = author
	this.CommitMessage = commitMessage
	this.Content = content
	var fileType FileType = INTENDED
	this.FileType = &fileType
	return &this
}

// NewConfigCreateRequestWithDefaults instantiates a new ConfigCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigCreateRequestWithDefaults() *ConfigCreateRequest {
	this := ConfigCreateRequest{}
	var fileType FileType = INTENDED
	this.FileType = &fileType
	return &this
}

// GetAuthor returns the Author field value
func (o *ConfigCreateRequest) GetAuthor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Author
}

// GetAuthorOk returns a tuple with the Author field value
// and a boolean to check if the value has been set.
func (o *ConfigCreateRequest) GetAuthorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Author, true
}

// SetAuthor sets field value
func (o *ConfigCreateRequest) SetAuthor(v string) {
	o.Author = v
}

// GetCommitMessage returns the CommitMessage field value
func (o *ConfigCreateRequest) GetCommitMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CommitMessage
}

// GetCommitMessageOk returns a tuple with the CommitMessage field value
// and a boolean to check if the value has been set.
func (o *ConfigCreateRequest) GetCommitMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommitMessage, true
}

// SetCommitMessage sets field value
func (o *ConfigCreateRequest) SetCommitMessage(v string) {
	o.CommitMessage = v
}

// GetContent returns the Content field value
func (o *ConfigCreateRequest) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *ConfigCreateRequest) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *ConfigCreateRequest) SetContent(v string) {
	o.Content = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConfigCreateRequest) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt.Get()
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *ConfigCreateRequest) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAt.Get(), o.CreatedAt.IsSet()
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ConfigCreateRequest) HasCreatedAt() bool {
	if o != nil && o.CreatedAt.IsSet() {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given NullableTime and assigns it to the CreatedAt field.
func (o *ConfigCreateRequest) SetCreatedAt(v time.Time) {
	o.CreatedAt.Set(&v)
}

// SetCreatedAtNil sets the value for CreatedAt to be an explicit nil
func (o *ConfigCreateRequest) SetCreatedAtNil() {
	o.CreatedAt.Set(nil)
}

// UnsetCreatedAt ensures that no value is present for CreatedAt, not even an explicit nil
func (o *ConfigCreateRequest) UnsetCreatedAt() {
	o.CreatedAt.Unset()
}

// GetFileType returns the FileType field value if set, zero value otherwise.
func (o *ConfigCreateRequest) GetFileType() FileType {
	if o == nil || IsNil(o.FileType) {
		var ret FileType
		return ret
	}
	return *o.FileType
}

// GetFileTypeOk returns a tuple with the FileType field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *ConfigCreateRequest) GetFileTypeOk() (*FileType, bool) {
	if o == nil || IsNil(o.FileType) {
		return nil, false
	}
	return o.FileType, true
}

// HasFileType returns a boolean if a field has been set.
func (o *ConfigCreateRequest) HasFileType() bool {
	if o != nil && !IsNil(o.FileType) {
		return true
	}

	return false
}

// SetFileType gets a reference to the given FileType and assigns it to the FileType field.
func (o *ConfigCreateRequest) SetFileType(v FileType) {
	o.FileType = &v
}

func (o ConfigCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["author"] = o.Author
	toSerialize["commit_message"] = o.CommitMessage
	toSerialize["content"] = o.Content
	if o.CreatedAt.IsSet() {
		toSerialize["created_at"] = o.CreatedAt.Get()
	}
	if !IsNil(o.FileType) {
		toSerialize["file_type"] = o.FileType
	}
	return toSerialize, nil
}

func (o *ConfigCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"author":         false,
		"commit_message": false,
		"content":        false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigCreateRequest := _ConfigCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigCreateRequest)

	if err != nil {
		return err
	}

	*o = ConfigCreateRequest(varConfigCreateRequest)

	return err
}

type NullableConfigCreateRequest struct {
	value *ConfigCreateRequest
	isSet bool
}

func (v NullableConfigCreateRequest) Get() *ConfigCreateRequest {
	return v.value
}

func (v *NullableConfigCreateRequest) Set(val *ConfigCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigCreateRequest(val *ConfigCreateRequest) *NullableConfigCreateRequest {
	return &NullableConfigCreateRequest{value: val, isSet: true}
}

func (v NullableConfigCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
