/*
Config Store API

PostgreSQL-backed configuration storage service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configstore

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BatchConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchConfigRequest{}

// BatchConfigRequest Batch config creation request.
type BatchConfigRequest struct {
	// List of files to create/update
	Files []BatchConfigItem `json:"files"`
}

type _BatchConfigRequest BatchConfigRequest

// NewBatchConfigRequest instantiates a new BatchConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchConfigRequest(files []BatchConfigItem) *BatchConfigRequest {
	this := BatchConfigRequest{}
	this.Files = files
	return &this
}

// NewBatchConfigRequestWithDefaults instantiates a new BatchConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchConfigRequestWithDefaults() *BatchConfigRequest {
	this := BatchConfigRequest{}
	return &this
}

// GetFiles returns the Files field value
func (o *BatchConfigRequest) GetFiles() []BatchConfigItem {
	if o == nil {
		var ret []BatchConfigItem
		return ret
	}

	return o.Files
}

// GetFilesOk returns a tuple with the Files field value
// and a boolean to check if the value has been set.
func (o *BatchConfigRequest) GetFilesOk() ([]BatchConfigItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Files, true
}

// SetFiles sets field value
func (o *BatchConfigRequest) SetFiles(v []BatchConfigItem) {
	o.Files = v
}

func (o BatchConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["files"] = o.Files
	return toSerialize, nil
}

func (o *BatchConfigRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"files": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchConfigRequest := _BatchConfigRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchConfigRequest)

	if err != nil {
		return err
	}

	*o = BatchConfigRequest(varBatchConfigRequest)

	return err
}

type NullableBatchConfigRequest struct {
	value *BatchConfigRequest
	isSet bool
}

func (v NullableBatchConfigRequest) Get() *BatchConfigRequest {
	return v.value
}

func (v *NullableBatchConfigRequest) Set(val *BatchConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchConfigRequest(val *BatchConfigRequest) *NullableBatchConfigRequest {
	return &NullableBatchConfigRequest{value: val, isSet: true}
}

func (v NullableBatchConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
