/*
Config Store API

PostgreSQL-backed configuration storage service

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configstore

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the DeviceMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceMetadata{}

// DeviceMetadata Device metadata from the selected DCIM provider.
type DeviceMetadata struct {
	// Provider UI link for the device
	DeviceUrl NullableString `json:"device_url,omitempty"`
	// When metadata was last refreshed
	LastUpdated NullableTime `json:"last_updated,omitempty"`
	// Device name
	Name string `json:"name"`
	// Legacy alias for device_url when the selected provider is Nautobot
	NautobotUrl NullableString `json:"nautobot_url,omitempty"`
	// Platform/OS name
	Platform NullableString `json:"platform,omitempty"`
	// Primary IPv4 address
	PrimaryIp4 NullableString `json:"primary_ip4,omitempty"`
	// Rack name
	Rack NullableString `json:"rack,omitempty"`
	// Device role
	Role NullableString `json:"role,omitempty"`
	// Site name
	Site string `json:"site"`
}

type _DeviceMetadata DeviceMetadata

// NewDeviceMetadata instantiates a new DeviceMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceMetadata(name string, site string) *DeviceMetadata {
	this := DeviceMetadata{}
	this.Name = name
	this.Site = site
	return &this
}

// NewDeviceMetadataWithDefaults instantiates a new DeviceMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceMetadataWithDefaults() *DeviceMetadata {
	this := DeviceMetadata{}
	return &this
}

// GetDeviceUrl returns the DeviceUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceMetadata) GetDeviceUrl() string {
	if o == nil || IsNil(o.DeviceUrl.Get()) {
		var ret string
		return ret
	}
	return *o.DeviceUrl.Get()
}

// GetDeviceUrlOk returns a tuple with the DeviceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *DeviceMetadata) GetDeviceUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeviceUrl.Get(), o.DeviceUrl.IsSet()
}

// HasDeviceUrl returns a boolean if a field has been set.
func (o *DeviceMetadata) HasDeviceUrl() bool {
	if o != nil && o.DeviceUrl.IsSet() {
		return true
	}

	return false
}

// SetDeviceUrl gets a reference to the given NullableString and assigns it to the DeviceUrl field.
func (o *DeviceMetadata) SetDeviceUrl(v string) {
	o.DeviceUrl.Set(&v)
}

// SetDeviceUrlNil sets the value for DeviceUrl to be an explicit nil
func (o *DeviceMetadata) SetDeviceUrlNil() {
	o.DeviceUrl.Set(nil)
}

// UnsetDeviceUrl ensures that no value is present for DeviceUrl, not even an explicit nil
func (o *DeviceMetadata) UnsetDeviceUrl() {
	o.DeviceUrl.Unset()
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceMetadata) GetLastUpdated() time.Time {
	if o == nil || IsNil(o.LastUpdated.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastUpdated.Get()
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *DeviceMetadata) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdated.Get(), o.LastUpdated.IsSet()
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *DeviceMetadata) HasLastUpdated() bool {
	if o != nil && o.LastUpdated.IsSet() {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given NullableTime and assigns it to the LastUpdated field.
func (o *DeviceMetadata) SetLastUpdated(v time.Time) {
	o.LastUpdated.Set(&v)
}

// SetLastUpdatedNil sets the value for LastUpdated to be an explicit nil
func (o *DeviceMetadata) SetLastUpdatedNil() {
	o.LastUpdated.Set(nil)
}

// UnsetLastUpdated ensures that no value is present for LastUpdated, not even an explicit nil
func (o *DeviceMetadata) UnsetLastUpdated() {
	o.LastUpdated.Unset()
}

// GetName returns the Name field value
func (o *DeviceMetadata) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DeviceMetadata) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DeviceMetadata) SetName(v string) {
	o.Name = v
}

// GetNautobotUrl returns the NautobotUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceMetadata) GetNautobotUrl() string {
	if o == nil || IsNil(o.NautobotUrl.Get()) {
		var ret string
		return ret
	}
	return *o.NautobotUrl.Get()
}

// GetNautobotUrlOk returns a tuple with the NautobotUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *DeviceMetadata) GetNautobotUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NautobotUrl.Get(), o.NautobotUrl.IsSet()
}

// HasNautobotUrl returns a boolean if a field has been set.
func (o *DeviceMetadata) HasNautobotUrl() bool {
	if o != nil && o.NautobotUrl.IsSet() {
		return true
	}

	return false
}

// SetNautobotUrl gets a reference to the given NullableString and assigns it to the NautobotUrl field.
func (o *DeviceMetadata) SetNautobotUrl(v string) {
	o.NautobotUrl.Set(&v)
}

// SetNautobotUrlNil sets the value for NautobotUrl to be an explicit nil
func (o *DeviceMetadata) SetNautobotUrlNil() {
	o.NautobotUrl.Set(nil)
}

// UnsetNautobotUrl ensures that no value is present for NautobotUrl, not even an explicit nil
func (o *DeviceMetadata) UnsetNautobotUrl() {
	o.NautobotUrl.Unset()
}

// GetPlatform returns the Platform field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceMetadata) GetPlatform() string {
	if o == nil || IsNil(o.Platform.Get()) {
		var ret string
		return ret
	}
	return *o.Platform.Get()
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *DeviceMetadata) GetPlatformOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Platform.Get(), o.Platform.IsSet()
}

// HasPlatform returns a boolean if a field has been set.
func (o *DeviceMetadata) HasPlatform() bool {
	if o != nil && o.Platform.IsSet() {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given NullableString and assigns it to the Platform field.
func (o *DeviceMetadata) SetPlatform(v string) {
	o.Platform.Set(&v)
}

// SetPlatformNil sets the value for Platform to be an explicit nil
func (o *DeviceMetadata) SetPlatformNil() {
	o.Platform.Set(nil)
}

// UnsetPlatform ensures that no value is present for Platform, not even an explicit nil
func (o *DeviceMetadata) UnsetPlatform() {
	o.Platform.Unset()
}

// GetPrimaryIp4 returns the PrimaryIp4 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceMetadata) GetPrimaryIp4() string {
	if o == nil || IsNil(o.PrimaryIp4.Get()) {
		var ret string
		return ret
	}
	return *o.PrimaryIp4.Get()
}

// GetPrimaryIp4Ok returns a tuple with the PrimaryIp4 field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *DeviceMetadata) GetPrimaryIp4Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrimaryIp4.Get(), o.PrimaryIp4.IsSet()
}

// HasPrimaryIp4 returns a boolean if a field has been set.
func (o *DeviceMetadata) HasPrimaryIp4() bool {
	if o != nil && o.PrimaryIp4.IsSet() {
		return true
	}

	return false
}

// SetPrimaryIp4 gets a reference to the given NullableString and assigns it to the PrimaryIp4 field.
func (o *DeviceMetadata) SetPrimaryIp4(v string) {
	o.PrimaryIp4.Set(&v)
}

// SetPrimaryIp4Nil sets the value for PrimaryIp4 to be an explicit nil
func (o *DeviceMetadata) SetPrimaryIp4Nil() {
	o.PrimaryIp4.Set(nil)
}

// UnsetPrimaryIp4 ensures that no value is present for PrimaryIp4, not even an explicit nil
func (o *DeviceMetadata) UnsetPrimaryIp4() {
	o.PrimaryIp4.Unset()
}

// GetRack returns the Rack field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceMetadata) GetRack() string {
	if o == nil || IsNil(o.Rack.Get()) {
		var ret string
		return ret
	}
	return *o.Rack.Get()
}

// GetRackOk returns a tuple with the Rack field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *DeviceMetadata) GetRackOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rack.Get(), o.Rack.IsSet()
}

// HasRack returns a boolean if a field has been set.
func (o *DeviceMetadata) HasRack() bool {
	if o != nil && o.Rack.IsSet() {
		return true
	}

	return false
}

// SetRack gets a reference to the given NullableString and assigns it to the Rack field.
func (o *DeviceMetadata) SetRack(v string) {
	o.Rack.Set(&v)
}

// SetRackNil sets the value for Rack to be an explicit nil
func (o *DeviceMetadata) SetRackNil() {
	o.Rack.Set(nil)
}

// UnsetRack ensures that no value is present for Rack, not even an explicit nil
func (o *DeviceMetadata) UnsetRack() {
	o.Rack.Unset()
}

// GetRole returns the Role field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeviceMetadata) GetRole() string {
	if o == nil || IsNil(o.Role.Get()) {
		var ret string
		return ret
	}
	return *o.Role.Get()
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *DeviceMetadata) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Role.Get(), o.Role.IsSet()
}

// HasRole returns a boolean if a field has been set.
func (o *DeviceMetadata) HasRole() bool {
	if o != nil && o.Role.IsSet() {
		return true
	}

	return false
}

// SetRole gets a reference to the given NullableString and assigns it to the Role field.
func (o *DeviceMetadata) SetRole(v string) {
	o.Role.Set(&v)
}

// SetRoleNil sets the value for Role to be an explicit nil
func (o *DeviceMetadata) SetRoleNil() {
	o.Role.Set(nil)
}

// UnsetRole ensures that no value is present for Role, not even an explicit nil
func (o *DeviceMetadata) UnsetRole() {
	o.Role.Unset()
}

// GetSite returns the Site field value
func (o *DeviceMetadata) GetSite() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Site
}

// GetSiteOk returns a tuple with the Site field value
// and a boolean to check if the value has been set.
func (o *DeviceMetadata) GetSiteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Site, true
}

// SetSite sets field value
func (o *DeviceMetadata) SetSite(v string) {
	o.Site = v
}

func (o DeviceMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DeviceUrl.IsSet() {
		toSerialize["device_url"] = o.DeviceUrl.Get()
	}
	if o.LastUpdated.IsSet() {
		toSerialize["last_updated"] = o.LastUpdated.Get()
	}
	toSerialize["name"] = o.Name
	if o.NautobotUrl.IsSet() {
		toSerialize["nautobot_url"] = o.NautobotUrl.Get()
	}
	if o.Platform.IsSet() {
		toSerialize["platform"] = o.Platform.Get()
	}
	if o.PrimaryIp4.IsSet() {
		toSerialize["primary_ip4"] = o.PrimaryIp4.Get()
	}
	if o.Rack.IsSet() {
		toSerialize["rack"] = o.Rack.Get()
	}
	if o.Role.IsSet() {
		toSerialize["role"] = o.Role.Get()
	}
	toSerialize["site"] = o.Site
	return toSerialize, nil
}

func (o *DeviceMetadata) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"name": false,
		"site": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeviceMetadata := _DeviceMetadata{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeviceMetadata)

	if err != nil {
		return err
	}

	*o = DeviceMetadata(varDeviceMetadata)

	return err
}

type NullableDeviceMetadata struct {
	value *DeviceMetadata
	isSet bool
}

func (v NullableDeviceMetadata) Get() *DeviceMetadata {
	return v.value
}

func (v *NullableDeviceMetadata) Set(val *DeviceMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceMetadata(val *DeviceMetadata) *NullableDeviceMetadata {
	return &NullableDeviceMetadata{value: val, isSet: true}
}

func (v NullableDeviceMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
