/*
Render API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ConsumerInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsumerInfo{}

// ConsumerInfo Consumer information model.
type ConsumerInfo struct {
	Name          string `json:"name"`
	NumAckPending int32  `json:"num_ack_pending"`
	NumDelivered  int32  `json:"num_delivered"`
	NumPending    int32  `json:"num_pending"`
	Stream        string `json:"stream"`
	Subject       string `json:"subject"`
}

type _ConsumerInfo ConsumerInfo

// NewConsumerInfo instantiates a new ConsumerInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsumerInfo(name string, numAckPending int32, numDelivered int32, numPending int32, stream string, subject string) *ConsumerInfo {
	this := ConsumerInfo{}
	this.Name = name
	this.NumAckPending = numAckPending
	this.NumDelivered = numDelivered
	this.NumPending = numPending
	this.Stream = stream
	this.Subject = subject
	return &this
}

// NewConsumerInfoWithDefaults instantiates a new ConsumerInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsumerInfoWithDefaults() *ConsumerInfo {
	this := ConsumerInfo{}
	return &this
}

// GetName returns the Name field value
func (o *ConsumerInfo) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConsumerInfo) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConsumerInfo) SetName(v string) {
	o.Name = v
}

// GetNumAckPending returns the NumAckPending field value
func (o *ConsumerInfo) GetNumAckPending() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NumAckPending
}

// GetNumAckPendingOk returns a tuple with the NumAckPending field value
// and a boolean to check if the value has been set.
func (o *ConsumerInfo) GetNumAckPendingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumAckPending, true
}

// SetNumAckPending sets field value
func (o *ConsumerInfo) SetNumAckPending(v int32) {
	o.NumAckPending = v
}

// GetNumDelivered returns the NumDelivered field value
func (o *ConsumerInfo) GetNumDelivered() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NumDelivered
}

// GetNumDeliveredOk returns a tuple with the NumDelivered field value
// and a boolean to check if the value has been set.
func (o *ConsumerInfo) GetNumDeliveredOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumDelivered, true
}

// SetNumDelivered sets field value
func (o *ConsumerInfo) SetNumDelivered(v int32) {
	o.NumDelivered = v
}

// GetNumPending returns the NumPending field value
func (o *ConsumerInfo) GetNumPending() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NumPending
}

// GetNumPendingOk returns a tuple with the NumPending field value
// and a boolean to check if the value has been set.
func (o *ConsumerInfo) GetNumPendingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumPending, true
}

// SetNumPending sets field value
func (o *ConsumerInfo) SetNumPending(v int32) {
	o.NumPending = v
}

// GetStream returns the Stream field value
func (o *ConsumerInfo) GetStream() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Stream
}

// GetStreamOk returns a tuple with the Stream field value
// and a boolean to check if the value has been set.
func (o *ConsumerInfo) GetStreamOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stream, true
}

// SetStream sets field value
func (o *ConsumerInfo) SetStream(v string) {
	o.Stream = v
}

// GetSubject returns the Subject field value
func (o *ConsumerInfo) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *ConsumerInfo) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *ConsumerInfo) SetSubject(v string) {
	o.Subject = v
}

func (o ConsumerInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsumerInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["num_ack_pending"] = o.NumAckPending
	toSerialize["num_delivered"] = o.NumDelivered
	toSerialize["num_pending"] = o.NumPending
	toSerialize["stream"] = o.Stream
	toSerialize["subject"] = o.Subject
	return toSerialize, nil
}

func (o *ConsumerInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"name":            false,
		"num_ack_pending": false,
		"num_delivered":   false,
		"num_pending":     false,
		"stream":          false,
		"subject":         false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConsumerInfo := _ConsumerInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConsumerInfo)

	if err != nil {
		return err
	}

	*o = ConsumerInfo(varConsumerInfo)

	return err
}

type NullableConsumerInfo struct {
	value *ConsumerInfo
	isSet bool
}

func (v NullableConsumerInfo) Get() *ConsumerInfo {
	return v.value
}

func (v *NullableConsumerInfo) Set(val *ConsumerInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableConsumerInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableConsumerInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsumerInfo(val *ConsumerInfo) *NullableConsumerInfo {
	return &NullableConsumerInfo{value: val, isSet: true}
}

func (v NullableConsumerInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsumerInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
