/*
Render API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"encoding/json"
)

// checks if the RenderResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RenderResponse{}

// RenderResponse Response from a single device render operation.
type RenderResponse struct {
	// Files that changed during the render
	UpdatedFiles []FileCommit `json:"updated_files,omitempty"`
}

// NewRenderResponse instantiates a new RenderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRenderResponse() *RenderResponse {
	this := RenderResponse{}
	return &this
}

// NewRenderResponseWithDefaults instantiates a new RenderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRenderResponseWithDefaults() *RenderResponse {
	this := RenderResponse{}
	return &this
}

// GetUpdatedFiles returns the UpdatedFiles field value if set, zero value otherwise.
func (o *RenderResponse) GetUpdatedFiles() []FileCommit {
	if o == nil || IsNil(o.UpdatedFiles) {
		var ret []FileCommit
		return ret
	}
	return o.UpdatedFiles
}

// GetUpdatedFilesOk returns a tuple with the UpdatedFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *RenderResponse) GetUpdatedFilesOk() ([]FileCommit, bool) {
	if o == nil || IsNil(o.UpdatedFiles) {
		return nil, false
	}
	return o.UpdatedFiles, true
}

// HasUpdatedFiles returns a boolean if a field has been set.
func (o *RenderResponse) HasUpdatedFiles() bool {
	if o != nil && !IsNil(o.UpdatedFiles) {
		return true
	}

	return false
}

// SetUpdatedFiles gets a reference to the given []FileCommit and assigns it to the UpdatedFiles field.
func (o *RenderResponse) SetUpdatedFiles(v []FileCommit) {
	o.UpdatedFiles = v
}

func (o RenderResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RenderResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UpdatedFiles) {
		toSerialize["updated_files"] = o.UpdatedFiles
	}
	return toSerialize, nil
}

type NullableRenderResponse struct {
	value *RenderResponse
	isSet bool
}

func (v NullableRenderResponse) Get() *RenderResponse {
	return v.value
}

func (v *NullableRenderResponse) Set(val *RenderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRenderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRenderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRenderResponse(val *RenderResponse) *NullableRenderResponse {
	return &NullableRenderResponse{value: val, isSet: true}
}

func (v NullableRenderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRenderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
