/*
Render API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ConsumerListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsumerListResponse{}

// ConsumerListResponse Consumer list response model.
type ConsumerListResponse struct {
	Consumers []ConsumerInfo `json:"consumers"`
}

type _ConsumerListResponse ConsumerListResponse

// NewConsumerListResponse instantiates a new ConsumerListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsumerListResponse(consumers []ConsumerInfo) *ConsumerListResponse {
	this := ConsumerListResponse{}
	this.Consumers = consumers
	return &this
}

// NewConsumerListResponseWithDefaults instantiates a new ConsumerListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsumerListResponseWithDefaults() *ConsumerListResponse {
	this := ConsumerListResponse{}
	return &this
}

// GetConsumers returns the Consumers field value
func (o *ConsumerListResponse) GetConsumers() []ConsumerInfo {
	if o == nil {
		var ret []ConsumerInfo
		return ret
	}

	return o.Consumers
}

// GetConsumersOk returns a tuple with the Consumers field value
// and a boolean to check if the value has been set.
func (o *ConsumerListResponse) GetConsumersOk() ([]ConsumerInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Consumers, true
}

// SetConsumers sets field value
func (o *ConsumerListResponse) SetConsumers(v []ConsumerInfo) {
	o.Consumers = v
}

func (o ConsumerListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsumerListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["consumers"] = o.Consumers
	return toSerialize, nil
}

func (o *ConsumerListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"consumers": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConsumerListResponse := _ConsumerListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConsumerListResponse)

	if err != nil {
		return err
	}

	*o = ConsumerListResponse(varConsumerListResponse)

	return err
}

type NullableConsumerListResponse struct {
	value *ConsumerListResponse
	isSet bool
}

func (v NullableConsumerListResponse) Get() *ConsumerListResponse {
	return v.value
}

func (v *NullableConsumerListResponse) Set(val *ConsumerListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConsumerListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConsumerListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsumerListResponse(val *ConsumerListResponse) *NullableConsumerListResponse {
	return &NullableConsumerListResponse{value: val, isSet: true}
}

func (v NullableConsumerListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsumerListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
