/*
Render API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the FileCommit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileCommit{}

// FileCommit A rendered file and the config store commit it produced.
type FileCommit struct {
	Commit   string `json:"commit"`
	Filename string `json:"filename"`
}

type _FileCommit FileCommit

// NewFileCommit instantiates a new FileCommit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileCommit(commit string, filename string) *FileCommit {
	this := FileCommit{}
	this.Commit = commit
	this.Filename = filename
	return &this
}

// NewFileCommitWithDefaults instantiates a new FileCommit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileCommitWithDefaults() *FileCommit {
	this := FileCommit{}
	return &this
}

// GetCommit returns the Commit field value
func (o *FileCommit) GetCommit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Commit
}

// GetCommitOk returns a tuple with the Commit field value
// and a boolean to check if the value has been set.
func (o *FileCommit) GetCommitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Commit, true
}

// SetCommit sets field value
func (o *FileCommit) SetCommit(v string) {
	o.Commit = v
}

// GetFilename returns the Filename field value
func (o *FileCommit) GetFilename() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value
// and a boolean to check if the value has been set.
func (o *FileCommit) GetFilenameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filename, true
}

// SetFilename sets field value
func (o *FileCommit) SetFilename(v string) {
	o.Filename = v
}

func (o FileCommit) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileCommit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["commit"] = o.Commit
	toSerialize["filename"] = o.Filename
	return toSerialize, nil
}

func (o *FileCommit) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"commit":   false,
		"filename": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFileCommit := _FileCommit{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFileCommit)

	if err != nil {
		return err
	}

	*o = FileCommit(varFileCommit)

	return err
}

type NullableFileCommit struct {
	value *FileCommit
	isSet bool
}

func (v NullableFileCommit) Get() *FileCommit {
	return v.value
}

func (v *NullableFileCommit) Set(val *FileCommit) {
	v.value = val
	v.isSet = true
}

func (v NullableFileCommit) IsSet() bool {
	return v.isSet
}

func (v *NullableFileCommit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileCommit(val *FileCommit) *NullableFileCommit {
	return &NullableFileCommit{value: val, isSet: true}
}

func (v NullableFileCommit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileCommit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
