/*
Render API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BatchRenderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchRenderRequest{}

// BatchRenderRequest Request body for a batch render operation.
type BatchRenderRequest struct {
	CommitMessage  NullableString `json:"commit_message,omitempty"`
	DeviceUuids    []string       `json:"device_uuids"`
	MaxConcurrency *int32         `json:"max_concurrency,omitempty"`
}

type _BatchRenderRequest BatchRenderRequest

// NewBatchRenderRequest instantiates a new BatchRenderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchRenderRequest(deviceUuids []string) *BatchRenderRequest {
	this := BatchRenderRequest{}
	this.DeviceUuids = deviceUuids
	var maxConcurrency int32 = 20
	this.MaxConcurrency = &maxConcurrency
	return &this
}

// NewBatchRenderRequestWithDefaults instantiates a new BatchRenderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchRenderRequestWithDefaults() *BatchRenderRequest {
	this := BatchRenderRequest{}
	var maxConcurrency int32 = 20
	this.MaxConcurrency = &maxConcurrency
	return &this
}

// GetCommitMessage returns the CommitMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BatchRenderRequest) GetCommitMessage() string {
	if o == nil || IsNil(o.CommitMessage.Get()) {
		var ret string
		return ret
	}
	return *o.CommitMessage.Get()
}

// GetCommitMessageOk returns a tuple with the CommitMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *BatchRenderRequest) GetCommitMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CommitMessage.Get(), o.CommitMessage.IsSet()
}

// HasCommitMessage returns a boolean if a field has been set.
func (o *BatchRenderRequest) HasCommitMessage() bool {
	if o != nil && o.CommitMessage.IsSet() {
		return true
	}

	return false
}

// SetCommitMessage gets a reference to the given NullableString and assigns it to the CommitMessage field.
func (o *BatchRenderRequest) SetCommitMessage(v string) {
	o.CommitMessage.Set(&v)
}

// SetCommitMessageNil sets the value for CommitMessage to be an explicit nil
func (o *BatchRenderRequest) SetCommitMessageNil() {
	o.CommitMessage.Set(nil)
}

// UnsetCommitMessage ensures that no value is present for CommitMessage, not even an explicit nil
func (o *BatchRenderRequest) UnsetCommitMessage() {
	o.CommitMessage.Unset()
}

// GetDeviceUuids returns the DeviceUuids field value
func (o *BatchRenderRequest) GetDeviceUuids() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.DeviceUuids
}

// GetDeviceUuidsOk returns a tuple with the DeviceUuids field value
// and a boolean to check if the value has been set.
func (o *BatchRenderRequest) GetDeviceUuidsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeviceUuids, true
}

// SetDeviceUuids sets field value
func (o *BatchRenderRequest) SetDeviceUuids(v []string) {
	o.DeviceUuids = v
}

// GetMaxConcurrency returns the MaxConcurrency field value if set, zero value otherwise.
func (o *BatchRenderRequest) GetMaxConcurrency() int32 {
	if o == nil || IsNil(o.MaxConcurrency) {
		var ret int32
		return ret
	}
	return *o.MaxConcurrency
}

// GetMaxConcurrencyOk returns a tuple with the MaxConcurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *BatchRenderRequest) GetMaxConcurrencyOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxConcurrency) {
		return nil, false
	}
	return o.MaxConcurrency, true
}

// HasMaxConcurrency returns a boolean if a field has been set.
func (o *BatchRenderRequest) HasMaxConcurrency() bool {
	if o != nil && !IsNil(o.MaxConcurrency) {
		return true
	}

	return false
}

// SetMaxConcurrency gets a reference to the given int32 and assigns it to the MaxConcurrency field.
func (o *BatchRenderRequest) SetMaxConcurrency(v int32) {
	o.MaxConcurrency = &v
}

func (o BatchRenderRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchRenderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CommitMessage.IsSet() {
		toSerialize["commit_message"] = o.CommitMessage.Get()
	}
	toSerialize["device_uuids"] = o.DeviceUuids
	if !IsNil(o.MaxConcurrency) {
		toSerialize["max_concurrency"] = o.MaxConcurrency
	}
	return toSerialize, nil
}

func (o *BatchRenderRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"device_uuids": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchRenderRequest := _BatchRenderRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchRenderRequest)

	if err != nil {
		return err
	}

	*o = BatchRenderRequest(varBatchRenderRequest)

	return err
}

type NullableBatchRenderRequest struct {
	value *BatchRenderRequest
	isSet bool
}

func (v NullableBatchRenderRequest) Get() *BatchRenderRequest {
	return v.value
}

func (v *NullableBatchRenderRequest) Set(val *BatchRenderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchRenderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchRenderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchRenderRequest(val *BatchRenderRequest) *NullableBatchRenderRequest {
	return &NullableBatchRenderRequest{value: val, isSet: true}
}

func (v NullableBatchRenderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchRenderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
