/*
Render API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package render

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BulkRenderResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkRenderResponse{}

// BulkRenderResponse Response from a bulk render operation (render-all or batch).
type BulkRenderResponse struct {
	// Devices that failed to queue
	FailedDevices []FailedDevice `json:"failed_devices,omitempty"`
	// Maximum concurrent renders (batch only)
	MaxConcurrency NullableInt32 `json:"max_concurrency,omitempty"`
	Message        string        `json:"message"`
	QueuedCount    int32         `json:"queued_count"`
	// Total number of devices targeted
	TotalDevices *int32 `json:"total_devices,omitempty"`
}

type _BulkRenderResponse BulkRenderResponse

// NewBulkRenderResponse instantiates a new BulkRenderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkRenderResponse(message string, queuedCount int32) *BulkRenderResponse {
	this := BulkRenderResponse{}
	this.Message = message
	this.QueuedCount = queuedCount
	var totalDevices int32 = 0
	this.TotalDevices = &totalDevices
	return &this
}

// NewBulkRenderResponseWithDefaults instantiates a new BulkRenderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkRenderResponseWithDefaults() *BulkRenderResponse {
	this := BulkRenderResponse{}
	var totalDevices int32 = 0
	this.TotalDevices = &totalDevices
	return &this
}

// GetFailedDevices returns the FailedDevices field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkRenderResponse) GetFailedDevices() []FailedDevice {
	if o == nil {
		var ret []FailedDevice
		return ret
	}
	return o.FailedDevices
}

// GetFailedDevicesOk returns a tuple with the FailedDevices field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *BulkRenderResponse) GetFailedDevicesOk() ([]FailedDevice, bool) {
	if o == nil || IsNil(o.FailedDevices) {
		return nil, false
	}
	return o.FailedDevices, true
}

// HasFailedDevices returns a boolean if a field has been set.
func (o *BulkRenderResponse) HasFailedDevices() bool {
	if o != nil && !IsNil(o.FailedDevices) {
		return true
	}

	return false
}

// SetFailedDevices gets a reference to the given []FailedDevice and assigns it to the FailedDevices field.
func (o *BulkRenderResponse) SetFailedDevices(v []FailedDevice) {
	o.FailedDevices = v
}

// GetMaxConcurrency returns the MaxConcurrency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkRenderResponse) GetMaxConcurrency() int32 {
	if o == nil || IsNil(o.MaxConcurrency.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxConcurrency.Get()
}

// GetMaxConcurrencyOk returns a tuple with the MaxConcurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *BulkRenderResponse) GetMaxConcurrencyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxConcurrency.Get(), o.MaxConcurrency.IsSet()
}

// HasMaxConcurrency returns a boolean if a field has been set.
func (o *BulkRenderResponse) HasMaxConcurrency() bool {
	if o != nil && o.MaxConcurrency.IsSet() {
		return true
	}

	return false
}

// SetMaxConcurrency gets a reference to the given NullableInt32 and assigns it to the MaxConcurrency field.
func (o *BulkRenderResponse) SetMaxConcurrency(v int32) {
	o.MaxConcurrency.Set(&v)
}

// SetMaxConcurrencyNil sets the value for MaxConcurrency to be an explicit nil
func (o *BulkRenderResponse) SetMaxConcurrencyNil() {
	o.MaxConcurrency.Set(nil)
}

// UnsetMaxConcurrency ensures that no value is present for MaxConcurrency, not even an explicit nil
func (o *BulkRenderResponse) UnsetMaxConcurrency() {
	o.MaxConcurrency.Unset()
}

// GetMessage returns the Message field value
func (o *BulkRenderResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *BulkRenderResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *BulkRenderResponse) SetMessage(v string) {
	o.Message = v
}

// GetQueuedCount returns the QueuedCount field value
func (o *BulkRenderResponse) GetQueuedCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.QueuedCount
}

// GetQueuedCountOk returns a tuple with the QueuedCount field value
// and a boolean to check if the value has been set.
func (o *BulkRenderResponse) GetQueuedCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QueuedCount, true
}

// SetQueuedCount sets field value
func (o *BulkRenderResponse) SetQueuedCount(v int32) {
	o.QueuedCount = v
}

// GetTotalDevices returns the TotalDevices field value if set, zero value otherwise.
func (o *BulkRenderResponse) GetTotalDevices() int32 {
	if o == nil || IsNil(o.TotalDevices) {
		var ret int32
		return ret
	}
	return *o.TotalDevices
}

// GetTotalDevicesOk returns a tuple with the TotalDevices field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *BulkRenderResponse) GetTotalDevicesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalDevices) {
		return nil, false
	}
	return o.TotalDevices, true
}

// HasTotalDevices returns a boolean if a field has been set.
func (o *BulkRenderResponse) HasTotalDevices() bool {
	if o != nil && !IsNil(o.TotalDevices) {
		return true
	}

	return false
}

// SetTotalDevices gets a reference to the given int32 and assigns it to the TotalDevices field.
func (o *BulkRenderResponse) SetTotalDevices(v int32) {
	o.TotalDevices = &v
}

func (o BulkRenderResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkRenderResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.FailedDevices != nil {
		toSerialize["failed_devices"] = o.FailedDevices
	}
	if o.MaxConcurrency.IsSet() {
		toSerialize["max_concurrency"] = o.MaxConcurrency.Get()
	}
	toSerialize["message"] = o.Message
	toSerialize["queued_count"] = o.QueuedCount
	if !IsNil(o.TotalDevices) {
		toSerialize["total_devices"] = o.TotalDevices
	}
	return toSerialize, nil
}

func (o *BulkRenderResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"message":      false,
		"queued_count": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkRenderResponse := _BulkRenderResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkRenderResponse)

	if err != nil {
		return err
	}

	*o = BulkRenderResponse(varBulkRenderResponse)

	return err
}

type NullableBulkRenderResponse struct {
	value *BulkRenderResponse
	isSet bool
}

func (v NullableBulkRenderResponse) Get() *BulkRenderResponse {
	return v.value
}

func (v *NullableBulkRenderResponse) Set(val *BulkRenderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkRenderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkRenderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkRenderResponse(val *BulkRenderResponse) *NullableBulkRenderResponse {
	return &NullableBulkRenderResponse{value: val, isSet: true}
}

func (v NullableBulkRenderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkRenderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
