# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Public, versioned API for NVIDIA Config Manager DCIM providers."""

from nv_config_manager_dcim import (
    DeviceRenderData,
    LocationRenderData,
    RenderData,
    RenderDataRequest,
    RenderDataRequirement,
    RenderDeviceIdentity,
    RenderLocation,
)

from nv_config_manager.dcim.api import (
    DCIM_PROVIDER_API_VERSION,
    DCIMClient,
    DCIMEventProvider,
    DCIMProvider,
    DCIMProviderMetadata,
    DCIMRenderEventHandler,
    DCIMRenderEventProvider,
    DCIMRenderEventRegistry,
    NautobotMCPClient,
    NautobotMCPProvider,
    ProviderSettings,
)
from nv_config_manager.dcim.errors import (
    DCIMAuthenticationError,
    DCIMAuthorizationError,
    DCIMConflictError,
    DCIMConnectivityError,
    DCIMError,
    DCIMInvalidDataError,
    DCIMNotFoundError,
    DCIMOperationNotSupportedError,
    DCIMProviderCompatibilityError,
    DCIMProviderConfigurationError,
    DCIMProviderDiscoveryError,
    DCIMProviderDuplicateError,
    DCIMProviderError,
    DCIMProviderInitializationError,
    DCIMProviderNotFoundError,
)
from nv_config_manager.dcim.models import (
    DCIM_EVENT_CONTRACT_VERSION,
    ConfigurationBackupIntent,
    ConfigurationBackupMetadata,
    DCIMChangeEvent,
    DCIMDeviceSelection,
    DCIMDeviceSelectionFilter,
    DCIMSelection,
    DeviceMetadata,
    DeviceVRF,
    FirmwareBundle,
    FirmwareComponent,
    HostInterfaceMetadata,
    HostMetadata,
    IBHostSite,
    IBInterfaceGuid,
    IBNeighbor,
    IBPKeyAssignment,
    IBPKeyCleanup,
    IBPKeyContext,
    IBPKeyPartition,
    IBSwitchTopology,
    IntendedConfigurationUpdate,
    IntendedInterfaceNeighbor,
    IntendedNeighborDevice,
    NamespaceRouteDistinguisher,
    RenderDeviceStatus,
    RenderEventRequest,
    RenderTemplateVersion,
    SpectrumXVRF,
    ZTPDevice,
)
from nv_config_manager.dcim.registry import (
    DCIM_PROVIDER_ENTRY_POINT_GROUP,
    DEFAULT_DCIM_PROVIDER,
    configured_dcim_provider_name,
    create_dcim_client,
    create_nautobot_mcp_client,
    dcim_client_session,
    discover_dcim_providers,
    get_dcim_provider,
    normalize_dcim_event,
    provider_settings,
    supports_nautobot_mcp,
)

__all__ = [
    "DCIM_PROVIDER_API_VERSION",
    "DCIM_EVENT_CONTRACT_VERSION",
    "DCIM_PROVIDER_ENTRY_POINT_GROUP",
    "DEFAULT_DCIM_PROVIDER",
    "DCIMAuthenticationError",
    "DCIMAuthorizationError",
    "DCIMClient",
    "DCIMChangeEvent",
    "DCIMDeviceSelection",
    "DCIMDeviceSelectionFilter",
    "DCIMConflictError",
    "DCIMConnectivityError",
    "DCIMError",
    "DCIMEventProvider",
    "DCIMRenderEventHandler",
    "DCIMRenderEventProvider",
    "DCIMRenderEventRegistry",
    "DCIMInvalidDataError",
    "DCIMNotFoundError",
    "DCIMOperationNotSupportedError",
    "DCIMProvider",
    "DCIMProviderCompatibilityError",
    "DCIMProviderConfigurationError",
    "DCIMProviderDiscoveryError",
    "DCIMProviderDuplicateError",
    "DCIMProviderError",
    "DCIMProviderInitializationError",
    "DCIMProviderMetadata",
    "DCIMProviderNotFoundError",
    "DCIMSelection",
    "ConfigurationBackupIntent",
    "ConfigurationBackupMetadata",
    "DeviceMetadata",
    "DeviceVRF",
    "FirmwareBundle",
    "FirmwareComponent",
    "HostInterfaceMetadata",
    "HostMetadata",
    "IBHostSite",
    "IBInterfaceGuid",
    "IBPKeyAssignment",
    "IBPKeyCleanup",
    "IBPKeyContext",
    "IBPKeyPartition",
    "IBNeighbor",
    "IBSwitchTopology",
    "IntendedConfigurationUpdate",
    "IntendedInterfaceNeighbor",
    "IntendedNeighborDevice",
    "NautobotMCPClient",
    "NautobotMCPProvider",
    "ProviderSettings",
    "NamespaceRouteDistinguisher",
    "DeviceRenderData",
    "LocationRenderData",
    "RenderData",
    "RenderDataRequirement",
    "RenderDataRequest",
    "RenderDeviceIdentity",
    "RenderLocation",
    "RenderEventRequest",
    "RenderDeviceStatus",
    "RenderTemplateVersion",
    "SpectrumXVRF",
    "ZTPDevice",
    "configured_dcim_provider_name",
    "create_dcim_client",
    "create_nautobot_mcp_client",
    "dcim_client_session",
    "discover_dcim_providers",
    "get_dcim_provider",
    "normalize_dcim_event",
    "provider_settings",
    "supports_nautobot_mcp",
]
