# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Public facade and activity catalog for InfiniBand PKey operations."""

from nv_config_manager_workflows.activities.ib_pkey.dcim_activities import (
    CreatePartitionInNautobotInput,
    CreatePartitionInNautobotOutput,
    RecordIBPKeyInNautobotInput,
    RecordIBPKeyInNautobotOutput,
    cleanup_empty_pkey_partition,
    create_partition_in_dcim,
    create_partition_in_nautobot,
    fetch_pkey_assignments,
    record_ib_pkey_in_dcim,
    record_ib_pkey_in_nautobot,
    record_pkey_assignments,
    remove_pkey_assignments,
    resolve_guids_to_interfaces,
    resolve_ib_context,
    resolve_ib_context_for_add,
    resolve_ib_site_for_host,
    resolve_interface_guids,
    sync_pkey_assignments,
)
from nv_config_manager_workflows.activities.ib_pkey.models import (
    PKEY_MAX,
    PKEY_MIN,
    PKEY_RESERVED,
    AddGuidsInput,
    AddGuidsOutput,
    CleanupEmptyPartitionInput,
    CleanupEmptyPartitionOutput,
    CreatePartitionInDCIMInput,
    CreatePartitionInDCIMOutput,
    CreatePKeyInput,
    CreatePKeyOutput,
    CurrentAssignment,
    DCIMLocationIdentifier,
    DCIMLocationType,
    FetchPKeyAssignmentsInput,
    FetchPKeyAssignmentsOutput,
    FetchPKeyMembersInput,
    FetchPKeyMembersOutput,
    InterfaceRef,
    RecordIBPKeyInDCIMInput,
    RecordIBPKeyInDCIMOutput,
    RecordPKeyAssignmentsInput,
    RecordPKeyAssignmentsOutput,
    RemoveGuidsInput,
    RemoveGuidsOutput,
    RemovePKeyAssignmentsInput,
    RemovePKeyAssignmentsOutput,
    ResolvedInterface,
    ResolveGuidsToInterfacesInput,
    ResolveGuidsToInterfacesOutput,
    ResolveIBContextInput,
    ResolveIBContextOutput,
    ResolveIBSiteForHostInput,
    ResolveIBSiteForHostOutput,
    ResolveInterfaceGuidsInput,
    ResolveInterfaceGuidsOutput,
    SetGuidsInput,
    SetGuidsOutput,
    SyncPKeyAssignmentsInput,
    SyncPKeyAssignmentsOutput,
    ValidatePKeyInput,
    ValidatePKeyOutput,
    VerifyPKeyInput,
    VerifyPKeyMembersAbsentInput,
    VerifyPKeyMembersAbsentOutput,
    VerifyPKeyMembersInput,
    VerifyPKeyMembersOutput,
    VerifyPKeyOutput,
)
from nv_config_manager_workflows.activities.ib_pkey.normalization import (
    DEFAULT_MEMBERSHIP_TYPE,
    normalize_membership_type,
)
from nv_config_manager_workflows.activities.ib_pkey.resolution import (
    SITE_LOCATION_TYPE_NAME,
    index_resolved_interfaces,
    normalize_ib_guid,
)
from nv_config_manager_workflows.activities.ib_pkey.ufm_activities import (
    add_guids_to_pkey,
    create_pkey_on_ufm,
    fetch_pkey_members,
    remove_guids_from_pkey,
    set_pkey_members,
    validate_pkey_available,
    verify_pkey_created,
    verify_pkey_members,
    verify_pkey_members_absent,
)

# Preserve UFM ordering followed by the former DCIM ordering.
IB_PKEY_ACTIVITIES = (
    validate_pkey_available,
    create_pkey_on_ufm,
    verify_pkey_created,
    add_guids_to_pkey,
    verify_pkey_members,
    remove_guids_from_pkey,
    set_pkey_members,
    verify_pkey_members_absent,
    fetch_pkey_members,
    record_ib_pkey_in_dcim,
    record_ib_pkey_in_nautobot,
    create_partition_in_dcim,
    create_partition_in_nautobot,
    resolve_interface_guids,
    resolve_guids_to_interfaces,
    resolve_ib_context,
    resolve_ib_context_for_add,
    resolve_ib_site_for_host,
    record_pkey_assignments,
    fetch_pkey_assignments,
    sync_pkey_assignments,
    remove_pkey_assignments,
    cleanup_empty_pkey_partition,
)

__all__ = [
    "IB_PKEY_ACTIVITIES",
    "PKEY_MAX",
    "PKEY_MIN",
    "PKEY_RESERVED",
    "DCIMLocationIdentifier",
    "DCIMLocationType",
    "ValidatePKeyInput",
    "ValidatePKeyOutput",
    "CreatePKeyInput",
    "CreatePKeyOutput",
    "VerifyPKeyInput",
    "VerifyPKeyOutput",
    "AddGuidsInput",
    "AddGuidsOutput",
    "SetGuidsInput",
    "SetGuidsOutput",
    "VerifyPKeyMembersInput",
    "VerifyPKeyMembersOutput",
    "FetchPKeyMembersInput",
    "FetchPKeyMembersOutput",
    "RemoveGuidsInput",
    "RemoveGuidsOutput",
    "VerifyPKeyMembersAbsentInput",
    "VerifyPKeyMembersAbsentOutput",
    "CreatePartitionInDCIMInput",
    "CreatePartitionInDCIMOutput",
    "RecordIBPKeyInDCIMInput",
    "RecordIBPKeyInDCIMOutput",
    "InterfaceRef",
    "ResolvedInterface",
    "ResolveInterfaceGuidsInput",
    "ResolveInterfaceGuidsOutput",
    "ResolveGuidsToInterfacesInput",
    "ResolveGuidsToInterfacesOutput",
    "RecordPKeyAssignmentsInput",
    "RecordPKeyAssignmentsOutput",
    "RemovePKeyAssignmentsInput",
    "RemovePKeyAssignmentsOutput",
    "CurrentAssignment",
    "FetchPKeyAssignmentsInput",
    "FetchPKeyAssignmentsOutput",
    "SyncPKeyAssignmentsInput",
    "SyncPKeyAssignmentsOutput",
    "CleanupEmptyPartitionInput",
    "CleanupEmptyPartitionOutput",
    "ResolveIBSiteForHostInput",
    "ResolveIBSiteForHostOutput",
    "ResolveIBContextInput",
    "ResolveIBContextOutput",
    "validate_pkey_available",
    "create_pkey_on_ufm",
    "verify_pkey_created",
    "add_guids_to_pkey",
    "verify_pkey_members",
    "remove_guids_from_pkey",
    "set_pkey_members",
    "verify_pkey_members_absent",
    "fetch_pkey_members",
    "record_ib_pkey_in_dcim",
    "record_ib_pkey_in_nautobot",
    "create_partition_in_dcim",
    "create_partition_in_nautobot",
    "resolve_interface_guids",
    "resolve_guids_to_interfaces",
    "resolve_ib_context",
    "resolve_ib_context_for_add",
    "resolve_ib_site_for_host",
    "record_pkey_assignments",
    "fetch_pkey_assignments",
    "sync_pkey_assignments",
    "remove_pkey_assignments",
    "cleanup_empty_pkey_partition",
    "CreatePartitionInNautobotInput",
    "CreatePartitionInNautobotOutput",
    "RecordIBPKeyInNautobotInput",
    "RecordIBPKeyInNautobotOutput",
    "DEFAULT_MEMBERSHIP_TYPE",
    "normalize_membership_type",
    "SITE_LOCATION_TYPE_NAME",
    "index_resolved_interfaces",
    "normalize_ib_guid",
]
