/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the WorkflowDetailResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowDetailResponse{}

// WorkflowDetailResponse Workflow Detail Response.
type WorkflowDetailResponse struct {
	CloseTime   NullableTime `json:"close_time"`
	FailedStage bool         `json:"failed_stage"`
	// Calculate URL to Temporal UI Workflow View.
	Href             string                           `json:"href"`
	Id               string                           `json:"id"`
	PendingApproval  bool                             `json:"pending_approval"`
	Result           interface{}                      `json:"result"`
	SearchAttributes map[string]SearchAttributesValue `json:"search_attributes"`
	Stages           []Stage                          `json:"stages"`
	StartTime        time.Time                        `json:"start_time"`
	StartedBy        string                           `json:"started_by"`
	Status           string                           `json:"status"`
	WorkflowInput    interface{}                      `json:"workflow_input"`
	WorkflowType     string                           `json:"workflow_type"`
}

type _WorkflowDetailResponse WorkflowDetailResponse

// NewWorkflowDetailResponse instantiates a new WorkflowDetailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowDetailResponse(closeTime NullableTime, failedStage bool, href string, id string, pendingApproval bool, result interface{}, searchAttributes map[string]SearchAttributesValue, stages []Stage, startTime time.Time, startedBy string, status string, workflowInput interface{}, workflowType string) *WorkflowDetailResponse {
	this := WorkflowDetailResponse{}
	this.CloseTime = closeTime
	this.FailedStage = failedStage
	this.Href = href
	this.Id = id
	this.PendingApproval = pendingApproval
	this.Result = result
	this.SearchAttributes = searchAttributes
	this.Stages = stages
	this.StartTime = startTime
	this.StartedBy = startedBy
	this.Status = status
	this.WorkflowInput = workflowInput
	this.WorkflowType = workflowType
	return &this
}

// NewWorkflowDetailResponseWithDefaults instantiates a new WorkflowDetailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowDetailResponseWithDefaults() *WorkflowDetailResponse {
	this := WorkflowDetailResponse{}
	return &this
}

// GetCloseTime returns the CloseTime field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *WorkflowDetailResponse) GetCloseTime() time.Time {
	if o == nil || o.CloseTime.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.CloseTime.Get()
}

// GetCloseTimeOk returns a tuple with the CloseTime field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowDetailResponse) GetCloseTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CloseTime.Get(), o.CloseTime.IsSet()
}

// SetCloseTime sets field value
func (o *WorkflowDetailResponse) SetCloseTime(v time.Time) {
	o.CloseTime.Set(&v)
}

// GetFailedStage returns the FailedStage field value
func (o *WorkflowDetailResponse) GetFailedStage() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FailedStage
}

// GetFailedStageOk returns a tuple with the FailedStage field value
// and a boolean to check if the value has been set.
func (o *WorkflowDetailResponse) GetFailedStageOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailedStage, true
}

// SetFailedStage sets field value
func (o *WorkflowDetailResponse) SetFailedStage(v bool) {
	o.FailedStage = v
}

// GetHref returns the Href field value
func (o *WorkflowDetailResponse) GetHref() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Href
}

// GetHrefOk returns a tuple with the Href field value
// and a boolean to check if the value has been set.
func (o *WorkflowDetailResponse) GetHrefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Href, true
}

// SetHref sets field value
func (o *WorkflowDetailResponse) SetHref(v string) {
	o.Href = v
}

// GetId returns the Id field value
func (o *WorkflowDetailResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WorkflowDetailResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WorkflowDetailResponse) SetId(v string) {
	o.Id = v
}

// GetPendingApproval returns the PendingApproval field value
func (o *WorkflowDetailResponse) GetPendingApproval() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PendingApproval
}

// GetPendingApprovalOk returns a tuple with the PendingApproval field value
// and a boolean to check if the value has been set.
func (o *WorkflowDetailResponse) GetPendingApprovalOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PendingApproval, true
}

// SetPendingApproval sets field value
func (o *WorkflowDetailResponse) SetPendingApproval(v bool) {
	o.PendingApproval = v
}

// GetResult returns the Result field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *WorkflowDetailResponse) GetResult() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowDetailResponse) GetResultOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *WorkflowDetailResponse) SetResult(v interface{}) {
	o.Result = v
}

// GetSearchAttributes returns the SearchAttributes field value
func (o *WorkflowDetailResponse) GetSearchAttributes() map[string]SearchAttributesValue {
	if o == nil {
		var ret map[string]SearchAttributesValue
		return ret
	}

	return o.SearchAttributes
}

// GetSearchAttributesOk returns a tuple with the SearchAttributes field value
// and a boolean to check if the value has been set.
func (o *WorkflowDetailResponse) GetSearchAttributesOk() (map[string]SearchAttributesValue, bool) {
	if o == nil {
		return map[string]SearchAttributesValue{}, false
	}
	return o.SearchAttributes, true
}

// SetSearchAttributes sets field value
func (o *WorkflowDetailResponse) SetSearchAttributes(v map[string]SearchAttributesValue) {
	o.SearchAttributes = v
}

// GetStages returns the Stages field value
func (o *WorkflowDetailResponse) GetStages() []Stage {
	if o == nil {
		var ret []Stage
		return ret
	}

	return o.Stages
}

// GetStagesOk returns a tuple with the Stages field value
// and a boolean to check if the value has been set.
func (o *WorkflowDetailResponse) GetStagesOk() ([]Stage, bool) {
	if o == nil {
		return nil, false
	}
	return o.Stages, true
}

// SetStages sets field value
func (o *WorkflowDetailResponse) SetStages(v []Stage) {
	o.Stages = v
}

// GetStartTime returns the StartTime field value
func (o *WorkflowDetailResponse) GetStartTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *WorkflowDetailResponse) GetStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *WorkflowDetailResponse) SetStartTime(v time.Time) {
	o.StartTime = v
}

// GetStartedBy returns the StartedBy field value
func (o *WorkflowDetailResponse) GetStartedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartedBy
}

// GetStartedByOk returns a tuple with the StartedBy field value
// and a boolean to check if the value has been set.
func (o *WorkflowDetailResponse) GetStartedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartedBy, true
}

// SetStartedBy sets field value
func (o *WorkflowDetailResponse) SetStartedBy(v string) {
	o.StartedBy = v
}

// GetStatus returns the Status field value
func (o *WorkflowDetailResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *WorkflowDetailResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *WorkflowDetailResponse) SetStatus(v string) {
	o.Status = v
}

// GetWorkflowInput returns the WorkflowInput field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *WorkflowDetailResponse) GetWorkflowInput() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.WorkflowInput
}

// GetWorkflowInputOk returns a tuple with the WorkflowInput field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowDetailResponse) GetWorkflowInputOk() (*interface{}, bool) {
	if o == nil || IsNil(o.WorkflowInput) {
		return nil, false
	}
	return &o.WorkflowInput, true
}

// SetWorkflowInput sets field value
func (o *WorkflowDetailResponse) SetWorkflowInput(v interface{}) {
	o.WorkflowInput = v
}

// GetWorkflowType returns the WorkflowType field value
func (o *WorkflowDetailResponse) GetWorkflowType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkflowType
}

// GetWorkflowTypeOk returns a tuple with the WorkflowType field value
// and a boolean to check if the value has been set.
func (o *WorkflowDetailResponse) GetWorkflowTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkflowType, true
}

// SetWorkflowType sets field value
func (o *WorkflowDetailResponse) SetWorkflowType(v string) {
	o.WorkflowType = v
}

func (o WorkflowDetailResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowDetailResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["close_time"] = o.CloseTime.Get()
	toSerialize["failed_stage"] = o.FailedStage
	toSerialize["href"] = o.Href
	toSerialize["id"] = o.Id
	toSerialize["pending_approval"] = o.PendingApproval
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	toSerialize["search_attributes"] = o.SearchAttributes
	toSerialize["stages"] = o.Stages
	toSerialize["start_time"] = o.StartTime
	toSerialize["started_by"] = o.StartedBy
	toSerialize["status"] = o.Status
	if o.WorkflowInput != nil {
		toSerialize["workflow_input"] = o.WorkflowInput
	}
	toSerialize["workflow_type"] = o.WorkflowType
	return toSerialize, nil
}

func (o *WorkflowDetailResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"close_time":        true,
		"failed_stage":      false,
		"href":              false,
		"id":                false,
		"pending_approval":  false,
		"result":            true,
		"search_attributes": false,
		"stages":            false,
		"start_time":        false,
		"started_by":        false,
		"status":            false,
		"workflow_input":    true,
		"workflow_type":     false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowDetailResponse := _WorkflowDetailResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowDetailResponse)

	if err != nil {
		return err
	}

	*o = WorkflowDetailResponse(varWorkflowDetailResponse)

	return err
}

type NullableWorkflowDetailResponse struct {
	value *WorkflowDetailResponse
	isSet bool
}

func (v NullableWorkflowDetailResponse) Get() *WorkflowDetailResponse {
	return v.value
}

func (v *NullableWorkflowDetailResponse) Set(val *WorkflowDetailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowDetailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowDetailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowDetailResponse(val *WorkflowDetailResponse) *NullableWorkflowDetailResponse {
	return &NullableWorkflowDetailResponse{value: val, isSet: true}
}

func (v NullableWorkflowDetailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowDetailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
