/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DevicePasswordRotationInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DevicePasswordRotationInput{}

// DevicePasswordRotationInput Device Password Rotation Workflow Input Definition.
type DevicePasswordRotationInput struct {
	// Identifier of the network device to update.
	DeviceId string `json:"device_id"`
	// Name of the managed secret containing the replacement password.
	SelectedSecret string `json:"selected_secret"`
}

type _DevicePasswordRotationInput DevicePasswordRotationInput

// NewDevicePasswordRotationInput instantiates a new DevicePasswordRotationInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDevicePasswordRotationInput(deviceId string, selectedSecret string) *DevicePasswordRotationInput {
	this := DevicePasswordRotationInput{}
	this.DeviceId = deviceId
	this.SelectedSecret = selectedSecret
	return &this
}

// NewDevicePasswordRotationInputWithDefaults instantiates a new DevicePasswordRotationInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDevicePasswordRotationInputWithDefaults() *DevicePasswordRotationInput {
	this := DevicePasswordRotationInput{}
	return &this
}

// GetDeviceId returns the DeviceId field value
func (o *DevicePasswordRotationInput) GetDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *DevicePasswordRotationInput) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *DevicePasswordRotationInput) SetDeviceId(v string) {
	o.DeviceId = v
}

// GetSelectedSecret returns the SelectedSecret field value
func (o *DevicePasswordRotationInput) GetSelectedSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SelectedSecret
}

// GetSelectedSecretOk returns a tuple with the SelectedSecret field value
// and a boolean to check if the value has been set.
func (o *DevicePasswordRotationInput) GetSelectedSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SelectedSecret, true
}

// SetSelectedSecret sets field value
func (o *DevicePasswordRotationInput) SetSelectedSecret(v string) {
	o.SelectedSecret = v
}

func (o DevicePasswordRotationInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DevicePasswordRotationInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["device_id"] = o.DeviceId
	toSerialize["selected_secret"] = o.SelectedSecret
	return toSerialize, nil
}

func (o *DevicePasswordRotationInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"device_id":       false,
		"selected_secret": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDevicePasswordRotationInput := _DevicePasswordRotationInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDevicePasswordRotationInput)

	if err != nil {
		return err
	}

	*o = DevicePasswordRotationInput(varDevicePasswordRotationInput)

	return err
}

type NullableDevicePasswordRotationInput struct {
	value *DevicePasswordRotationInput
	isSet bool
}

func (v NullableDevicePasswordRotationInput) Get() *DevicePasswordRotationInput {
	return v.value
}

func (v *NullableDevicePasswordRotationInput) Set(val *DevicePasswordRotationInput) {
	v.value = val
	v.isSet = true
}

func (v NullableDevicePasswordRotationInput) IsSet() bool {
	return v.isSet
}

func (v *NullableDevicePasswordRotationInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDevicePasswordRotationInput(val *DevicePasswordRotationInput) *NullableDevicePasswordRotationInput {
	return &NullableDevicePasswordRotationInput{value: val, isSet: true}
}

func (v NullableDevicePasswordRotationInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDevicePasswordRotationInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
