/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the IBPKeyMemberUpdateInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IBPKeyMemberUpdateInput{}

// IBPKeyMemberUpdateInput InfiniBand PKey Member Update Workflow Input.  Site and Overlay are resolved server-side from “host“ and “pkey“.
type IBPKeyMemberUpdateInput struct {
	// Per-GUID membership types corresponding to the supplied GUIDs.
	GuidMemberships []string `json:"guid_memberships,omitempty"`
	// InfiniBand port GUIDs that should belong to the partition.
	Guids []string `json:"guids,omitempty"`
	// Hostname of the UFM server managing the InfiniBand fabric.
	Host string `json:"host"`
	// DCIM interfaces to resolve to InfiniBand port GUIDs.
	Interfaces []InterfaceRef `json:"interfaces,omitempty"`
	// IP over InfiniBand setting used when the partition does not already exist.
	IpOverIb *bool `json:"ip_over_ib,omitempty"`
	// Default partition membership type for updated members.
	MembershipType *string `json:"membership_type,omitempty"`
	// Partition key whose membership will be replaced.
	Pkey string `json:"pkey"`
}

type _IBPKeyMemberUpdateInput IBPKeyMemberUpdateInput

// NewIBPKeyMemberUpdateInput instantiates a new IBPKeyMemberUpdateInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIBPKeyMemberUpdateInput(host string, pkey string) *IBPKeyMemberUpdateInput {
	this := IBPKeyMemberUpdateInput{}
	this.Host = host
	var ipOverIb bool = true
	this.IpOverIb = &ipOverIb
	var membershipType string = "full"
	this.MembershipType = &membershipType
	this.Pkey = pkey
	return &this
}

// NewIBPKeyMemberUpdateInputWithDefaults instantiates a new IBPKeyMemberUpdateInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIBPKeyMemberUpdateInputWithDefaults() *IBPKeyMemberUpdateInput {
	this := IBPKeyMemberUpdateInput{}
	var ipOverIb bool = true
	this.IpOverIb = &ipOverIb
	var membershipType string = "full"
	this.MembershipType = &membershipType
	return &this
}

// GetGuidMemberships returns the GuidMemberships field value if set, zero value otherwise.
func (o *IBPKeyMemberUpdateInput) GetGuidMemberships() []string {
	if o == nil || IsNil(o.GuidMemberships) {
		var ret []string
		return ret
	}
	return o.GuidMemberships
}

// GetGuidMembershipsOk returns a tuple with the GuidMemberships field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *IBPKeyMemberUpdateInput) GetGuidMembershipsOk() ([]string, bool) {
	if o == nil || IsNil(o.GuidMemberships) {
		return nil, false
	}
	return o.GuidMemberships, true
}

// HasGuidMemberships returns a boolean if a field has been set.
func (o *IBPKeyMemberUpdateInput) HasGuidMemberships() bool {
	if o != nil && !IsNil(o.GuidMemberships) {
		return true
	}

	return false
}

// SetGuidMemberships gets a reference to the given []string and assigns it to the GuidMemberships field.
func (o *IBPKeyMemberUpdateInput) SetGuidMemberships(v []string) {
	o.GuidMemberships = v
}

// GetGuids returns the Guids field value if set, zero value otherwise.
func (o *IBPKeyMemberUpdateInput) GetGuids() []string {
	if o == nil || IsNil(o.Guids) {
		var ret []string
		return ret
	}
	return o.Guids
}

// GetGuidsOk returns a tuple with the Guids field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *IBPKeyMemberUpdateInput) GetGuidsOk() ([]string, bool) {
	if o == nil || IsNil(o.Guids) {
		return nil, false
	}
	return o.Guids, true
}

// HasGuids returns a boolean if a field has been set.
func (o *IBPKeyMemberUpdateInput) HasGuids() bool {
	if o != nil && !IsNil(o.Guids) {
		return true
	}

	return false
}

// SetGuids gets a reference to the given []string and assigns it to the Guids field.
func (o *IBPKeyMemberUpdateInput) SetGuids(v []string) {
	o.Guids = v
}

// GetHost returns the Host field value
func (o *IBPKeyMemberUpdateInput) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *IBPKeyMemberUpdateInput) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *IBPKeyMemberUpdateInput) SetHost(v string) {
	o.Host = v
}

// GetInterfaces returns the Interfaces field value if set, zero value otherwise.
func (o *IBPKeyMemberUpdateInput) GetInterfaces() []InterfaceRef {
	if o == nil || IsNil(o.Interfaces) {
		var ret []InterfaceRef
		return ret
	}
	return o.Interfaces
}

// GetInterfacesOk returns a tuple with the Interfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *IBPKeyMemberUpdateInput) GetInterfacesOk() ([]InterfaceRef, bool) {
	if o == nil || IsNil(o.Interfaces) {
		return nil, false
	}
	return o.Interfaces, true
}

// HasInterfaces returns a boolean if a field has been set.
func (o *IBPKeyMemberUpdateInput) HasInterfaces() bool {
	if o != nil && !IsNil(o.Interfaces) {
		return true
	}

	return false
}

// SetInterfaces gets a reference to the given []InterfaceRef and assigns it to the Interfaces field.
func (o *IBPKeyMemberUpdateInput) SetInterfaces(v []InterfaceRef) {
	o.Interfaces = v
}

// GetIpOverIb returns the IpOverIb field value if set, zero value otherwise.
func (o *IBPKeyMemberUpdateInput) GetIpOverIb() bool {
	if o == nil || IsNil(o.IpOverIb) {
		var ret bool
		return ret
	}
	return *o.IpOverIb
}

// GetIpOverIbOk returns a tuple with the IpOverIb field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *IBPKeyMemberUpdateInput) GetIpOverIbOk() (*bool, bool) {
	if o == nil || IsNil(o.IpOverIb) {
		return nil, false
	}
	return o.IpOverIb, true
}

// HasIpOverIb returns a boolean if a field has been set.
func (o *IBPKeyMemberUpdateInput) HasIpOverIb() bool {
	if o != nil && !IsNil(o.IpOverIb) {
		return true
	}

	return false
}

// SetIpOverIb gets a reference to the given bool and assigns it to the IpOverIb field.
func (o *IBPKeyMemberUpdateInput) SetIpOverIb(v bool) {
	o.IpOverIb = &v
}

// GetMembershipType returns the MembershipType field value if set, zero value otherwise.
func (o *IBPKeyMemberUpdateInput) GetMembershipType() string {
	if o == nil || IsNil(o.MembershipType) {
		var ret string
		return ret
	}
	return *o.MembershipType
}

// GetMembershipTypeOk returns a tuple with the MembershipType field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *IBPKeyMemberUpdateInput) GetMembershipTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MembershipType) {
		return nil, false
	}
	return o.MembershipType, true
}

// HasMembershipType returns a boolean if a field has been set.
func (o *IBPKeyMemberUpdateInput) HasMembershipType() bool {
	if o != nil && !IsNil(o.MembershipType) {
		return true
	}

	return false
}

// SetMembershipType gets a reference to the given string and assigns it to the MembershipType field.
func (o *IBPKeyMemberUpdateInput) SetMembershipType(v string) {
	o.MembershipType = &v
}

// GetPkey returns the Pkey field value
func (o *IBPKeyMemberUpdateInput) GetPkey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pkey
}

// GetPkeyOk returns a tuple with the Pkey field value
// and a boolean to check if the value has been set.
func (o *IBPKeyMemberUpdateInput) GetPkeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pkey, true
}

// SetPkey sets field value
func (o *IBPKeyMemberUpdateInput) SetPkey(v string) {
	o.Pkey = v
}

func (o IBPKeyMemberUpdateInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IBPKeyMemberUpdateInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GuidMemberships) {
		toSerialize["guid_memberships"] = o.GuidMemberships
	}
	if !IsNil(o.Guids) {
		toSerialize["guids"] = o.Guids
	}
	toSerialize["host"] = o.Host
	if !IsNil(o.Interfaces) {
		toSerialize["interfaces"] = o.Interfaces
	}
	if !IsNil(o.IpOverIb) {
		toSerialize["ip_over_ib"] = o.IpOverIb
	}
	if !IsNil(o.MembershipType) {
		toSerialize["membership_type"] = o.MembershipType
	}
	toSerialize["pkey"] = o.Pkey
	return toSerialize, nil
}

func (o *IBPKeyMemberUpdateInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"host": false,
		"pkey": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIBPKeyMemberUpdateInput := _IBPKeyMemberUpdateInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIBPKeyMemberUpdateInput)

	if err != nil {
		return err
	}

	*o = IBPKeyMemberUpdateInput(varIBPKeyMemberUpdateInput)

	return err
}

type NullableIBPKeyMemberUpdateInput struct {
	value *IBPKeyMemberUpdateInput
	isSet bool
}

func (v NullableIBPKeyMemberUpdateInput) Get() *IBPKeyMemberUpdateInput {
	return v.value
}

func (v *NullableIBPKeyMemberUpdateInput) Set(val *IBPKeyMemberUpdateInput) {
	v.value = val
	v.isSet = true
}

func (v NullableIBPKeyMemberUpdateInput) IsSet() bool {
	return v.isSet
}

func (v *NullableIBPKeyMemberUpdateInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIBPKeyMemberUpdateInput(val *IBPKeyMemberUpdateInput) *NullableIBPKeyMemberUpdateInput {
	return &NullableIBPKeyMemberUpdateInput{value: val, isSet: true}
}

func (v NullableIBPKeyMemberUpdateInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIBPKeyMemberUpdateInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
