/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InfinibandCableValidationInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InfinibandCableValidationInput{}

// InfinibandCableValidationInput IB Cable Validation Workflow Input Definition.
type InfinibandCableValidationInput struct {
	// Identifiers of the InfiniBand switches to validate.
	SwitchDeviceIds []string `json:"switch_device_ids"`
	// Identifier of the UFM device used to inspect the InfiniBand fabric.
	UfmDeviceId string `json:"ufm_device_id"`
}

type _InfinibandCableValidationInput InfinibandCableValidationInput

// NewInfinibandCableValidationInput instantiates a new InfinibandCableValidationInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInfinibandCableValidationInput(switchDeviceIds []string, ufmDeviceId string) *InfinibandCableValidationInput {
	this := InfinibandCableValidationInput{}
	this.SwitchDeviceIds = switchDeviceIds
	this.UfmDeviceId = ufmDeviceId
	return &this
}

// NewInfinibandCableValidationInputWithDefaults instantiates a new InfinibandCableValidationInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInfinibandCableValidationInputWithDefaults() *InfinibandCableValidationInput {
	this := InfinibandCableValidationInput{}
	return &this
}

// GetSwitchDeviceIds returns the SwitchDeviceIds field value
func (o *InfinibandCableValidationInput) GetSwitchDeviceIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SwitchDeviceIds
}

// GetSwitchDeviceIdsOk returns a tuple with the SwitchDeviceIds field value
// and a boolean to check if the value has been set.
func (o *InfinibandCableValidationInput) GetSwitchDeviceIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SwitchDeviceIds, true
}

// SetSwitchDeviceIds sets field value
func (o *InfinibandCableValidationInput) SetSwitchDeviceIds(v []string) {
	o.SwitchDeviceIds = v
}

// GetUfmDeviceId returns the UfmDeviceId field value
func (o *InfinibandCableValidationInput) GetUfmDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UfmDeviceId
}

// GetUfmDeviceIdOk returns a tuple with the UfmDeviceId field value
// and a boolean to check if the value has been set.
func (o *InfinibandCableValidationInput) GetUfmDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UfmDeviceId, true
}

// SetUfmDeviceId sets field value
func (o *InfinibandCableValidationInput) SetUfmDeviceId(v string) {
	o.UfmDeviceId = v
}

func (o InfinibandCableValidationInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InfinibandCableValidationInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["switch_device_ids"] = o.SwitchDeviceIds
	toSerialize["ufm_device_id"] = o.UfmDeviceId
	return toSerialize, nil
}

func (o *InfinibandCableValidationInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"switch_device_ids": false,
		"ufm_device_id":     false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInfinibandCableValidationInput := _InfinibandCableValidationInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInfinibandCableValidationInput)

	if err != nil {
		return err
	}

	*o = InfinibandCableValidationInput(varInfinibandCableValidationInput)

	return err
}

type NullableInfinibandCableValidationInput struct {
	value *InfinibandCableValidationInput
	isSet bool
}

func (v NullableInfinibandCableValidationInput) Get() *InfinibandCableValidationInput {
	return v.value
}

func (v *NullableInfinibandCableValidationInput) Set(val *InfinibandCableValidationInput) {
	v.value = val
	v.isSet = true
}

func (v NullableInfinibandCableValidationInput) IsSet() bool {
	return v.isSet
}

func (v *NullableInfinibandCableValidationInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInfinibandCableValidationInput(val *InfinibandCableValidationInput) *NullableInfinibandCableValidationInput {
	return &NullableInfinibandCableValidationInput{value: val, isSet: true}
}

func (v NullableInfinibandCableValidationInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInfinibandCableValidationInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
