/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ValidateHardwareInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidateHardwareInput{}

// ValidateHardwareInput Validate Hardware Workflow Input.
type ValidateHardwareInput struct {
	// Device type identifiers used to filter network devices.
	DeviceTypeIds []string `json:"device_type_ids,omitempty"`
	// Whether invalid hardware should fail the workflow.
	RaiseForInvalid *bool `json:"raise_for_invalid,omitempty"`
	// Device roles used to filter the selected network devices.
	Roles []string `json:"roles,omitempty"`
	// Site used to select network devices for validation.
	Site string `json:"site"`
	// DCIM model that owns the site identifier.
	SiteModel NullableString `json:"site_model,omitempty"`
	// Device statuses used to filter the selected network devices.
	Status []string `json:"status,omitempty"`
	// Tenant used to filter the selected network devices.
	Tenant NullableString `json:"tenant,omitempty"`
}

type _ValidateHardwareInput ValidateHardwareInput

// NewValidateHardwareInput instantiates a new ValidateHardwareInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidateHardwareInput(site string) *ValidateHardwareInput {
	this := ValidateHardwareInput{}
	var raiseForInvalid bool = false
	this.RaiseForInvalid = &raiseForInvalid
	this.Site = site
	return &this
}

// NewValidateHardwareInputWithDefaults instantiates a new ValidateHardwareInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidateHardwareInputWithDefaults() *ValidateHardwareInput {
	this := ValidateHardwareInput{}
	var raiseForInvalid bool = false
	this.RaiseForInvalid = &raiseForInvalid
	return &this
}

// GetDeviceTypeIds returns the DeviceTypeIds field value if set, zero value otherwise.
func (o *ValidateHardwareInput) GetDeviceTypeIds() []string {
	if o == nil || IsNil(o.DeviceTypeIds) {
		var ret []string
		return ret
	}
	return o.DeviceTypeIds
}

// GetDeviceTypeIdsOk returns a tuple with the DeviceTypeIds field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *ValidateHardwareInput) GetDeviceTypeIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.DeviceTypeIds) {
		return nil, false
	}
	return o.DeviceTypeIds, true
}

// HasDeviceTypeIds returns a boolean if a field has been set.
func (o *ValidateHardwareInput) HasDeviceTypeIds() bool {
	if o != nil && !IsNil(o.DeviceTypeIds) {
		return true
	}

	return false
}

// SetDeviceTypeIds gets a reference to the given []string and assigns it to the DeviceTypeIds field.
func (o *ValidateHardwareInput) SetDeviceTypeIds(v []string) {
	o.DeviceTypeIds = v
}

// GetRaiseForInvalid returns the RaiseForInvalid field value if set, zero value otherwise.
func (o *ValidateHardwareInput) GetRaiseForInvalid() bool {
	if o == nil || IsNil(o.RaiseForInvalid) {
		var ret bool
		return ret
	}
	return *o.RaiseForInvalid
}

// GetRaiseForInvalidOk returns a tuple with the RaiseForInvalid field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *ValidateHardwareInput) GetRaiseForInvalidOk() (*bool, bool) {
	if o == nil || IsNil(o.RaiseForInvalid) {
		return nil, false
	}
	return o.RaiseForInvalid, true
}

// HasRaiseForInvalid returns a boolean if a field has been set.
func (o *ValidateHardwareInput) HasRaiseForInvalid() bool {
	if o != nil && !IsNil(o.RaiseForInvalid) {
		return true
	}

	return false
}

// SetRaiseForInvalid gets a reference to the given bool and assigns it to the RaiseForInvalid field.
func (o *ValidateHardwareInput) SetRaiseForInvalid(v bool) {
	o.RaiseForInvalid = &v
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *ValidateHardwareInput) GetRoles() []string {
	if o == nil || IsNil(o.Roles) {
		var ret []string
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *ValidateHardwareInput) GetRolesOk() ([]string, bool) {
	if o == nil || IsNil(o.Roles) {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *ValidateHardwareInput) HasRoles() bool {
	if o != nil && !IsNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []string and assigns it to the Roles field.
func (o *ValidateHardwareInput) SetRoles(v []string) {
	o.Roles = v
}

// GetSite returns the Site field value
func (o *ValidateHardwareInput) GetSite() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Site
}

// GetSiteOk returns a tuple with the Site field value
// and a boolean to check if the value has been set.
func (o *ValidateHardwareInput) GetSiteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Site, true
}

// SetSite sets field value
func (o *ValidateHardwareInput) SetSite(v string) {
	o.Site = v
}

// GetSiteModel returns the SiteModel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ValidateHardwareInput) GetSiteModel() string {
	if o == nil || IsNil(o.SiteModel.Get()) {
		var ret string
		return ret
	}
	return *o.SiteModel.Get()
}

// GetSiteModelOk returns a tuple with the SiteModel field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *ValidateHardwareInput) GetSiteModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SiteModel.Get(), o.SiteModel.IsSet()
}

// HasSiteModel returns a boolean if a field has been set.
func (o *ValidateHardwareInput) HasSiteModel() bool {
	if o != nil && o.SiteModel.IsSet() {
		return true
	}

	return false
}

// SetSiteModel gets a reference to the given NullableString and assigns it to the SiteModel field.
func (o *ValidateHardwareInput) SetSiteModel(v string) {
	o.SiteModel.Set(&v)
}

// SetSiteModelNil sets the value for SiteModel to be an explicit nil
func (o *ValidateHardwareInput) SetSiteModelNil() {
	o.SiteModel.Set(nil)
}

// UnsetSiteModel ensures that no value is present for SiteModel, not even an explicit nil
func (o *ValidateHardwareInput) UnsetSiteModel() {
	o.SiteModel.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ValidateHardwareInput) GetStatus() []string {
	if o == nil || IsNil(o.Status) {
		var ret []string
		return ret
	}
	return o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *ValidateHardwareInput) GetStatusOk() ([]string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ValidateHardwareInput) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given []string and assigns it to the Status field.
func (o *ValidateHardwareInput) SetStatus(v []string) {
	o.Status = v
}

// GetTenant returns the Tenant field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ValidateHardwareInput) GetTenant() string {
	if o == nil || IsNil(o.Tenant.Get()) {
		var ret string
		return ret
	}
	return *o.Tenant.Get()
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *ValidateHardwareInput) GetTenantOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tenant.Get(), o.Tenant.IsSet()
}

// HasTenant returns a boolean if a field has been set.
func (o *ValidateHardwareInput) HasTenant() bool {
	if o != nil && o.Tenant.IsSet() {
		return true
	}

	return false
}

// SetTenant gets a reference to the given NullableString and assigns it to the Tenant field.
func (o *ValidateHardwareInput) SetTenant(v string) {
	o.Tenant.Set(&v)
}

// SetTenantNil sets the value for Tenant to be an explicit nil
func (o *ValidateHardwareInput) SetTenantNil() {
	o.Tenant.Set(nil)
}

// UnsetTenant ensures that no value is present for Tenant, not even an explicit nil
func (o *ValidateHardwareInput) UnsetTenant() {
	o.Tenant.Unset()
}

func (o ValidateHardwareInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidateHardwareInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeviceTypeIds) {
		toSerialize["device_type_ids"] = o.DeviceTypeIds
	}
	if !IsNil(o.RaiseForInvalid) {
		toSerialize["raise_for_invalid"] = o.RaiseForInvalid
	}
	if !IsNil(o.Roles) {
		toSerialize["roles"] = o.Roles
	}
	toSerialize["site"] = o.Site
	if o.SiteModel.IsSet() {
		toSerialize["site_model"] = o.SiteModel.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.Tenant.IsSet() {
		toSerialize["tenant"] = o.Tenant.Get()
	}
	return toSerialize, nil
}

func (o *ValidateHardwareInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"site": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidateHardwareInput := _ValidateHardwareInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValidateHardwareInput)

	if err != nil {
		return err
	}

	*o = ValidateHardwareInput(varValidateHardwareInput)

	return err
}

type NullableValidateHardwareInput struct {
	value *ValidateHardwareInput
	isSet bool
}

func (v NullableValidateHardwareInput) Get() *ValidateHardwareInput {
	return v.value
}

func (v *NullableValidateHardwareInput) Set(val *ValidateHardwareInput) {
	v.value = val
	v.isSet = true
}

func (v NullableValidateHardwareInput) IsSet() bool {
	return v.isSet
}

func (v *NullableValidateHardwareInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidateHardwareInput(val *ValidateHardwareInput) *NullableValidateHardwareInput {
	return &NullableValidateHardwareInput{value: val, isSet: true}
}

func (v NullableValidateHardwareInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidateHardwareInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
