/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the IBPKeyMemberDeleteInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IBPKeyMemberDeleteInput{}

// IBPKeyMemberDeleteInput InfiniBand PKey Member Delete Workflow Input.  Provide either “interfaces“ (resolved to GUIDs via the DCIM) or “guids“ directly, but not both. Site and Overlay are resolved server-side from “host“ and “pkey“.
type IBPKeyMemberDeleteInput struct {
	// InfiniBand port GUIDs to remove directly from the partition.
	Guids []string `json:"guids,omitempty"`
	// Hostname of the UFM server managing the InfiniBand fabric.
	Host string `json:"host"`
	// DCIM interfaces to resolve to InfiniBand port GUIDs.
	Interfaces []InterfaceRef `json:"interfaces,omitempty"`
	// Partition key whose members will be removed.
	Pkey string `json:"pkey"`
}

type _IBPKeyMemberDeleteInput IBPKeyMemberDeleteInput

// NewIBPKeyMemberDeleteInput instantiates a new IBPKeyMemberDeleteInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIBPKeyMemberDeleteInput(host string, pkey string) *IBPKeyMemberDeleteInput {
	this := IBPKeyMemberDeleteInput{}
	this.Host = host
	this.Pkey = pkey
	return &this
}

// NewIBPKeyMemberDeleteInputWithDefaults instantiates a new IBPKeyMemberDeleteInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIBPKeyMemberDeleteInputWithDefaults() *IBPKeyMemberDeleteInput {
	this := IBPKeyMemberDeleteInput{}
	return &this
}

// GetGuids returns the Guids field value if set, zero value otherwise.
func (o *IBPKeyMemberDeleteInput) GetGuids() []string {
	if o == nil || IsNil(o.Guids) {
		var ret []string
		return ret
	}
	return o.Guids
}

// GetGuidsOk returns a tuple with the Guids field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *IBPKeyMemberDeleteInput) GetGuidsOk() ([]string, bool) {
	if o == nil || IsNil(o.Guids) {
		return nil, false
	}
	return o.Guids, true
}

// HasGuids returns a boolean if a field has been set.
func (o *IBPKeyMemberDeleteInput) HasGuids() bool {
	if o != nil && !IsNil(o.Guids) {
		return true
	}

	return false
}

// SetGuids gets a reference to the given []string and assigns it to the Guids field.
func (o *IBPKeyMemberDeleteInput) SetGuids(v []string) {
	o.Guids = v
}

// GetHost returns the Host field value
func (o *IBPKeyMemberDeleteInput) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *IBPKeyMemberDeleteInput) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *IBPKeyMemberDeleteInput) SetHost(v string) {
	o.Host = v
}

// GetInterfaces returns the Interfaces field value if set, zero value otherwise.
func (o *IBPKeyMemberDeleteInput) GetInterfaces() []InterfaceRef {
	if o == nil || IsNil(o.Interfaces) {
		var ret []InterfaceRef
		return ret
	}
	return o.Interfaces
}

// GetInterfacesOk returns a tuple with the Interfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *IBPKeyMemberDeleteInput) GetInterfacesOk() ([]InterfaceRef, bool) {
	if o == nil || IsNil(o.Interfaces) {
		return nil, false
	}
	return o.Interfaces, true
}

// HasInterfaces returns a boolean if a field has been set.
func (o *IBPKeyMemberDeleteInput) HasInterfaces() bool {
	if o != nil && !IsNil(o.Interfaces) {
		return true
	}

	return false
}

// SetInterfaces gets a reference to the given []InterfaceRef and assigns it to the Interfaces field.
func (o *IBPKeyMemberDeleteInput) SetInterfaces(v []InterfaceRef) {
	o.Interfaces = v
}

// GetPkey returns the Pkey field value
func (o *IBPKeyMemberDeleteInput) GetPkey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pkey
}

// GetPkeyOk returns a tuple with the Pkey field value
// and a boolean to check if the value has been set.
func (o *IBPKeyMemberDeleteInput) GetPkeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pkey, true
}

// SetPkey sets field value
func (o *IBPKeyMemberDeleteInput) SetPkey(v string) {
	o.Pkey = v
}

func (o IBPKeyMemberDeleteInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IBPKeyMemberDeleteInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Guids) {
		toSerialize["guids"] = o.Guids
	}
	toSerialize["host"] = o.Host
	if !IsNil(o.Interfaces) {
		toSerialize["interfaces"] = o.Interfaces
	}
	toSerialize["pkey"] = o.Pkey
	return toSerialize, nil
}

func (o *IBPKeyMemberDeleteInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"host": false,
		"pkey": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIBPKeyMemberDeleteInput := _IBPKeyMemberDeleteInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIBPKeyMemberDeleteInput)

	if err != nil {
		return err
	}

	*o = IBPKeyMemberDeleteInput(varIBPKeyMemberDeleteInput)

	return err
}

type NullableIBPKeyMemberDeleteInput struct {
	value *IBPKeyMemberDeleteInput
	isSet bool
}

func (v NullableIBPKeyMemberDeleteInput) Get() *IBPKeyMemberDeleteInput {
	return v.value
}

func (v *NullableIBPKeyMemberDeleteInput) Set(val *IBPKeyMemberDeleteInput) {
	v.value = val
	v.isSet = true
}

func (v NullableIBPKeyMemberDeleteInput) IsSet() bool {
	return v.isSet
}

func (v *NullableIBPKeyMemberDeleteInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIBPKeyMemberDeleteInput(val *IBPKeyMemberDeleteInput) *NullableIBPKeyMemberDeleteInput {
	return &NullableIBPKeyMemberDeleteInput{value: val, isSet: true}
}

func (v NullableIBPKeyMemberDeleteInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIBPKeyMemberDeleteInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
