/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"encoding/json"
)

// checks if the WorkflowFormUiSchemaUiGlobalOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowFormUiSchemaUiGlobalOptions{}

// WorkflowFormUiSchemaUiGlobalOptions Rendering options applied to the whole form.
type WorkflowFormUiSchemaUiGlobalOptions struct {
	// Mutually exclusive input modes. A value in one mode disables and clears the others.
	ExclusiveGroups []WorkflowFormUiSchemaUiGlobalOptionsExclusiveGroupsInner `json:"exclusiveGroups,omitempty"`
	// Client-side comparisons between projected numeric fields.
	FieldComparisons []WorkflowFormUiSchemaUiGlobalOptionsFieldComparisonsInner `json:"fieldComparisons,omitempty"`
	// Hide descriptions inherited from the projected input schema.
	HideSchemaDescriptions *bool `json:"hideSchemaDescriptions,omitempty"`
}

// NewWorkflowFormUiSchemaUiGlobalOptions instantiates a new WorkflowFormUiSchemaUiGlobalOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowFormUiSchemaUiGlobalOptions() *WorkflowFormUiSchemaUiGlobalOptions {
	this := WorkflowFormUiSchemaUiGlobalOptions{}
	return &this
}

// NewWorkflowFormUiSchemaUiGlobalOptionsWithDefaults instantiates a new WorkflowFormUiSchemaUiGlobalOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowFormUiSchemaUiGlobalOptionsWithDefaults() *WorkflowFormUiSchemaUiGlobalOptions {
	this := WorkflowFormUiSchemaUiGlobalOptions{}
	return &this
}

// GetExclusiveGroups returns the ExclusiveGroups field value if set, zero value otherwise.
func (o *WorkflowFormUiSchemaUiGlobalOptions) GetExclusiveGroups() []WorkflowFormUiSchemaUiGlobalOptionsExclusiveGroupsInner {
	if o == nil || IsNil(o.ExclusiveGroups) {
		var ret []WorkflowFormUiSchemaUiGlobalOptionsExclusiveGroupsInner
		return ret
	}
	return o.ExclusiveGroups
}

// GetExclusiveGroupsOk returns a tuple with the ExclusiveGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *WorkflowFormUiSchemaUiGlobalOptions) GetExclusiveGroupsOk() ([]WorkflowFormUiSchemaUiGlobalOptionsExclusiveGroupsInner, bool) {
	if o == nil || IsNil(o.ExclusiveGroups) {
		return nil, false
	}
	return o.ExclusiveGroups, true
}

// HasExclusiveGroups returns a boolean if a field has been set.
func (o *WorkflowFormUiSchemaUiGlobalOptions) HasExclusiveGroups() bool {
	if o != nil && !IsNil(o.ExclusiveGroups) {
		return true
	}

	return false
}

// SetExclusiveGroups gets a reference to the given []WorkflowFormUiSchemaUiGlobalOptionsExclusiveGroupsInner and assigns it to the ExclusiveGroups field.
func (o *WorkflowFormUiSchemaUiGlobalOptions) SetExclusiveGroups(v []WorkflowFormUiSchemaUiGlobalOptionsExclusiveGroupsInner) {
	o.ExclusiveGroups = v
}

// GetFieldComparisons returns the FieldComparisons field value if set, zero value otherwise.
func (o *WorkflowFormUiSchemaUiGlobalOptions) GetFieldComparisons() []WorkflowFormUiSchemaUiGlobalOptionsFieldComparisonsInner {
	if o == nil || IsNil(o.FieldComparisons) {
		var ret []WorkflowFormUiSchemaUiGlobalOptionsFieldComparisonsInner
		return ret
	}
	return o.FieldComparisons
}

// GetFieldComparisonsOk returns a tuple with the FieldComparisons field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *WorkflowFormUiSchemaUiGlobalOptions) GetFieldComparisonsOk() ([]WorkflowFormUiSchemaUiGlobalOptionsFieldComparisonsInner, bool) {
	if o == nil || IsNil(o.FieldComparisons) {
		return nil, false
	}
	return o.FieldComparisons, true
}

// HasFieldComparisons returns a boolean if a field has been set.
func (o *WorkflowFormUiSchemaUiGlobalOptions) HasFieldComparisons() bool {
	if o != nil && !IsNil(o.FieldComparisons) {
		return true
	}

	return false
}

// SetFieldComparisons gets a reference to the given []WorkflowFormUiSchemaUiGlobalOptionsFieldComparisonsInner and assigns it to the FieldComparisons field.
func (o *WorkflowFormUiSchemaUiGlobalOptions) SetFieldComparisons(v []WorkflowFormUiSchemaUiGlobalOptionsFieldComparisonsInner) {
	o.FieldComparisons = v
}

// GetHideSchemaDescriptions returns the HideSchemaDescriptions field value if set, zero value otherwise.
func (o *WorkflowFormUiSchemaUiGlobalOptions) GetHideSchemaDescriptions() bool {
	if o == nil || IsNil(o.HideSchemaDescriptions) {
		var ret bool
		return ret
	}
	return *o.HideSchemaDescriptions
}

// GetHideSchemaDescriptionsOk returns a tuple with the HideSchemaDescriptions field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *WorkflowFormUiSchemaUiGlobalOptions) GetHideSchemaDescriptionsOk() (*bool, bool) {
	if o == nil || IsNil(o.HideSchemaDescriptions) {
		return nil, false
	}
	return o.HideSchemaDescriptions, true
}

// HasHideSchemaDescriptions returns a boolean if a field has been set.
func (o *WorkflowFormUiSchemaUiGlobalOptions) HasHideSchemaDescriptions() bool {
	if o != nil && !IsNil(o.HideSchemaDescriptions) {
		return true
	}

	return false
}

// SetHideSchemaDescriptions gets a reference to the given bool and assigns it to the HideSchemaDescriptions field.
func (o *WorkflowFormUiSchemaUiGlobalOptions) SetHideSchemaDescriptions(v bool) {
	o.HideSchemaDescriptions = &v
}

func (o WorkflowFormUiSchemaUiGlobalOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowFormUiSchemaUiGlobalOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExclusiveGroups) {
		toSerialize["exclusiveGroups"] = o.ExclusiveGroups
	}
	if !IsNil(o.FieldComparisons) {
		toSerialize["fieldComparisons"] = o.FieldComparisons
	}
	if !IsNil(o.HideSchemaDescriptions) {
		toSerialize["hideSchemaDescriptions"] = o.HideSchemaDescriptions
	}
	return toSerialize, nil
}

type NullableWorkflowFormUiSchemaUiGlobalOptions struct {
	value *WorkflowFormUiSchemaUiGlobalOptions
	isSet bool
}

func (v NullableWorkflowFormUiSchemaUiGlobalOptions) Get() *WorkflowFormUiSchemaUiGlobalOptions {
	return v.value
}

func (v *NullableWorkflowFormUiSchemaUiGlobalOptions) Set(val *WorkflowFormUiSchemaUiGlobalOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowFormUiSchemaUiGlobalOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowFormUiSchemaUiGlobalOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowFormUiSchemaUiGlobalOptions(val *WorkflowFormUiSchemaUiGlobalOptions) *NullableWorkflowFormUiSchemaUiGlobalOptions {
	return &NullableWorkflowFormUiSchemaUiGlobalOptions{value: val, isSet: true}
}

func (v NullableWorkflowFormUiSchemaUiGlobalOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowFormUiSchemaUiGlobalOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
