/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NVLinkSwitchFirmwareUpgradeInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NVLinkSwitchFirmwareUpgradeInput{}

// NVLinkSwitchFirmwareUpgradeInput NVLinkSwitch Firmware Upgrade Workflow Input Definition.
type NVLinkSwitchFirmwareUpgradeInput struct {
	// Target NVLink firmware bundle version.
	BundleVersion string `json:"bundle_version"`
	// Identifier of the NVLink switch to upgrade.
	DeviceId string `json:"device_id"`
}

type _NVLinkSwitchFirmwareUpgradeInput NVLinkSwitchFirmwareUpgradeInput

// NewNVLinkSwitchFirmwareUpgradeInput instantiates a new NVLinkSwitchFirmwareUpgradeInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNVLinkSwitchFirmwareUpgradeInput(bundleVersion string, deviceId string) *NVLinkSwitchFirmwareUpgradeInput {
	this := NVLinkSwitchFirmwareUpgradeInput{}
	this.BundleVersion = bundleVersion
	this.DeviceId = deviceId
	return &this
}

// NewNVLinkSwitchFirmwareUpgradeInputWithDefaults instantiates a new NVLinkSwitchFirmwareUpgradeInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNVLinkSwitchFirmwareUpgradeInputWithDefaults() *NVLinkSwitchFirmwareUpgradeInput {
	this := NVLinkSwitchFirmwareUpgradeInput{}
	return &this
}

// GetBundleVersion returns the BundleVersion field value
func (o *NVLinkSwitchFirmwareUpgradeInput) GetBundleVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BundleVersion
}

// GetBundleVersionOk returns a tuple with the BundleVersion field value
// and a boolean to check if the value has been set.
func (o *NVLinkSwitchFirmwareUpgradeInput) GetBundleVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BundleVersion, true
}

// SetBundleVersion sets field value
func (o *NVLinkSwitchFirmwareUpgradeInput) SetBundleVersion(v string) {
	o.BundleVersion = v
}

// GetDeviceId returns the DeviceId field value
func (o *NVLinkSwitchFirmwareUpgradeInput) GetDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *NVLinkSwitchFirmwareUpgradeInput) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *NVLinkSwitchFirmwareUpgradeInput) SetDeviceId(v string) {
	o.DeviceId = v
}

func (o NVLinkSwitchFirmwareUpgradeInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NVLinkSwitchFirmwareUpgradeInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bundle_version"] = o.BundleVersion
	toSerialize["device_id"] = o.DeviceId
	return toSerialize, nil
}

func (o *NVLinkSwitchFirmwareUpgradeInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"bundle_version": false,
		"device_id":      false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNVLinkSwitchFirmwareUpgradeInput := _NVLinkSwitchFirmwareUpgradeInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNVLinkSwitchFirmwareUpgradeInput)

	if err != nil {
		return err
	}

	*o = NVLinkSwitchFirmwareUpgradeInput(varNVLinkSwitchFirmwareUpgradeInput)

	return err
}

type NullableNVLinkSwitchFirmwareUpgradeInput struct {
	value *NVLinkSwitchFirmwareUpgradeInput
	isSet bool
}

func (v NullableNVLinkSwitchFirmwareUpgradeInput) Get() *NVLinkSwitchFirmwareUpgradeInput {
	return v.value
}

func (v *NullableNVLinkSwitchFirmwareUpgradeInput) Set(val *NVLinkSwitchFirmwareUpgradeInput) {
	v.value = val
	v.isSet = true
}

func (v NullableNVLinkSwitchFirmwareUpgradeInput) IsSet() bool {
	return v.isSet
}

func (v *NullableNVLinkSwitchFirmwareUpgradeInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNVLinkSwitchFirmwareUpgradeInput(val *NVLinkSwitchFirmwareUpgradeInput) *NullableNVLinkSwitchFirmwareUpgradeInput {
	return &NullableNVLinkSwitchFirmwareUpgradeInput{value: val, isSet: true}
}

func (v NullableNVLinkSwitchFirmwareUpgradeInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNVLinkSwitchFirmwareUpgradeInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
