/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"encoding/json"
)

// checks if the WorkflowFormUiSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowFormUiSchema{}

// WorkflowFormUiSchema The supported subset of an RJSF uiSchema: root options plus one entry per top-level schema property.
type WorkflowFormUiSchema struct {
	UiGlobalOptions *WorkflowFormUiSchemaUiGlobalOptions `json:"ui:globalOptions,omitempty"`
	// Top-level property rendering order; an optional * inserts unlisted properties.
	UiOrder               []string                                   `json:"ui:order,omitempty"`
	UiSubmitButtonOptions *WorkflowFormUiSchemaUiSubmitButtonOptions `json:"ui:submitButtonOptions,omitempty"`
	AdditionalProperties  map[string]interface{}
}

type _WorkflowFormUiSchema WorkflowFormUiSchema

// NewWorkflowFormUiSchema instantiates a new WorkflowFormUiSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowFormUiSchema() *WorkflowFormUiSchema {
	this := WorkflowFormUiSchema{}
	return &this
}

// NewWorkflowFormUiSchemaWithDefaults instantiates a new WorkflowFormUiSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowFormUiSchemaWithDefaults() *WorkflowFormUiSchema {
	this := WorkflowFormUiSchema{}
	return &this
}

// GetUiGlobalOptions returns the UiGlobalOptions field value if set, zero value otherwise.
func (o *WorkflowFormUiSchema) GetUiGlobalOptions() WorkflowFormUiSchemaUiGlobalOptions {
	if o == nil || IsNil(o.UiGlobalOptions) {
		var ret WorkflowFormUiSchemaUiGlobalOptions
		return ret
	}
	return *o.UiGlobalOptions
}

// GetUiGlobalOptionsOk returns a tuple with the UiGlobalOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *WorkflowFormUiSchema) GetUiGlobalOptionsOk() (*WorkflowFormUiSchemaUiGlobalOptions, bool) {
	if o == nil || IsNil(o.UiGlobalOptions) {
		return nil, false
	}
	return o.UiGlobalOptions, true
}

// HasUiGlobalOptions returns a boolean if a field has been set.
func (o *WorkflowFormUiSchema) HasUiGlobalOptions() bool {
	if o != nil && !IsNil(o.UiGlobalOptions) {
		return true
	}

	return false
}

// SetUiGlobalOptions gets a reference to the given WorkflowFormUiSchemaUiGlobalOptions and assigns it to the UiGlobalOptions field.
func (o *WorkflowFormUiSchema) SetUiGlobalOptions(v WorkflowFormUiSchemaUiGlobalOptions) {
	o.UiGlobalOptions = &v
}

// GetUiOrder returns the UiOrder field value if set, zero value otherwise.
func (o *WorkflowFormUiSchema) GetUiOrder() []string {
	if o == nil || IsNil(o.UiOrder) {
		var ret []string
		return ret
	}
	return o.UiOrder
}

// GetUiOrderOk returns a tuple with the UiOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *WorkflowFormUiSchema) GetUiOrderOk() ([]string, bool) {
	if o == nil || IsNil(o.UiOrder) {
		return nil, false
	}
	return o.UiOrder, true
}

// HasUiOrder returns a boolean if a field has been set.
func (o *WorkflowFormUiSchema) HasUiOrder() bool {
	if o != nil && !IsNil(o.UiOrder) {
		return true
	}

	return false
}

// SetUiOrder gets a reference to the given []string and assigns it to the UiOrder field.
func (o *WorkflowFormUiSchema) SetUiOrder(v []string) {
	o.UiOrder = v
}

// GetUiSubmitButtonOptions returns the UiSubmitButtonOptions field value if set, zero value otherwise.
func (o *WorkflowFormUiSchema) GetUiSubmitButtonOptions() WorkflowFormUiSchemaUiSubmitButtonOptions {
	if o == nil || IsNil(o.UiSubmitButtonOptions) {
		var ret WorkflowFormUiSchemaUiSubmitButtonOptions
		return ret
	}
	return *o.UiSubmitButtonOptions
}

// GetUiSubmitButtonOptionsOk returns a tuple with the UiSubmitButtonOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *WorkflowFormUiSchema) GetUiSubmitButtonOptionsOk() (*WorkflowFormUiSchemaUiSubmitButtonOptions, bool) {
	if o == nil || IsNil(o.UiSubmitButtonOptions) {
		return nil, false
	}
	return o.UiSubmitButtonOptions, true
}

// HasUiSubmitButtonOptions returns a boolean if a field has been set.
func (o *WorkflowFormUiSchema) HasUiSubmitButtonOptions() bool {
	if o != nil && !IsNil(o.UiSubmitButtonOptions) {
		return true
	}

	return false
}

// SetUiSubmitButtonOptions gets a reference to the given WorkflowFormUiSchemaUiSubmitButtonOptions and assigns it to the UiSubmitButtonOptions field.
func (o *WorkflowFormUiSchema) SetUiSubmitButtonOptions(v WorkflowFormUiSchemaUiSubmitButtonOptions) {
	o.UiSubmitButtonOptions = &v
}

func (o WorkflowFormUiSchema) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowFormUiSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UiGlobalOptions) {
		toSerialize["ui:globalOptions"] = o.UiGlobalOptions
	}
	if !IsNil(o.UiOrder) {
		toSerialize["ui:order"] = o.UiOrder
	}
	if !IsNil(o.UiSubmitButtonOptions) {
		toSerialize["ui:submitButtonOptions"] = o.UiSubmitButtonOptions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WorkflowFormUiSchema) UnmarshalJSON(data []byte) (err error) {
	varWorkflowFormUiSchema := _WorkflowFormUiSchema{}

	err = json.Unmarshal(data, &varWorkflowFormUiSchema)

	if err != nil {
		return err
	}

	*o = WorkflowFormUiSchema(varWorkflowFormUiSchema)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ui:globalOptions")
		delete(additionalProperties, "ui:order")
		delete(additionalProperties, "ui:submitButtonOptions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWorkflowFormUiSchema struct {
	value *WorkflowFormUiSchema
	isSet bool
}

func (v NullableWorkflowFormUiSchema) Get() *WorkflowFormUiSchema {
	return v.value
}

func (v *NullableWorkflowFormUiSchema) Set(val *WorkflowFormUiSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowFormUiSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowFormUiSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowFormUiSchema(val *WorkflowFormUiSchema) *NullableWorkflowFormUiSchema {
	return &NullableWorkflowFormUiSchema{value: val, isSet: true}
}

func (v NullableWorkflowFormUiSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowFormUiSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
