/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CommandEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommandEntry{}

// CommandEntry A single command in the diagnostics catalog.
type CommandEntry struct {
	Description string `json:"description"`
	Name        string `json:"name"`
}

type _CommandEntry CommandEntry

// NewCommandEntry instantiates a new CommandEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommandEntry(description string, name string) *CommandEntry {
	this := CommandEntry{}
	this.Description = description
	this.Name = name
	return &this
}

// NewCommandEntryWithDefaults instantiates a new CommandEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommandEntryWithDefaults() *CommandEntry {
	this := CommandEntry{}
	return &this
}

// GetDescription returns the Description field value
func (o *CommandEntry) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CommandEntry) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CommandEntry) SetDescription(v string) {
	o.Description = v
}

// GetName returns the Name field value
func (o *CommandEntry) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CommandEntry) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CommandEntry) SetName(v string) {
	o.Name = v
}

func (o CommandEntry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommandEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CommandEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"description": false,
		"name":        false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommandEntry := _CommandEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommandEntry)

	if err != nil {
		return err
	}

	*o = CommandEntry(varCommandEntry)

	return err
}

type NullableCommandEntry struct {
	value *CommandEntry
	isSet bool
}

func (v NullableCommandEntry) Get() *CommandEntry {
	return v.value
}

func (v *NullableCommandEntry) Set(val *CommandEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableCommandEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableCommandEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommandEntry(val *CommandEntry) *NullableCommandEntry {
	return &NullableCommandEntry{value: val, isSet: true}
}

func (v NullableCommandEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommandEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
