/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NetworkDeviceData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkDeviceData{}

// NetworkDeviceData Normalized network-device inventory and configuration intent.
type NetworkDeviceData struct {
	BackupEnabled *bool                  `json:"backup_enabled,omitempty"`
	DeployEnabled *bool                  `json:"deploy_enabled,omitempty"`
	DeviceType    string                 `json:"device_type"`
	Id            string                 `json:"id"`
	Intent        map[string]interface{} `json:"intent,omitempty"`
	Name          string                 `json:"name"`
	Platform      Platform               `json:"platform"`
	Position      NullableInt32          `json:"position,omitempty"`
	PrimaryIp4    NullableString         `json:"primary_ip4"`
	PrimaryIp6    NullableString         `json:"primary_ip6"`
	Rack          NullableString         `json:"rack,omitempty"`
	RenderEnabled *bool                  `json:"render_enabled,omitempty"`
	Role          string                 `json:"role"`
	Site          string                 `json:"site"`
	ZtpEnabled    *bool                  `json:"ztp_enabled,omitempty"`
}

type _NetworkDeviceData NetworkDeviceData

// NewNetworkDeviceData instantiates a new NetworkDeviceData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkDeviceData(deviceType string, id string, name string, platform Platform, primaryIp4 NullableString, primaryIp6 NullableString, role string, site string) *NetworkDeviceData {
	this := NetworkDeviceData{}
	var backupEnabled bool = false
	this.BackupEnabled = &backupEnabled
	var deployEnabled bool = false
	this.DeployEnabled = &deployEnabled
	this.DeviceType = deviceType
	this.Id = id
	this.Name = name
	this.Platform = platform
	this.PrimaryIp4 = primaryIp4
	this.PrimaryIp6 = primaryIp6
	var renderEnabled bool = false
	this.RenderEnabled = &renderEnabled
	this.Role = role
	this.Site = site
	var ztpEnabled bool = false
	this.ZtpEnabled = &ztpEnabled
	return &this
}

// NewNetworkDeviceDataWithDefaults instantiates a new NetworkDeviceData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkDeviceDataWithDefaults() *NetworkDeviceData {
	this := NetworkDeviceData{}
	var backupEnabled bool = false
	this.BackupEnabled = &backupEnabled
	var deployEnabled bool = false
	this.DeployEnabled = &deployEnabled
	var renderEnabled bool = false
	this.RenderEnabled = &renderEnabled
	var ztpEnabled bool = false
	this.ZtpEnabled = &ztpEnabled
	return &this
}

// GetBackupEnabled returns the BackupEnabled field value if set, zero value otherwise.
func (o *NetworkDeviceData) GetBackupEnabled() bool {
	if o == nil || IsNil(o.BackupEnabled) {
		var ret bool
		return ret
	}
	return *o.BackupEnabled
}

// GetBackupEnabledOk returns a tuple with the BackupEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *NetworkDeviceData) GetBackupEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.BackupEnabled) {
		return nil, false
	}
	return o.BackupEnabled, true
}

// HasBackupEnabled returns a boolean if a field has been set.
func (o *NetworkDeviceData) HasBackupEnabled() bool {
	if o != nil && !IsNil(o.BackupEnabled) {
		return true
	}

	return false
}

// SetBackupEnabled gets a reference to the given bool and assigns it to the BackupEnabled field.
func (o *NetworkDeviceData) SetBackupEnabled(v bool) {
	o.BackupEnabled = &v
}

// GetDeployEnabled returns the DeployEnabled field value if set, zero value otherwise.
func (o *NetworkDeviceData) GetDeployEnabled() bool {
	if o == nil || IsNil(o.DeployEnabled) {
		var ret bool
		return ret
	}
	return *o.DeployEnabled
}

// GetDeployEnabledOk returns a tuple with the DeployEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *NetworkDeviceData) GetDeployEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.DeployEnabled) {
		return nil, false
	}
	return o.DeployEnabled, true
}

// HasDeployEnabled returns a boolean if a field has been set.
func (o *NetworkDeviceData) HasDeployEnabled() bool {
	if o != nil && !IsNil(o.DeployEnabled) {
		return true
	}

	return false
}

// SetDeployEnabled gets a reference to the given bool and assigns it to the DeployEnabled field.
func (o *NetworkDeviceData) SetDeployEnabled(v bool) {
	o.DeployEnabled = &v
}

// GetDeviceType returns the DeviceType field value
func (o *NetworkDeviceData) GetDeviceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceType
}

// GetDeviceTypeOk returns a tuple with the DeviceType field value
// and a boolean to check if the value has been set.
func (o *NetworkDeviceData) GetDeviceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceType, true
}

// SetDeviceType sets field value
func (o *NetworkDeviceData) SetDeviceType(v string) {
	o.DeviceType = v
}

// GetId returns the Id field value
func (o *NetworkDeviceData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NetworkDeviceData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NetworkDeviceData) SetId(v string) {
	o.Id = v
}

// GetIntent returns the Intent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkDeviceData) GetIntent() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Intent
}

// GetIntentOk returns a tuple with the Intent field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *NetworkDeviceData) GetIntentOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Intent) {
		return nil, false
	}
	return o.Intent, true
}

// HasIntent returns a boolean if a field has been set.
func (o *NetworkDeviceData) HasIntent() bool {
	if o != nil && !IsNil(o.Intent) {
		return true
	}

	return false
}

// SetIntent gets a reference to the given map[string]interface{} and assigns it to the Intent field.
func (o *NetworkDeviceData) SetIntent(v map[string]interface{}) {
	o.Intent = v
}

// GetName returns the Name field value
func (o *NetworkDeviceData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NetworkDeviceData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NetworkDeviceData) SetName(v string) {
	o.Name = v
}

// GetPlatform returns the Platform field value
func (o *NetworkDeviceData) GetPlatform() Platform {
	if o == nil {
		var ret Platform
		return ret
	}

	return o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value
// and a boolean to check if the value has been set.
func (o *NetworkDeviceData) GetPlatformOk() (*Platform, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Platform, true
}

// SetPlatform sets field value
func (o *NetworkDeviceData) SetPlatform(v Platform) {
	o.Platform = v
}

// GetPosition returns the Position field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkDeviceData) GetPosition() int32 {
	if o == nil || IsNil(o.Position.Get()) {
		var ret int32
		return ret
	}
	return *o.Position.Get()
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *NetworkDeviceData) GetPositionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Position.Get(), o.Position.IsSet()
}

// HasPosition returns a boolean if a field has been set.
func (o *NetworkDeviceData) HasPosition() bool {
	if o != nil && o.Position.IsSet() {
		return true
	}

	return false
}

// SetPosition gets a reference to the given NullableInt32 and assigns it to the Position field.
func (o *NetworkDeviceData) SetPosition(v int32) {
	o.Position.Set(&v)
}

// SetPositionNil sets the value for Position to be an explicit nil
func (o *NetworkDeviceData) SetPositionNil() {
	o.Position.Set(nil)
}

// UnsetPosition ensures that no value is present for Position, not even an explicit nil
func (o *NetworkDeviceData) UnsetPosition() {
	o.Position.Unset()
}

// GetPrimaryIp4 returns the PrimaryIp4 field value
// If the value is explicit nil, the zero value for string will be returned
func (o *NetworkDeviceData) GetPrimaryIp4() string {
	if o == nil || o.PrimaryIp4.Get() == nil {
		var ret string
		return ret
	}

	return *o.PrimaryIp4.Get()
}

// GetPrimaryIp4Ok returns a tuple with the PrimaryIp4 field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkDeviceData) GetPrimaryIp4Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrimaryIp4.Get(), o.PrimaryIp4.IsSet()
}

// SetPrimaryIp4 sets field value
func (o *NetworkDeviceData) SetPrimaryIp4(v string) {
	o.PrimaryIp4.Set(&v)
}

// GetPrimaryIp6 returns the PrimaryIp6 field value
// If the value is explicit nil, the zero value for string will be returned
func (o *NetworkDeviceData) GetPrimaryIp6() string {
	if o == nil || o.PrimaryIp6.Get() == nil {
		var ret string
		return ret
	}

	return *o.PrimaryIp6.Get()
}

// GetPrimaryIp6Ok returns a tuple with the PrimaryIp6 field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkDeviceData) GetPrimaryIp6Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrimaryIp6.Get(), o.PrimaryIp6.IsSet()
}

// SetPrimaryIp6 sets field value
func (o *NetworkDeviceData) SetPrimaryIp6(v string) {
	o.PrimaryIp6.Set(&v)
}

// GetRack returns the Rack field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkDeviceData) GetRack() string {
	if o == nil || IsNil(o.Rack.Get()) {
		var ret string
		return ret
	}
	return *o.Rack.Get()
}

// GetRackOk returns a tuple with the Rack field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *NetworkDeviceData) GetRackOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rack.Get(), o.Rack.IsSet()
}

// HasRack returns a boolean if a field has been set.
func (o *NetworkDeviceData) HasRack() bool {
	if o != nil && o.Rack.IsSet() {
		return true
	}

	return false
}

// SetRack gets a reference to the given NullableString and assigns it to the Rack field.
func (o *NetworkDeviceData) SetRack(v string) {
	o.Rack.Set(&v)
}

// SetRackNil sets the value for Rack to be an explicit nil
func (o *NetworkDeviceData) SetRackNil() {
	o.Rack.Set(nil)
}

// UnsetRack ensures that no value is present for Rack, not even an explicit nil
func (o *NetworkDeviceData) UnsetRack() {
	o.Rack.Unset()
}

// GetRenderEnabled returns the RenderEnabled field value if set, zero value otherwise.
func (o *NetworkDeviceData) GetRenderEnabled() bool {
	if o == nil || IsNil(o.RenderEnabled) {
		var ret bool
		return ret
	}
	return *o.RenderEnabled
}

// GetRenderEnabledOk returns a tuple with the RenderEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *NetworkDeviceData) GetRenderEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.RenderEnabled) {
		return nil, false
	}
	return o.RenderEnabled, true
}

// HasRenderEnabled returns a boolean if a field has been set.
func (o *NetworkDeviceData) HasRenderEnabled() bool {
	if o != nil && !IsNil(o.RenderEnabled) {
		return true
	}

	return false
}

// SetRenderEnabled gets a reference to the given bool and assigns it to the RenderEnabled field.
func (o *NetworkDeviceData) SetRenderEnabled(v bool) {
	o.RenderEnabled = &v
}

// GetRole returns the Role field value
func (o *NetworkDeviceData) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *NetworkDeviceData) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *NetworkDeviceData) SetRole(v string) {
	o.Role = v
}

// GetSite returns the Site field value
func (o *NetworkDeviceData) GetSite() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Site
}

// GetSiteOk returns a tuple with the Site field value
// and a boolean to check if the value has been set.
func (o *NetworkDeviceData) GetSiteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Site, true
}

// SetSite sets field value
func (o *NetworkDeviceData) SetSite(v string) {
	o.Site = v
}

// GetZtpEnabled returns the ZtpEnabled field value if set, zero value otherwise.
func (o *NetworkDeviceData) GetZtpEnabled() bool {
	if o == nil || IsNil(o.ZtpEnabled) {
		var ret bool
		return ret
	}
	return *o.ZtpEnabled
}

// GetZtpEnabledOk returns a tuple with the ZtpEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *NetworkDeviceData) GetZtpEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ZtpEnabled) {
		return nil, false
	}
	return o.ZtpEnabled, true
}

// HasZtpEnabled returns a boolean if a field has been set.
func (o *NetworkDeviceData) HasZtpEnabled() bool {
	if o != nil && !IsNil(o.ZtpEnabled) {
		return true
	}

	return false
}

// SetZtpEnabled gets a reference to the given bool and assigns it to the ZtpEnabled field.
func (o *NetworkDeviceData) SetZtpEnabled(v bool) {
	o.ZtpEnabled = &v
}

func (o NetworkDeviceData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkDeviceData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BackupEnabled) {
		toSerialize["backup_enabled"] = o.BackupEnabled
	}
	if !IsNil(o.DeployEnabled) {
		toSerialize["deploy_enabled"] = o.DeployEnabled
	}
	toSerialize["device_type"] = o.DeviceType
	toSerialize["id"] = o.Id
	if o.Intent != nil {
		toSerialize["intent"] = o.Intent
	}
	toSerialize["name"] = o.Name
	toSerialize["platform"] = o.Platform
	if o.Position.IsSet() {
		toSerialize["position"] = o.Position.Get()
	}
	toSerialize["primary_ip4"] = o.PrimaryIp4.Get()
	toSerialize["primary_ip6"] = o.PrimaryIp6.Get()
	if o.Rack.IsSet() {
		toSerialize["rack"] = o.Rack.Get()
	}
	if !IsNil(o.RenderEnabled) {
		toSerialize["render_enabled"] = o.RenderEnabled
	}
	toSerialize["role"] = o.Role
	toSerialize["site"] = o.Site
	if !IsNil(o.ZtpEnabled) {
		toSerialize["ztp_enabled"] = o.ZtpEnabled
	}
	return toSerialize, nil
}

func (o *NetworkDeviceData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"device_type": false,
		"id":          false,
		"name":        false,
		"platform":    false,
		"primary_ip4": true,
		"primary_ip6": true,
		"role":        false,
		"site":        false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkDeviceData := _NetworkDeviceData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNetworkDeviceData)

	if err != nil {
		return err
	}

	*o = NetworkDeviceData(varNetworkDeviceData)

	return err
}

type NullableNetworkDeviceData struct {
	value *NetworkDeviceData
	isSet bool
}

func (v NullableNetworkDeviceData) Get() *NetworkDeviceData {
	return v.value
}

func (v *NullableNetworkDeviceData) Set(val *NetworkDeviceData) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkDeviceData) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkDeviceData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkDeviceData(val *NetworkDeviceData) *NullableNetworkDeviceData {
	return &NullableNetworkDeviceData{value: val, isSet: true}
}

func (v NullableNetworkDeviceData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkDeviceData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
