/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SpXOverlayAssignmentInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpXOverlayAssignmentInput{}

// SpXOverlayAssignmentInput SpX Overlay Assignment Workflow Input Definition.
type SpXOverlayAssignmentInput struct {
	Device Device1 `json:"device"`
	// Tag identifying the namespace used for allocation.
	NamespaceTag *string `json:"namespace_tag,omitempty"`
	// Identifier of the SpX overlay whose VRF will be assigned to the device and ports. Omit the overlay_id property or explicitly set it to null to remove the selected ports' current SpX assignment.
	OverlayId NullableString `json:"overlay_id,omitempty"`
	// Names of the device interfaces to assign to the overlay.
	PortNames []string `json:"port_names"`
	// Site containing the target network device.
	Site string `json:"site"`
}

type _SpXOverlayAssignmentInput SpXOverlayAssignmentInput

// NewSpXOverlayAssignmentInput instantiates a new SpXOverlayAssignmentInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpXOverlayAssignmentInput(device Device1, portNames []string, site string) *SpXOverlayAssignmentInput {
	this := SpXOverlayAssignmentInput{}
	this.Device = device
	var namespaceTag string = "spectrumx"
	this.NamespaceTag = &namespaceTag
	this.PortNames = portNames
	this.Site = site
	return &this
}

// NewSpXOverlayAssignmentInputWithDefaults instantiates a new SpXOverlayAssignmentInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpXOverlayAssignmentInputWithDefaults() *SpXOverlayAssignmentInput {
	this := SpXOverlayAssignmentInput{}
	var namespaceTag string = "spectrumx"
	this.NamespaceTag = &namespaceTag
	return &this
}

// GetDevice returns the Device field value
func (o *SpXOverlayAssignmentInput) GetDevice() Device1 {
	if o == nil {
		var ret Device1
		return ret
	}

	return o.Device
}

// GetDeviceOk returns a tuple with the Device field value
// and a boolean to check if the value has been set.
func (o *SpXOverlayAssignmentInput) GetDeviceOk() (*Device1, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Device, true
}

// SetDevice sets field value
func (o *SpXOverlayAssignmentInput) SetDevice(v Device1) {
	o.Device = v
}

// GetNamespaceTag returns the NamespaceTag field value if set, zero value otherwise.
func (o *SpXOverlayAssignmentInput) GetNamespaceTag() string {
	if o == nil || IsNil(o.NamespaceTag) {
		var ret string
		return ret
	}
	return *o.NamespaceTag
}

// GetNamespaceTagOk returns a tuple with the NamespaceTag field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *SpXOverlayAssignmentInput) GetNamespaceTagOk() (*string, bool) {
	if o == nil || IsNil(o.NamespaceTag) {
		return nil, false
	}
	return o.NamespaceTag, true
}

// HasNamespaceTag returns a boolean if a field has been set.
func (o *SpXOverlayAssignmentInput) HasNamespaceTag() bool {
	if o != nil && !IsNil(o.NamespaceTag) {
		return true
	}

	return false
}

// SetNamespaceTag gets a reference to the given string and assigns it to the NamespaceTag field.
func (o *SpXOverlayAssignmentInput) SetNamespaceTag(v string) {
	o.NamespaceTag = &v
}

// GetOverlayId returns the OverlayId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpXOverlayAssignmentInput) GetOverlayId() string {
	if o == nil || IsNil(o.OverlayId.Get()) {
		var ret string
		return ret
	}
	return *o.OverlayId.Get()
}

// GetOverlayIdOk returns a tuple with the OverlayId field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *SpXOverlayAssignmentInput) GetOverlayIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OverlayId.Get(), o.OverlayId.IsSet()
}

// HasOverlayId returns a boolean if a field has been set.
func (o *SpXOverlayAssignmentInput) HasOverlayId() bool {
	if o != nil && o.OverlayId.IsSet() {
		return true
	}

	return false
}

// SetOverlayId gets a reference to the given NullableString and assigns it to the OverlayId field.
func (o *SpXOverlayAssignmentInput) SetOverlayId(v string) {
	o.OverlayId.Set(&v)
}

// SetOverlayIdNil sets the value for OverlayId to be an explicit nil
func (o *SpXOverlayAssignmentInput) SetOverlayIdNil() {
	o.OverlayId.Set(nil)
}

// UnsetOverlayId ensures that no value is present for OverlayId, not even an explicit nil
func (o *SpXOverlayAssignmentInput) UnsetOverlayId() {
	o.OverlayId.Unset()
}

// GetPortNames returns the PortNames field value
func (o *SpXOverlayAssignmentInput) GetPortNames() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.PortNames
}

// GetPortNamesOk returns a tuple with the PortNames field value
// and a boolean to check if the value has been set.
func (o *SpXOverlayAssignmentInput) GetPortNamesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PortNames, true
}

// SetPortNames sets field value
func (o *SpXOverlayAssignmentInput) SetPortNames(v []string) {
	o.PortNames = v
}

// GetSite returns the Site field value
func (o *SpXOverlayAssignmentInput) GetSite() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Site
}

// GetSiteOk returns a tuple with the Site field value
// and a boolean to check if the value has been set.
func (o *SpXOverlayAssignmentInput) GetSiteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Site, true
}

// SetSite sets field value
func (o *SpXOverlayAssignmentInput) SetSite(v string) {
	o.Site = v
}

func (o SpXOverlayAssignmentInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpXOverlayAssignmentInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["device"] = o.Device
	if !IsNil(o.NamespaceTag) {
		toSerialize["namespace_tag"] = o.NamespaceTag
	}
	if o.OverlayId.IsSet() {
		toSerialize["overlay_id"] = o.OverlayId.Get()
	}
	toSerialize["port_names"] = o.PortNames
	toSerialize["site"] = o.Site
	return toSerialize, nil
}

func (o *SpXOverlayAssignmentInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"device":     false,
		"port_names": false,
		"site":       false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpXOverlayAssignmentInput := _SpXOverlayAssignmentInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSpXOverlayAssignmentInput)

	if err != nil {
		return err
	}

	*o = SpXOverlayAssignmentInput(varSpXOverlayAssignmentInput)

	return err
}

type NullableSpXOverlayAssignmentInput struct {
	value *SpXOverlayAssignmentInput
	isSet bool
}

func (v NullableSpXOverlayAssignmentInput) Get() *SpXOverlayAssignmentInput {
	return v.value
}

func (v *NullableSpXOverlayAssignmentInput) Set(val *SpXOverlayAssignmentInput) {
	v.value = val
	v.isSet = true
}

func (v NullableSpXOverlayAssignmentInput) IsSet() bool {
	return v.isSet
}

func (v *NullableSpXOverlayAssignmentInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpXOverlayAssignmentInput(val *SpXOverlayAssignmentInput) *NullableSpXOverlayAssignmentInput {
	return &NullableSpXOverlayAssignmentInput{value: val, isSet: true}
}

func (v NullableSpXOverlayAssignmentInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpXOverlayAssignmentInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
