/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WhoamiResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WhoamiResponse{}

// WhoamiResponse Response shape for “GET /whoami“.
type WhoamiResponse struct {
	Roles []string `json:"roles"`
	User  string   `json:"user"`
}

type _WhoamiResponse WhoamiResponse

// NewWhoamiResponse instantiates a new WhoamiResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhoamiResponse(roles []string, user string) *WhoamiResponse {
	this := WhoamiResponse{}
	this.Roles = roles
	this.User = user
	return &this
}

// NewWhoamiResponseWithDefaults instantiates a new WhoamiResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhoamiResponseWithDefaults() *WhoamiResponse {
	this := WhoamiResponse{}
	return &this
}

// GetRoles returns the Roles field value
func (o *WhoamiResponse) GetRoles() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value
// and a boolean to check if the value has been set.
func (o *WhoamiResponse) GetRolesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Roles, true
}

// SetRoles sets field value
func (o *WhoamiResponse) SetRoles(v []string) {
	o.Roles = v
}

// GetUser returns the User field value
func (o *WhoamiResponse) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *WhoamiResponse) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *WhoamiResponse) SetUser(v string) {
	o.User = v
}

func (o WhoamiResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WhoamiResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["roles"] = o.Roles
	toSerialize["user"] = o.User
	return toSerialize, nil
}

func (o *WhoamiResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"roles": false,
		"user":  false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWhoamiResponse := _WhoamiResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWhoamiResponse)

	if err != nil {
		return err
	}

	*o = WhoamiResponse(varWhoamiResponse)

	return err
}

type NullableWhoamiResponse struct {
	value *WhoamiResponse
	isSet bool
}

func (v NullableWhoamiResponse) Get() *WhoamiResponse {
	return v.value
}

func (v *NullableWhoamiResponse) Set(val *WhoamiResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWhoamiResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWhoamiResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhoamiResponse(val *WhoamiResponse) *NullableWhoamiResponse {
	return &NullableWhoamiResponse{value: val, isSet: true}
}

func (v NullableWhoamiResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhoamiResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
