/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ConfigDiffInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigDiffInput{}

// ConfigDiffInput Config Diff Workflow input.
type ConfigDiffInput struct {
	// Preloaded network device data, if available.
	Device NullableNetworkDeviceData `json:"device,omitempty"`
	// Identifier of the network device to compare.
	DeviceId string `json:"device_id"`
}

type _ConfigDiffInput ConfigDiffInput

// NewConfigDiffInput instantiates a new ConfigDiffInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigDiffInput(deviceId string) *ConfigDiffInput {
	this := ConfigDiffInput{}
	this.DeviceId = deviceId
	return &this
}

// NewConfigDiffInputWithDefaults instantiates a new ConfigDiffInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigDiffInputWithDefaults() *ConfigDiffInput {
	this := ConfigDiffInput{}
	return &this
}

// GetDevice returns the Device field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConfigDiffInput) GetDevice() NetworkDeviceData {
	if o == nil || IsNil(o.Device.Get()) {
		var ret NetworkDeviceData
		return ret
	}
	return *o.Device.Get()
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *ConfigDiffInput) GetDeviceOk() (*NetworkDeviceData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Device.Get(), o.Device.IsSet()
}

// HasDevice returns a boolean if a field has been set.
func (o *ConfigDiffInput) HasDevice() bool {
	if o != nil && o.Device.IsSet() {
		return true
	}

	return false
}

// SetDevice gets a reference to the given NullableNetworkDeviceData and assigns it to the Device field.
func (o *ConfigDiffInput) SetDevice(v NetworkDeviceData) {
	o.Device.Set(&v)
}

// SetDeviceNil sets the value for Device to be an explicit nil
func (o *ConfigDiffInput) SetDeviceNil() {
	o.Device.Set(nil)
}

// UnsetDevice ensures that no value is present for Device, not even an explicit nil
func (o *ConfigDiffInput) UnsetDevice() {
	o.Device.Unset()
}

// GetDeviceId returns the DeviceId field value
func (o *ConfigDiffInput) GetDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *ConfigDiffInput) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *ConfigDiffInput) SetDeviceId(v string) {
	o.DeviceId = v
}

func (o ConfigDiffInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigDiffInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Device.IsSet() {
		toSerialize["device"] = o.Device.Get()
	}
	toSerialize["device_id"] = o.DeviceId
	return toSerialize, nil
}

func (o *ConfigDiffInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"device_id": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigDiffInput := _ConfigDiffInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigDiffInput)

	if err != nil {
		return err
	}

	*o = ConfigDiffInput(varConfigDiffInput)

	return err
}

type NullableConfigDiffInput struct {
	value *ConfigDiffInput
	isSet bool
}

func (v NullableConfigDiffInput) Get() *ConfigDiffInput {
	return v.value
}

func (v *NullableConfigDiffInput) Set(val *ConfigDiffInput) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigDiffInput) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigDiffInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigDiffInput(val *ConfigDiffInput) *NullableConfigDiffInput {
	return &NullableConfigDiffInput{value: val, isSet: true}
}

func (v NullableConfigDiffInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigDiffInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
