/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HelloWorldInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelloWorldInput{}

// HelloWorldInput Hello World Input Definition.
type HelloWorldInput struct {
	// Name to include in the workflow greeting.
	Name string `json:"name"`
}

type _HelloWorldInput HelloWorldInput

// NewHelloWorldInput instantiates a new HelloWorldInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelloWorldInput(name string) *HelloWorldInput {
	this := HelloWorldInput{}
	this.Name = name
	return &this
}

// NewHelloWorldInputWithDefaults instantiates a new HelloWorldInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelloWorldInputWithDefaults() *HelloWorldInput {
	this := HelloWorldInput{}
	return &this
}

// GetName returns the Name field value
func (o *HelloWorldInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HelloWorldInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HelloWorldInput) SetName(v string) {
	o.Name = v
}

func (o HelloWorldInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelloWorldInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *HelloWorldInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"name": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelloWorldInput := _HelloWorldInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHelloWorldInput)

	if err != nil {
		return err
	}

	*o = HelloWorldInput(varHelloWorldInput)

	return err
}

type NullableHelloWorldInput struct {
	value *HelloWorldInput
	isSet bool
}

func (v NullableHelloWorldInput) Get() *HelloWorldInput {
	return v.value
}

func (v *NullableHelloWorldInput) Set(val *HelloWorldInput) {
	v.value = val
	v.isSet = true
}

func (v NullableHelloWorldInput) IsSet() bool {
	return v.isSet
}

func (v *NullableHelloWorldInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelloWorldInput(val *HelloWorldInput) *NullableHelloWorldInput {
	return &NullableHelloWorldInput{value: val, isSet: true}
}

func (v NullableHelloWorldInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelloWorldInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
