/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WorkflowFormUnavailableDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowFormUnavailableDetail{}

// WorkflowFormUnavailableDetail Sanitized diagnostic for an unavailable third-party workflow form.
type WorkflowFormUnavailableDetail struct {
	Code     string `json:"code"`
	Message  string `json:"message"`
	Plugin   string `json:"plugin"`
	Workflow string `json:"workflow"`
}

type _WorkflowFormUnavailableDetail WorkflowFormUnavailableDetail

// NewWorkflowFormUnavailableDetail instantiates a new WorkflowFormUnavailableDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowFormUnavailableDetail(code string, message string, plugin string, workflow string) *WorkflowFormUnavailableDetail {
	this := WorkflowFormUnavailableDetail{}
	this.Code = code
	this.Message = message
	this.Plugin = plugin
	this.Workflow = workflow
	return &this
}

// NewWorkflowFormUnavailableDetailWithDefaults instantiates a new WorkflowFormUnavailableDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowFormUnavailableDetailWithDefaults() *WorkflowFormUnavailableDetail {
	this := WorkflowFormUnavailableDetail{}
	return &this
}

// GetCode returns the Code field value
func (o *WorkflowFormUnavailableDetail) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *WorkflowFormUnavailableDetail) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *WorkflowFormUnavailableDetail) SetCode(v string) {
	o.Code = v
}

// GetMessage returns the Message field value
func (o *WorkflowFormUnavailableDetail) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *WorkflowFormUnavailableDetail) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *WorkflowFormUnavailableDetail) SetMessage(v string) {
	o.Message = v
}

// GetPlugin returns the Plugin field value
func (o *WorkflowFormUnavailableDetail) GetPlugin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Plugin
}

// GetPluginOk returns a tuple with the Plugin field value
// and a boolean to check if the value has been set.
func (o *WorkflowFormUnavailableDetail) GetPluginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plugin, true
}

// SetPlugin sets field value
func (o *WorkflowFormUnavailableDetail) SetPlugin(v string) {
	o.Plugin = v
}

// GetWorkflow returns the Workflow field value
func (o *WorkflowFormUnavailableDetail) GetWorkflow() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Workflow
}

// GetWorkflowOk returns a tuple with the Workflow field value
// and a boolean to check if the value has been set.
func (o *WorkflowFormUnavailableDetail) GetWorkflowOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Workflow, true
}

// SetWorkflow sets field value
func (o *WorkflowFormUnavailableDetail) SetWorkflow(v string) {
	o.Workflow = v
}

func (o WorkflowFormUnavailableDetail) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowFormUnavailableDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["message"] = o.Message
	toSerialize["plugin"] = o.Plugin
	toSerialize["workflow"] = o.Workflow
	return toSerialize, nil
}

func (o *WorkflowFormUnavailableDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"code":     false,
		"message":  false,
		"plugin":   false,
		"workflow": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowFormUnavailableDetail := _WorkflowFormUnavailableDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowFormUnavailableDetail)

	if err != nil {
		return err
	}

	*o = WorkflowFormUnavailableDetail(varWorkflowFormUnavailableDetail)

	return err
}

type NullableWorkflowFormUnavailableDetail struct {
	value *WorkflowFormUnavailableDetail
	isSet bool
}

func (v NullableWorkflowFormUnavailableDetail) Get() *WorkflowFormUnavailableDetail {
	return v.value
}

func (v *NullableWorkflowFormUnavailableDetail) Set(val *WorkflowFormUnavailableDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowFormUnavailableDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowFormUnavailableDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowFormUnavailableDetail(val *WorkflowFormUnavailableDetail) *NullableWorkflowFormUnavailableDetail {
	return &NullableWorkflowFormUnavailableDetail{value: val, isSet: true}
}

func (v NullableWorkflowFormUnavailableDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowFormUnavailableDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
