/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SwitchOSUpgradeInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SwitchOSUpgradeInput{}

// SwitchOSUpgradeInput Firmware Upgrade Workflow Input Definition.
type SwitchOSUpgradeInput struct {
	// Identifier of the network switch to upgrade.
	DeviceId string `json:"device_id"`
}

type _SwitchOSUpgradeInput SwitchOSUpgradeInput

// NewSwitchOSUpgradeInput instantiates a new SwitchOSUpgradeInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSwitchOSUpgradeInput(deviceId string) *SwitchOSUpgradeInput {
	this := SwitchOSUpgradeInput{}
	this.DeviceId = deviceId
	return &this
}

// NewSwitchOSUpgradeInputWithDefaults instantiates a new SwitchOSUpgradeInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSwitchOSUpgradeInputWithDefaults() *SwitchOSUpgradeInput {
	this := SwitchOSUpgradeInput{}
	return &this
}

// GetDeviceId returns the DeviceId field value
func (o *SwitchOSUpgradeInput) GetDeviceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *SwitchOSUpgradeInput) GetDeviceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *SwitchOSUpgradeInput) SetDeviceId(v string) {
	o.DeviceId = v
}

func (o SwitchOSUpgradeInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SwitchOSUpgradeInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["device_id"] = o.DeviceId
	return toSerialize, nil
}

func (o *SwitchOSUpgradeInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"device_id": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSwitchOSUpgradeInput := _SwitchOSUpgradeInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSwitchOSUpgradeInput)

	if err != nil {
		return err
	}

	*o = SwitchOSUpgradeInput(varSwitchOSUpgradeInput)

	return err
}

type NullableSwitchOSUpgradeInput struct {
	value *SwitchOSUpgradeInput
	isSet bool
}

func (v NullableSwitchOSUpgradeInput) Get() *SwitchOSUpgradeInput {
	return v.value
}

func (v *NullableSwitchOSUpgradeInput) Set(val *SwitchOSUpgradeInput) {
	v.value = val
	v.isSet = true
}

func (v NullableSwitchOSUpgradeInput) IsSet() bool {
	return v.isSet
}

func (v *NullableSwitchOSUpgradeInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSwitchOSUpgradeInput(val *SwitchOSUpgradeInput) *NullableSwitchOSUpgradeInput {
	return &NullableSwitchOSUpgradeInput{value: val, isSet: true}
}

func (v NullableSwitchOSUpgradeInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSwitchOSUpgradeInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
