/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WorkflowListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowListResponse{}

// WorkflowListResponse Workflow List Response Model.
type WorkflowListResponse struct {
	NextPageToken NullableString            `json:"next_page_token"`
	PageCount     int32                     `json:"page_count"`
	TotalCount    int32                     `json:"total_count"`
	Workflows     []WorkflowSummaryResponse `json:"workflows"`
}

type _WorkflowListResponse WorkflowListResponse

// NewWorkflowListResponse instantiates a new WorkflowListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowListResponse(nextPageToken NullableString, pageCount int32, totalCount int32, workflows []WorkflowSummaryResponse) *WorkflowListResponse {
	this := WorkflowListResponse{}
	this.NextPageToken = nextPageToken
	this.PageCount = pageCount
	this.TotalCount = totalCount
	this.Workflows = workflows
	return &this
}

// NewWorkflowListResponseWithDefaults instantiates a new WorkflowListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowListResponseWithDefaults() *WorkflowListResponse {
	this := WorkflowListResponse{}
	return &this
}

// GetNextPageToken returns the NextPageToken field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WorkflowListResponse) GetNextPageToken() string {
	if o == nil || o.NextPageToken.Get() == nil {
		var ret string
		return ret
	}

	return *o.NextPageToken.Get()
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowListResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextPageToken.Get(), o.NextPageToken.IsSet()
}

// SetNextPageToken sets field value
func (o *WorkflowListResponse) SetNextPageToken(v string) {
	o.NextPageToken.Set(&v)
}

// GetPageCount returns the PageCount field value
func (o *WorkflowListResponse) GetPageCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageCount
}

// GetPageCountOk returns a tuple with the PageCount field value
// and a boolean to check if the value has been set.
func (o *WorkflowListResponse) GetPageCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageCount, true
}

// SetPageCount sets field value
func (o *WorkflowListResponse) SetPageCount(v int32) {
	o.PageCount = v
}

// GetTotalCount returns the TotalCount field value
func (o *WorkflowListResponse) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *WorkflowListResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *WorkflowListResponse) SetTotalCount(v int32) {
	o.TotalCount = v
}

// GetWorkflows returns the Workflows field value
func (o *WorkflowListResponse) GetWorkflows() []WorkflowSummaryResponse {
	if o == nil {
		var ret []WorkflowSummaryResponse
		return ret
	}

	return o.Workflows
}

// GetWorkflowsOk returns a tuple with the Workflows field value
// and a boolean to check if the value has been set.
func (o *WorkflowListResponse) GetWorkflowsOk() ([]WorkflowSummaryResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Workflows, true
}

// SetWorkflows sets field value
func (o *WorkflowListResponse) SetWorkflows(v []WorkflowSummaryResponse) {
	o.Workflows = v
}

func (o WorkflowListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["next_page_token"] = o.NextPageToken.Get()
	toSerialize["page_count"] = o.PageCount
	toSerialize["total_count"] = o.TotalCount
	toSerialize["workflows"] = o.Workflows
	return toSerialize, nil
}

func (o *WorkflowListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"next_page_token": true,
		"page_count":      false,
		"total_count":     false,
		"workflows":       false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkflowListResponse := _WorkflowListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkflowListResponse)

	if err != nil {
		return err
	}

	*o = WorkflowListResponse(varWorkflowListResponse)

	return err
}

type NullableWorkflowListResponse struct {
	value *WorkflowListResponse
	isSet bool
}

func (v NullableWorkflowListResponse) Get() *WorkflowListResponse {
	return v.value
}

func (v *NullableWorkflowListResponse) Set(val *WorkflowListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowListResponse(val *WorkflowListResponse) *NullableWorkflowListResponse {
	return &NullableWorkflowListResponse{value: val, isSet: true}
}

func (v NullableWorkflowListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
