/*
Temporal Workflow API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package temporal

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Overlay type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Overlay{}

// Overlay Overlay data for dropdown population.
type Overlay struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type _Overlay Overlay

// NewOverlay instantiates a new Overlay object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOverlay(id string, name string) *Overlay {
	this := Overlay{}
	this.Id = id
	this.Name = name
	return &this
}

// NewOverlayWithDefaults instantiates a new Overlay object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOverlayWithDefaults() *Overlay {
	this := Overlay{}
	return &this
}

// GetId returns the Id field value
func (o *Overlay) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Overlay) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Overlay) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Overlay) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Overlay) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Overlay) SetName(v string) {
	o.Name = v
}

func (o Overlay) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Overlay) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *Overlay) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"id":   false,
		"name": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOverlay := _Overlay{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOverlay)

	if err != nil {
		return err
	}

	*o = Overlay(varOverlay)

	return err
}

type NullableOverlay struct {
	value *Overlay
	isSet bool
}

func (v NullableOverlay) Get() *Overlay {
	return v.value
}

func (v *NullableOverlay) Set(val *Overlay) {
	v.value = val
	v.isSet = true
}

func (v NullableOverlay) IsSet() bool {
	return v.isSet
}

func (v *NullableOverlay) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOverlay(val *Overlay) *NullableOverlay {
	return &NullableOverlay{value: val, isSet: true}
}

func (v NullableOverlay) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOverlay) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
