topology_path: ''
mock_blueprint: air_trial
deployment_name: demo
simulation_name: nv-config-manager-air-trial-demo
oob_server_name: oob-mgmt-server
server_mode: use-existing
attach_switch: ''
attach_interface: ''
auto_configure: true
git_token: ''
config_manager_repo: https://github.com/dsx-ai-factory/nv-config-manager
size: small
config_manager_ref: main
cumulus_version: ''
deploy: true
run_mock_topology_job: true
mock_topology_path: development/mock_topology
template_plugin_paths:
- development/air_sim/template_plugins/superpod-template-plugin
extra_job_paths: []
extra_run_after_deploy: []
use_internal: false
org_id: ''
ngc_api_key: ''
wait_timeout: 1800
deploy_timeout: 3600
no_aggressive_dhcp: false
no_reset_before_dhcp: false
