fragment ip_data on IPAddressType {
  host
  mask_length
  address
  ip_version
}

query ($id: ID!, $id_str: String) {
  overlay_assignments(assigned_object_id: $id_str) {
    assigned_object_id
    assigned_object_type {
      app_label
      model
    }
    overlay {
      id
      name
      assignments {
        assigned_object_id
        assigned_object_type {
          app_label
          model
        }
        import_targets { name }
        export_targets { name }
      }
    }
  }
  vxlans {
    id
    name
    vnid
    vni_type
    l3_vlan_id
    overlay {
      id
      name
    }
    vlan {
      id
      vid
      name
    }
    vrf {
      id
      name
      rd
    }
    import_targets {
      name
    }
    export_targets {
      name
    }
  }
  device(id: $id) {
    id
    vrfs {
      id
      name
      rd
      _custom_field_data
      import_targets {
        name
      }
      export_targets {
        name
      }
    }
    name
    tags {
      name
    }
    tenant {
      name
    }
    role {
      name
    }
    device_type {
      manufacturer {
        name
      }
      model
    }
    platform {
      name
    }
    serial
    config_context
    nvlink_domain {
      topology
    }
    location {
      name
      location_type {
        name
      }
      parent {
        name
        location_type {
          name
        }
      }
    }
    bgp_routing_instances {
      status {
        name
      }
      autonomous_system {
        asn
      }
      router_id {
        id
        interfaces {
          name
          vrf {
            name
          }
        }
      }
      endpoints {
        source_interface {
          vrf {
            name
          }
        }
        peer_group {
          name
          extra_attributes
          peergroup_template {
            extra_attributes
          }
        }
        peer {
          description
          source_ip {
            address
            ip_version
          }
          source_interface {
            name
            ip_addresses{
              address
              ip_version
            }
          }
          routing_instance {
              device {
                name
                role {
                  name
                }
            }
            status {
              name
            }
            autonomous_system {
              asn
            }
          }
        }
      }
    }
    interfaces {
      role {
        name
      }
      type
      mtu
      mac_address
      enabled
      tags {
        name
      }
      name
      description
      vrf {
        id
        name
        rd
        export_targets {
          name
        }
        import_targets {
          name
        }
      }
      mgmt_only
      member_interfaces {
        name
      }
      parent_interface {
        name
      }
      untagged_vlan {
        id
        vid
        name
      }
      tagged_vlans {
        id
        vid
        name
      }
      ip_addresses {
        ...ip_data
        role {
          name
        }
        parent {
          prefix
          parent {
            prefix
            parent {
              prefix
            }
          }
        }
      }
      connected_interface {
        vrf {
          name
        }
        ip_addresses {
          ...ip_data
        }
        device {
          name
          config_context
          tenant {
            name
          }
          role {
            name
          }
          tags {
            name
          }
          bgp_routing_instances {
            autonomous_system {
              asn
            }
            router_id {
              interfaces {
                vrf {
                  name
                }
              }
            }
          }
        }
        module {
          parent_module_bay {
            parent_device {
              id
              name
              config_context
              tenant {
                name
              }
              role {
                name
              }
              tags {
                name
              }
              bgp_routing_instances {
                autonomous_system {
                  asn
                }
                router_id {
                  interfaces {
                    vrf {
                      name
                    }
                  }
                }
              }
            }
          }
        }
        name
      }
    }
    console_server_ports {
      name
      connected_console_port {
        device {
          name
          device_type {
            manufacturer {
              name
            }
          }
        }
        name
      }
    }
  }
}
