/*
ZTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ztp

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// DeviceAPIService DeviceAPI service
type DeviceAPIService service

type ApiLoadBootscriptV1DeviceDeviceUuidBootScriptGetRequest struct {
	ctx        context.Context
	ApiService *DeviceAPIService
	deviceUuid string
}

func (r ApiLoadBootscriptV1DeviceDeviceUuidBootScriptGetRequest) Execute() (string, *http.Response, error) {
	return r.ApiService.LoadBootscriptV1DeviceDeviceUuidBootScriptGetExecute(r)
}

/*
LoadBootscriptV1DeviceDeviceUuidBootScriptGet Load Bootscript

Load the bootscript for the given DCIM device ID.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param deviceUuid
	@return ApiLoadBootscriptV1DeviceDeviceUuidBootScriptGetRequest
*/
func (a *DeviceAPIService) LoadBootscriptV1DeviceDeviceUuidBootScriptGet(ctx context.Context, deviceUuid string) ApiLoadBootscriptV1DeviceDeviceUuidBootScriptGetRequest {
	return ApiLoadBootscriptV1DeviceDeviceUuidBootScriptGetRequest{
		ApiService: a,
		ctx:        ctx,
		deviceUuid: deviceUuid,
	}
}

// Execute executes the request
//
//	@return string
func (a *DeviceAPIService) LoadBootscriptV1DeviceDeviceUuidBootScriptGetExecute(r ApiLoadBootscriptV1DeviceDeviceUuidBootScriptGetRequest) (string, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DeviceAPIService.LoadBootscriptV1DeviceDeviceUuidBootScriptGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/device/{device_uuid}/boot-script"
	localVarPath = strings.Replace(localVarPath, "{"+"device_uuid"+"}", url.PathEscape(parameterValueToString(r.deviceUuid, "deviceUuid")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiLoadCertificateV1DeviceDeviceUuidCertificatesCertificateIdGetRequest struct {
	ctx           context.Context
	ApiService    *DeviceAPIService
	deviceUuid    string
	certificateId string
}

func (r ApiLoadCertificateV1DeviceDeviceUuidCertificatesCertificateIdGetRequest) Execute() (*http.Response, error) {
	return r.ApiService.LoadCertificateV1DeviceDeviceUuidCertificatesCertificateIdGetExecute(r)
}

/*
LoadCertificateV1DeviceDeviceUuidCertificatesCertificateIdGet Load Certificate

Issue or load one certificate explicitly assigned to the requesting device.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param deviceUuid
	@param certificateId
	@return ApiLoadCertificateV1DeviceDeviceUuidCertificatesCertificateIdGetRequest
*/
func (a *DeviceAPIService) LoadCertificateV1DeviceDeviceUuidCertificatesCertificateIdGet(ctx context.Context, deviceUuid string, certificateId string) ApiLoadCertificateV1DeviceDeviceUuidCertificatesCertificateIdGetRequest {
	return ApiLoadCertificateV1DeviceDeviceUuidCertificatesCertificateIdGetRequest{
		ApiService:    a,
		ctx:           ctx,
		deviceUuid:    deviceUuid,
		certificateId: certificateId,
	}
}

// Execute executes the request
func (a *DeviceAPIService) LoadCertificateV1DeviceDeviceUuidCertificatesCertificateIdGetExecute(r ApiLoadCertificateV1DeviceDeviceUuidCertificatesCertificateIdGetRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodGet
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DeviceAPIService.LoadCertificateV1DeviceDeviceUuidCertificatesCertificateIdGet")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/device/{device_uuid}/certificates/{certificate_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"device_uuid"+"}", url.PathEscape(parameterValueToString(r.deviceUuid, "deviceUuid")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"certificate_id"+"}", url.PathEscape(parameterValueToString(r.certificateId, "certificateId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiLoadConfigurationV1DeviceDeviceUuidConfigConfigletGetRequest struct {
	ctx        context.Context
	ApiService *DeviceAPIService
	deviceUuid string
	configlet  string
}

func (r ApiLoadConfigurationV1DeviceDeviceUuidConfigConfigletGetRequest) Execute() (string, *http.Response, error) {
	return r.ApiService.LoadConfigurationV1DeviceDeviceUuidConfigConfigletGetExecute(r)
}

/*
LoadConfigurationV1DeviceDeviceUuidConfigConfigletGet Load Configuration

Load the specified configuration file for the given DCIM device ID.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param deviceUuid
	@param configlet
	@return ApiLoadConfigurationV1DeviceDeviceUuidConfigConfigletGetRequest
*/
func (a *DeviceAPIService) LoadConfigurationV1DeviceDeviceUuidConfigConfigletGet(ctx context.Context, deviceUuid string, configlet string) ApiLoadConfigurationV1DeviceDeviceUuidConfigConfigletGetRequest {
	return ApiLoadConfigurationV1DeviceDeviceUuidConfigConfigletGetRequest{
		ApiService: a,
		ctx:        ctx,
		deviceUuid: deviceUuid,
		configlet:  configlet,
	}
}

// Execute executes the request
//
//	@return string
func (a *DeviceAPIService) LoadConfigurationV1DeviceDeviceUuidConfigConfigletGetExecute(r ApiLoadConfigurationV1DeviceDeviceUuidConfigConfigletGetRequest) (string, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DeviceAPIService.LoadConfigurationV1DeviceDeviceUuidConfigConfigletGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/device/{device_uuid}/config/{configlet}"
	localVarPath = strings.Replace(localVarPath, "{"+"device_uuid"+"}", url.PathEscape(parameterValueToString(r.deviceUuid, "deviceUuid")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"configlet"+"}", url.PathEscape(parameterValueToString(r.configlet, "configlet")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiLoadFirmwareChecksumV1DeviceDeviceUuidFirmwareChecksumGetRequest struct {
	ctx        context.Context
	ApiService *DeviceAPIService
	deviceUuid string
}

func (r ApiLoadFirmwareChecksumV1DeviceDeviceUuidFirmwareChecksumGetRequest) Execute() (*ChecksumResponse, *http.Response, error) {
	return r.ApiService.LoadFirmwareChecksumV1DeviceDeviceUuidFirmwareChecksumGetExecute(r)
}

/*
LoadFirmwareChecksumV1DeviceDeviceUuidFirmwareChecksumGet Load Firmware Checksum

Load the firmware checksum for the given device.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param deviceUuid
	@return ApiLoadFirmwareChecksumV1DeviceDeviceUuidFirmwareChecksumGetRequest
*/
func (a *DeviceAPIService) LoadFirmwareChecksumV1DeviceDeviceUuidFirmwareChecksumGet(ctx context.Context, deviceUuid string) ApiLoadFirmwareChecksumV1DeviceDeviceUuidFirmwareChecksumGetRequest {
	return ApiLoadFirmwareChecksumV1DeviceDeviceUuidFirmwareChecksumGetRequest{
		ApiService: a,
		ctx:        ctx,
		deviceUuid: deviceUuid,
	}
}

// Execute executes the request
//
//	@return ChecksumResponse
func (a *DeviceAPIService) LoadFirmwareChecksumV1DeviceDeviceUuidFirmwareChecksumGetExecute(r ApiLoadFirmwareChecksumV1DeviceDeviceUuidFirmwareChecksumGetRequest) (*ChecksumResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ChecksumResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DeviceAPIService.LoadFirmwareChecksumV1DeviceDeviceUuidFirmwareChecksumGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/device/{device_uuid}/firmware/checksum"
	localVarPath = strings.Replace(localVarPath, "{"+"device_uuid"+"}", url.PathEscape(parameterValueToString(r.deviceUuid, "deviceUuid")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiLoadFirmwareV1DeviceDeviceUuidFirmwareGetRequest struct {
	ctx        context.Context
	ApiService *DeviceAPIService
	deviceUuid string
}

func (r ApiLoadFirmwareV1DeviceDeviceUuidFirmwareGetRequest) Execute() (*http.Response, error) {
	return r.ApiService.LoadFirmwareV1DeviceDeviceUuidFirmwareGetExecute(r)
}

/*
LoadFirmwareV1DeviceDeviceUuidFirmwareGet Load Firmware

Load the firmware for the given device.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param deviceUuid
	@return ApiLoadFirmwareV1DeviceDeviceUuidFirmwareGetRequest
*/
func (a *DeviceAPIService) LoadFirmwareV1DeviceDeviceUuidFirmwareGet(ctx context.Context, deviceUuid string) ApiLoadFirmwareV1DeviceDeviceUuidFirmwareGetRequest {
	return ApiLoadFirmwareV1DeviceDeviceUuidFirmwareGetRequest{
		ApiService: a,
		ctx:        ctx,
		deviceUuid: deviceUuid,
	}
}

// Execute executes the request
func (a *DeviceAPIService) LoadFirmwareV1DeviceDeviceUuidFirmwareGetExecute(r ApiLoadFirmwareV1DeviceDeviceUuidFirmwareGetRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodGet
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DeviceAPIService.LoadFirmwareV1DeviceDeviceUuidFirmwareGet")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/device/{device_uuid}/firmware"
	localVarPath = strings.Replace(localVarPath, "{"+"device_uuid"+"}", url.PathEscape(parameterValueToString(r.deviceUuid, "deviceUuid")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiLoadFirmwareV1DeviceDeviceUuidOnieGetRequest struct {
	ctx        context.Context
	ApiService *DeviceAPIService
	deviceUuid string
}

func (r ApiLoadFirmwareV1DeviceDeviceUuidOnieGetRequest) Execute() (string, *http.Response, error) {
	return r.ApiService.LoadFirmwareV1DeviceDeviceUuidOnieGetExecute(r)
}

/*
LoadFirmwareV1DeviceDeviceUuidOnieGet Load Firmware

Load the firmware for the given device.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param deviceUuid
	@return ApiLoadFirmwareV1DeviceDeviceUuidOnieGetRequest
*/
func (a *DeviceAPIService) LoadFirmwareV1DeviceDeviceUuidOnieGet(ctx context.Context, deviceUuid string) ApiLoadFirmwareV1DeviceDeviceUuidOnieGetRequest {
	return ApiLoadFirmwareV1DeviceDeviceUuidOnieGetRequest{
		ApiService: a,
		ctx:        ctx,
		deviceUuid: deviceUuid,
	}
}

// Execute executes the request
//
//	@return string
func (a *DeviceAPIService) LoadFirmwareV1DeviceDeviceUuidOnieGetExecute(r ApiLoadFirmwareV1DeviceDeviceUuidOnieGetRequest) (string, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DeviceAPIService.LoadFirmwareV1DeviceDeviceUuidOnieGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/device/{device_uuid}/onie"
	localVarPath = strings.Replace(localVarPath, "{"+"device_uuid"+"}", url.PathEscape(parameterValueToString(r.deviceUuid, "deviceUuid")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiMarkProvisionedV1DeviceDeviceUuidProvisionedPostRequest struct {
	ctx        context.Context
	ApiService *DeviceAPIService
	deviceUuid string
}

func (r ApiMarkProvisionedV1DeviceDeviceUuidProvisionedPostRequest) Execute() (string, *http.Response, error) {
	return r.ApiService.MarkProvisionedV1DeviceDeviceUuidProvisionedPostExecute(r)
}

/*
MarkProvisionedV1DeviceDeviceUuidProvisionedPost Mark Provisioned

Mark the ZTP process complete for the given device.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param deviceUuid
	@return ApiMarkProvisionedV1DeviceDeviceUuidProvisionedPostRequest
*/
func (a *DeviceAPIService) MarkProvisionedV1DeviceDeviceUuidProvisionedPost(ctx context.Context, deviceUuid string) ApiMarkProvisionedV1DeviceDeviceUuidProvisionedPostRequest {
	return ApiMarkProvisionedV1DeviceDeviceUuidProvisionedPostRequest{
		ApiService: a,
		ctx:        ctx,
		deviceUuid: deviceUuid,
	}
}

// Execute executes the request
//
//	@return string
func (a *DeviceAPIService) MarkProvisionedV1DeviceDeviceUuidProvisionedPostExecute(r ApiMarkProvisionedV1DeviceDeviceUuidProvisionedPostRequest) (string, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DeviceAPIService.MarkProvisionedV1DeviceDeviceUuidProvisionedPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/device/{device_uuid}/provisioned"
	localVarPath = strings.Replace(localVarPath, "{"+"device_uuid"+"}", url.PathEscape(parameterValueToString(r.deviceUuid, "deviceUuid")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiValidateSerialV1DeviceDeviceUuidValidateSerialPostRequest struct {
	ctx                context.Context
	ApiService         *DeviceAPIService
	deviceUuid         string
	validateSerialBody *ValidateSerialBody
}

func (r ApiValidateSerialV1DeviceDeviceUuidValidateSerialPostRequest) ValidateSerialBody(validateSerialBody ValidateSerialBody) ApiValidateSerialV1DeviceDeviceUuidValidateSerialPostRequest {
	r.validateSerialBody = &validateSerialBody
	return r
}

func (r ApiValidateSerialV1DeviceDeviceUuidValidateSerialPostRequest) Execute() (string, *http.Response, error) {
	return r.ApiService.ValidateSerialV1DeviceDeviceUuidValidateSerialPostExecute(r)
}

/*
ValidateSerialV1DeviceDeviceUuidValidateSerialPost Validate Serial

Validate the device serial number matches the selected DCIM.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param deviceUuid
	@return ApiValidateSerialV1DeviceDeviceUuidValidateSerialPostRequest
*/
func (a *DeviceAPIService) ValidateSerialV1DeviceDeviceUuidValidateSerialPost(ctx context.Context, deviceUuid string) ApiValidateSerialV1DeviceDeviceUuidValidateSerialPostRequest {
	return ApiValidateSerialV1DeviceDeviceUuidValidateSerialPostRequest{
		ApiService: a,
		ctx:        ctx,
		deviceUuid: deviceUuid,
	}
}

// Execute executes the request
//
//	@return string
func (a *DeviceAPIService) ValidateSerialV1DeviceDeviceUuidValidateSerialPostExecute(r ApiValidateSerialV1DeviceDeviceUuidValidateSerialPostRequest) (string, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DeviceAPIService.ValidateSerialV1DeviceDeviceUuidValidateSerialPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/device/{device_uuid}/validate_serial"
	localVarPath = strings.Replace(localVarPath, "{"+"device_uuid"+"}", url.PathEscape(parameterValueToString(r.deviceUuid, "deviceUuid")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.validateSerialBody == nil {
		return localVarReturnValue, nil, reportError("validateSerialBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.validateSerialBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
