/*
ZTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ztp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ValidateSerialBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidateSerialBody{}

// ValidateSerialBody Request body for serial number validation.
type ValidateSerialBody struct {
	Serial string `json:"serial"`
}

type _ValidateSerialBody ValidateSerialBody

// NewValidateSerialBody instantiates a new ValidateSerialBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidateSerialBody(serial string) *ValidateSerialBody {
	this := ValidateSerialBody{}
	this.Serial = serial
	return &this
}

// NewValidateSerialBodyWithDefaults instantiates a new ValidateSerialBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidateSerialBodyWithDefaults() *ValidateSerialBody {
	this := ValidateSerialBody{}
	return &this
}

// GetSerial returns the Serial field value
func (o *ValidateSerialBody) GetSerial() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Serial
}

// GetSerialOk returns a tuple with the Serial field value
// and a boolean to check if the value has been set.
func (o *ValidateSerialBody) GetSerialOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Serial, true
}

// SetSerial sets field value
func (o *ValidateSerialBody) SetSerial(v string) {
	o.Serial = v
}

func (o ValidateSerialBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidateSerialBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["serial"] = o.Serial
	return toSerialize, nil
}

func (o *ValidateSerialBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"serial": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varValidateSerialBody := _ValidateSerialBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varValidateSerialBody)

	if err != nil {
		return err
	}

	*o = ValidateSerialBody(varValidateSerialBody)

	return err
}

type NullableValidateSerialBody struct {
	value *ValidateSerialBody
	isSet bool
}

func (v NullableValidateSerialBody) Get() *ValidateSerialBody {
	return v.value
}

func (v *NullableValidateSerialBody) Set(val *ValidateSerialBody) {
	v.value = val
	v.isSet = true
}

func (v NullableValidateSerialBody) IsSet() bool {
	return v.isSet
}

func (v *NullableValidateSerialBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidateSerialBody(val *ValidateSerialBody) *NullableValidateSerialBody {
	return &NullableValidateSerialBody{value: val, isSet: true}
}

func (v NullableValidateSerialBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidateSerialBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
