/*
ZTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ztp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ObjectInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectInfo{}

// ObjectInfo Metadata for an object in the storage backend.
type ObjectInfo struct {
	// ETag hash
	Etag NullableString `json:"etag,omitempty"`
	// Object key/path
	Key          string       `json:"key"`
	LastModified LastModified `json:"last_modified"`
	// Object metadata
	Metadata map[string]string `json:"metadata,omitempty"`
	// Object size in bytes
	Size int32 `json:"size"`
	// Object tags
	Tags map[string]string `json:"tags,omitempty"`
}

type _ObjectInfo ObjectInfo

// NewObjectInfo instantiates a new ObjectInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectInfo(key string, lastModified LastModified, size int32) *ObjectInfo {
	this := ObjectInfo{}
	this.Key = key
	this.LastModified = lastModified
	this.Size = size
	return &this
}

// NewObjectInfoWithDefaults instantiates a new ObjectInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectInfoWithDefaults() *ObjectInfo {
	this := ObjectInfo{}
	return &this
}

// GetEtag returns the Etag field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ObjectInfo) GetEtag() string {
	if o == nil || IsNil(o.Etag.Get()) {
		var ret string
		return ret
	}
	return *o.Etag.Get()
}

// GetEtagOk returns a tuple with the Etag field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *ObjectInfo) GetEtagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Etag.Get(), o.Etag.IsSet()
}

// HasEtag returns a boolean if a field has been set.
func (o *ObjectInfo) HasEtag() bool {
	if o != nil && o.Etag.IsSet() {
		return true
	}

	return false
}

// SetEtag gets a reference to the given NullableString and assigns it to the Etag field.
func (o *ObjectInfo) SetEtag(v string) {
	o.Etag.Set(&v)
}

// SetEtagNil sets the value for Etag to be an explicit nil
func (o *ObjectInfo) SetEtagNil() {
	o.Etag.Set(nil)
}

// UnsetEtag ensures that no value is present for Etag, not even an explicit nil
func (o *ObjectInfo) UnsetEtag() {
	o.Etag.Unset()
}

// GetKey returns the Key field value
func (o *ObjectInfo) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *ObjectInfo) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *ObjectInfo) SetKey(v string) {
	o.Key = v
}

// GetLastModified returns the LastModified field value
func (o *ObjectInfo) GetLastModified() LastModified {
	if o == nil {
		var ret LastModified
		return ret
	}

	return o.LastModified
}

// GetLastModifiedOk returns a tuple with the LastModified field value
// and a boolean to check if the value has been set.
func (o *ObjectInfo) GetLastModifiedOk() (*LastModified, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastModified, true
}

// SetLastModified sets field value
func (o *ObjectInfo) SetLastModified(v LastModified) {
	o.LastModified = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ObjectInfo) GetMetadata() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *ObjectInfo) GetMetadataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ObjectInfo) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *ObjectInfo) SetMetadata(v map[string]string) {
	o.Metadata = v
}

// GetSize returns the Size field value
func (o *ObjectInfo) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ObjectInfo) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ObjectInfo) SetSize(v int32) {
	o.Size = v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ObjectInfo) GetTags() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.

func (o *ObjectInfo) GetTagsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ObjectInfo) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]string and assigns it to the Tags field.
func (o *ObjectInfo) SetTags(v map[string]string) {
	o.Tags = v
}

func (o ObjectInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Etag.IsSet() {
		toSerialize["etag"] = o.Etag.Get()
	}
	toSerialize["key"] = o.Key
	toSerialize["last_modified"] = o.LastModified
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["size"] = o.Size
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

func (o *ObjectInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"key":           false,
		"last_modified": false,
		"size":          false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObjectInfo := _ObjectInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varObjectInfo)

	if err != nil {
		return err
	}

	*o = ObjectInfo(varObjectInfo)

	return err
}

type NullableObjectInfo struct {
	value *ObjectInfo
	isSet bool
}

func (v NullableObjectInfo) Get() *ObjectInfo {
	return v.value
}

func (v *NullableObjectInfo) Set(val *ObjectInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectInfo(val *ObjectInfo) *NullableObjectInfo {
	return &NullableObjectInfo{value: val, isSet: true}
}

func (v NullableObjectInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
