/*
DHCP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dhcp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PoolRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PoolRecord{}

// PoolRecord Configured address pool.
type PoolRecord struct {
	Pool   string `json:"pool"`
	Subnet string `json:"subnet"`
}

type _PoolRecord PoolRecord

// NewPoolRecord instantiates a new PoolRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPoolRecord(pool string, subnet string) *PoolRecord {
	this := PoolRecord{}
	this.Pool = pool
	this.Subnet = subnet
	return &this
}

// NewPoolRecordWithDefaults instantiates a new PoolRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPoolRecordWithDefaults() *PoolRecord {
	this := PoolRecord{}
	return &this
}

// GetPool returns the Pool field value
func (o *PoolRecord) GetPool() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pool
}

// GetPoolOk returns a tuple with the Pool field value
// and a boolean to check if the value has been set.
func (o *PoolRecord) GetPoolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pool, true
}

// SetPool sets field value
func (o *PoolRecord) SetPool(v string) {
	o.Pool = v
}

// GetSubnet returns the Subnet field value
func (o *PoolRecord) GetSubnet() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subnet
}

// GetSubnetOk returns a tuple with the Subnet field value
// and a boolean to check if the value has been set.
func (o *PoolRecord) GetSubnetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subnet, true
}

// SetSubnet sets field value
func (o *PoolRecord) SetSubnet(v string) {
	o.Subnet = v
}

func (o PoolRecord) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PoolRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pool"] = o.Pool
	toSerialize["subnet"] = o.Subnet
	return toSerialize, nil
}

func (o *PoolRecord) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"pool":   false,
		"subnet": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPoolRecord := _PoolRecord{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPoolRecord)

	if err != nil {
		return err
	}

	*o = PoolRecord(varPoolRecord)

	return err
}

type NullablePoolRecord struct {
	value *PoolRecord
	isSet bool
}

func (v NullablePoolRecord) Get() *PoolRecord {
	return v.value
}

func (v *NullablePoolRecord) Set(val *PoolRecord) {
	v.value = val
	v.isSet = true
}

func (v NullablePoolRecord) IsSet() bool {
	return v.isSet
}

func (v *NullablePoolRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePoolRecord(val *PoolRecord) *NullablePoolRecord {
	return &NullablePoolRecord{value: val, isSet: true}
}

func (v NullablePoolRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePoolRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
