/*
DHCP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dhcp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PoolPageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PoolPageResponse{}

// PoolPageResponse Bounded page of configured pools.
type PoolPageResponse struct {
	NextCursor NullableString `json:"next_cursor,omitempty"`
	Pools      []PoolRecord   `json:"pools"`
	TotalCount int32          `json:"total_count"`
}

type _PoolPageResponse PoolPageResponse

// NewPoolPageResponse instantiates a new PoolPageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPoolPageResponse(pools []PoolRecord, totalCount int32) *PoolPageResponse {
	this := PoolPageResponse{}
	this.Pools = pools
	this.TotalCount = totalCount
	return &this
}

// NewPoolPageResponseWithDefaults instantiates a new PoolPageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPoolPageResponseWithDefaults() *PoolPageResponse {
	this := PoolPageResponse{}
	return &this
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PoolPageResponse) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor.Get()) {
		var ret string
		return ret
	}
	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *PoolPageResponse) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// HasNextCursor returns a boolean if a field has been set.
func (o *PoolPageResponse) HasNextCursor() bool {
	if o != nil && o.NextCursor.IsSet() {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given NullableString and assigns it to the NextCursor field.
func (o *PoolPageResponse) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}

// SetNextCursorNil sets the value for NextCursor to be an explicit nil
func (o *PoolPageResponse) SetNextCursorNil() {
	o.NextCursor.Set(nil)
}

// UnsetNextCursor ensures that no value is present for NextCursor, not even an explicit nil
func (o *PoolPageResponse) UnsetNextCursor() {
	o.NextCursor.Unset()
}

// GetPools returns the Pools field value
func (o *PoolPageResponse) GetPools() []PoolRecord {
	if o == nil {
		var ret []PoolRecord
		return ret
	}

	return o.Pools
}

// GetPoolsOk returns a tuple with the Pools field value
// and a boolean to check if the value has been set.
func (o *PoolPageResponse) GetPoolsOk() ([]PoolRecord, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pools, true
}

// SetPools sets field value
func (o *PoolPageResponse) SetPools(v []PoolRecord) {
	o.Pools = v
}

// GetTotalCount returns the TotalCount field value
func (o *PoolPageResponse) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *PoolPageResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *PoolPageResponse) SetTotalCount(v int32) {
	o.TotalCount = v
}

func (o PoolPageResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PoolPageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.NextCursor.IsSet() {
		toSerialize["next_cursor"] = o.NextCursor.Get()
	}
	toSerialize["pools"] = o.Pools
	toSerialize["total_count"] = o.TotalCount
	return toSerialize, nil
}

func (o *PoolPageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"pools":       false,
		"total_count": false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPoolPageResponse := _PoolPageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPoolPageResponse)

	if err != nil {
		return err
	}

	*o = PoolPageResponse(varPoolPageResponse)

	return err
}

type NullablePoolPageResponse struct {
	value *PoolPageResponse
	isSet bool
}

func (v NullablePoolPageResponse) Get() *PoolPageResponse {
	return v.value
}

func (v *NullablePoolPageResponse) Set(val *PoolPageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePoolPageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePoolPageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePoolPageResponse(val *PoolPageResponse) *NullablePoolPageResponse {
	return &NullablePoolPageResponse{value: val, isSet: true}
}

func (v NullablePoolPageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePoolPageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
