/*
DHCP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dhcp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ReservationPageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReservationPageResponse{}

// ReservationPageResponse Bounded page of normalized reservations.
type ReservationPageResponse struct {
	NextCursor   NullableString      `json:"next_cursor,omitempty"`
	Reservations []ReservationRecord `json:"reservations"`
	TotalCount   int32               `json:"total_count"`
}

type _ReservationPageResponse ReservationPageResponse

// NewReservationPageResponse instantiates a new ReservationPageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReservationPageResponse(reservations []ReservationRecord, totalCount int32) *ReservationPageResponse {
	this := ReservationPageResponse{}
	this.Reservations = reservations
	this.TotalCount = totalCount
	return &this
}

// NewReservationPageResponseWithDefaults instantiates a new ReservationPageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReservationPageResponseWithDefaults() *ReservationPageResponse {
	this := ReservationPageResponse{}
	return &this
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReservationPageResponse) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor.Get()) {
		var ret string
		return ret
	}
	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.

// NOTE: If the value is an explicit nil, `nil, true` will be returned

func (o *ReservationPageResponse) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// HasNextCursor returns a boolean if a field has been set.
func (o *ReservationPageResponse) HasNextCursor() bool {
	if o != nil && o.NextCursor.IsSet() {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given NullableString and assigns it to the NextCursor field.
func (o *ReservationPageResponse) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}

// SetNextCursorNil sets the value for NextCursor to be an explicit nil
func (o *ReservationPageResponse) SetNextCursorNil() {
	o.NextCursor.Set(nil)
}

// UnsetNextCursor ensures that no value is present for NextCursor, not even an explicit nil
func (o *ReservationPageResponse) UnsetNextCursor() {
	o.NextCursor.Unset()
}

// GetReservations returns the Reservations field value
func (o *ReservationPageResponse) GetReservations() []ReservationRecord {
	if o == nil {
		var ret []ReservationRecord
		return ret
	}

	return o.Reservations
}

// GetReservationsOk returns a tuple with the Reservations field value
// and a boolean to check if the value has been set.
func (o *ReservationPageResponse) GetReservationsOk() ([]ReservationRecord, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reservations, true
}

// SetReservations sets field value
func (o *ReservationPageResponse) SetReservations(v []ReservationRecord) {
	o.Reservations = v
}

// GetTotalCount returns the TotalCount field value
func (o *ReservationPageResponse) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *ReservationPageResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *ReservationPageResponse) SetTotalCount(v int32) {
	o.TotalCount = v
}

func (o ReservationPageResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReservationPageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.NextCursor.IsSet() {
		toSerialize["next_cursor"] = o.NextCursor.Get()
	}
	toSerialize["reservations"] = o.Reservations
	toSerialize["total_count"] = o.TotalCount
	return toSerialize, nil
}

func (o *ReservationPageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"reservations": false,
		"total_count":  false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReservationPageResponse := _ReservationPageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReservationPageResponse)

	if err != nil {
		return err
	}

	*o = ReservationPageResponse(varReservationPageResponse)

	return err
}

type NullableReservationPageResponse struct {
	value *ReservationPageResponse
	isSet bool
}

func (v NullableReservationPageResponse) Get() *ReservationPageResponse {
	return v.value
}

func (v *NullableReservationPageResponse) Set(val *ReservationPageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReservationPageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReservationPageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReservationPageResponse(val *ReservationPageResponse) *NullableReservationPageResponse {
	return &NullableReservationPageResponse{value: val, isSet: true}
}

func (v NullableReservationPageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReservationPageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
