/*
DHCP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dhcp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DhcpSummaryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DhcpSummaryResponse{}

// DhcpSummaryResponse Lease, reservation, and pool summary.
type DhcpSummaryResponse struct {
	ActiveLeaseCount int32 `json:"active_lease_count"`
	PoolCount        int32 `json:"pool_count"`
	ReservationCount int32 `json:"reservation_count"`
}

type _DhcpSummaryResponse DhcpSummaryResponse

// NewDhcpSummaryResponse instantiates a new DhcpSummaryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDhcpSummaryResponse(activeLeaseCount int32, poolCount int32, reservationCount int32) *DhcpSummaryResponse {
	this := DhcpSummaryResponse{}
	this.ActiveLeaseCount = activeLeaseCount
	this.PoolCount = poolCount
	this.ReservationCount = reservationCount
	return &this
}

// NewDhcpSummaryResponseWithDefaults instantiates a new DhcpSummaryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDhcpSummaryResponseWithDefaults() *DhcpSummaryResponse {
	this := DhcpSummaryResponse{}
	return &this
}

// GetActiveLeaseCount returns the ActiveLeaseCount field value
func (o *DhcpSummaryResponse) GetActiveLeaseCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ActiveLeaseCount
}

// GetActiveLeaseCountOk returns a tuple with the ActiveLeaseCount field value
// and a boolean to check if the value has been set.
func (o *DhcpSummaryResponse) GetActiveLeaseCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActiveLeaseCount, true
}

// SetActiveLeaseCount sets field value
func (o *DhcpSummaryResponse) SetActiveLeaseCount(v int32) {
	o.ActiveLeaseCount = v
}

// GetPoolCount returns the PoolCount field value
func (o *DhcpSummaryResponse) GetPoolCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PoolCount
}

// GetPoolCountOk returns a tuple with the PoolCount field value
// and a boolean to check if the value has been set.
func (o *DhcpSummaryResponse) GetPoolCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolCount, true
}

// SetPoolCount sets field value
func (o *DhcpSummaryResponse) SetPoolCount(v int32) {
	o.PoolCount = v
}

// GetReservationCount returns the ReservationCount field value
func (o *DhcpSummaryResponse) GetReservationCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReservationCount
}

// GetReservationCountOk returns a tuple with the ReservationCount field value
// and a boolean to check if the value has been set.
func (o *DhcpSummaryResponse) GetReservationCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReservationCount, true
}

// SetReservationCount sets field value
func (o *DhcpSummaryResponse) SetReservationCount(v int32) {
	o.ReservationCount = v
}

func (o DhcpSummaryResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DhcpSummaryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["active_lease_count"] = o.ActiveLeaseCount
	toSerialize["pool_count"] = o.PoolCount
	toSerialize["reservation_count"] = o.ReservationCount
	return toSerialize, nil
}

func (o *DhcpSummaryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := map[string]bool{
		"active_lease_count": false,
		"pool_count":         false,
		"reservation_count":  false,
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for requiredProperty, nullable := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || (value == nil && !nullable) {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDhcpSummaryResponse := _DhcpSummaryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDhcpSummaryResponse)

	if err != nil {
		return err
	}

	*o = DhcpSummaryResponse(varDhcpSummaryResponse)

	return err
}

type NullableDhcpSummaryResponse struct {
	value *DhcpSummaryResponse
	isSet bool
}

func (v NullableDhcpSummaryResponse) Get() *DhcpSummaryResponse {
	return v.value
}

func (v *NullableDhcpSummaryResponse) Set(val *DhcpSummaryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDhcpSummaryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDhcpSummaryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDhcpSummaryResponse(val *DhcpSummaryResponse) *NullableDhcpSummaryResponse {
	return &NullableDhcpSummaryResponse{value: val, isSet: true}
}

func (v NullableDhcpSummaryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDhcpSummaryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
