fragment DHCPInterface on InterfaceType {
  name
  mac_address
  role {
    name
  }
  device {
    id
    name
    serial
    platform {
      name
    }
    status {
      name
    }
    configmanagerdevicestatus {
      ztp_enabled
      is_aggregate_managed
    }
  }
}

query site_dhcp_options {
  config_contexts(schema: "nv-config-manager-site-dhcp-option-def", is_active: true) {
    data
  }
}

query dhcp_contexts($is_aggregate_managed: Boolean, $limit: Int!, $offset: Int!) {
  config_manager_devices(
    ztp_enabled: true
    is_aggregate_managed: $is_aggregate_managed
    limit: $limit
    offset: $offset
  ) {
    device {
      id
      config_context
    }
  }
}

query static_data {
  config_contexts(schema: "nv-config-manager-kea-static-data", is_active: true) {
    data
  }
}

query auto_dhcp_subnets_prefixes($limit: Int!, $offset: Int!) {
  prefixes(tags: ["dhcp-subnet"], limit: $limit, offset: $offset) {
    id
    prefix
    ip_version
    rel_prefix_to_gateway {
      address
    }
  }
}

query auto_dhcp_subnets_pool_ips($limit: Int!, $offset: Int!) {
  pool_ips: ip_addresses(tags: ["dhcp-pool"], limit: $limit, offset: $offset) {
    address
    ip_version
    parent {
      id
    }
    interfaces {
      ...DHCPInterface
    }
  }
}

query auto_dhcp_subnets_reserved_ips($limit: Int!, $offset: Int!) {
  reserved_ips: ip_addresses(tags: ["dhcp-reserve"], limit: $limit, offset: $offset) {
    address
    ip_version
    parent {
      id
    }
    interfaces {
      ...DHCPInterface
    }
  }
}
