# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Compatibility exports for package-owned DCIM activities."""

from nv_config_manager_workflows.activities.dcim import (
    DCIM_ACTIVITIES,
    AssignVrfToDeviceInput,
    AssignVrfToInterfaceInput,
    CheckRecordedConfigDriftInput,
    DeleteOverlayInput,
    DeleteOverlayOutput,
    DeviceVRF,
    DeviceVrfInfo,
    GetAvailableRouteDistinguishersInput,
    GetAvailableRouteDistinguishersOutput,
    GetDeviceInterfacesInput,
    GetDeviceInterfacesOutput,
    GetDeviceVrfsInput,
    GetDeviceVrfsOutput,
    GetHostDeviceInput,
    GetHostDeviceOutput,
    GetHostDevicesInput,
    GetHostDevicesOutput,
    GetNetworkDeviceInput,
    GetNetworkDeviceOutput,
    GetNetworkDevicesInput,
    GetNetworkDevicesOutput,
    HostData,
    HostInterface,
    ProvisionVrfInput,
    QueryVRFByVPCInput,
    ReconcileSpXOverlayAssignmentsInput,
    ReconcileSpXOverlayAssignmentsOutput,
    RemoveUnmappedDeviceVrfsInput,
    RemoveUnmappedDeviceVrfsOutput,
    SwitchPortByMacActivityInput,
    SwitchPortByMacActivityOutput,
    Vrf,
    VrfDeletionActivityInput,
    assign_vrf_to_device,
    assign_vrf_to_interface,
    check_recorded_config_drift,
    delete_overlay,
    delete_vrf,
    get_available_route_distinguishers,
    get_device_interfaces,
    get_device_vrfs,
    get_host_data_by_macs,
    get_host_data_by_names,
    get_host_device,
    get_host_devices,
    get_network_device,
    get_network_devices,
    get_switch_port_by_remote_mac_address,
    get_vrfs_by_overlay_id,
    provision_vrf,
    reconcile_spx_overlay_assignments,
    remove_unmapped_device_vrfs,
)

__all__ = [
    "DCIM_ACTIVITIES",
    "AssignVrfToDeviceInput",
    "AssignVrfToInterfaceInput",
    "CheckRecordedConfigDriftInput",
    "DeleteOverlayInput",
    "DeleteOverlayOutput",
    "DeviceVRF",
    "DeviceVrfInfo",
    "GetAvailableRouteDistinguishersInput",
    "GetAvailableRouteDistinguishersOutput",
    "GetDeviceInterfacesInput",
    "GetDeviceInterfacesOutput",
    "GetDeviceVrfsInput",
    "GetDeviceVrfsOutput",
    "GetHostDeviceInput",
    "GetHostDeviceOutput",
    "GetHostDevicesInput",
    "GetHostDevicesOutput",
    "GetNetworkDeviceInput",
    "GetNetworkDeviceOutput",
    "GetNetworkDevicesInput",
    "GetNetworkDevicesOutput",
    "HostData",
    "HostInterface",
    "ProvisionVrfInput",
    "QueryVRFByVPCInput",
    "ReconcileSpXOverlayAssignmentsInput",
    "ReconcileSpXOverlayAssignmentsOutput",
    "RemoveUnmappedDeviceVrfsInput",
    "RemoveUnmappedDeviceVrfsOutput",
    "SwitchPortByMacActivityInput",
    "SwitchPortByMacActivityOutput",
    "Vrf",
    "VrfDeletionActivityInput",
    "assign_vrf_to_device",
    "assign_vrf_to_interface",
    "check_recorded_config_drift",
    "delete_overlay",
    "delete_vrf",
    "get_available_route_distinguishers",
    "get_device_interfaces",
    "get_device_vrfs",
    "get_host_data_by_macs",
    "get_host_data_by_names",
    "get_host_device",
    "get_host_devices",
    "get_network_device",
    "get_network_devices",
    "get_switch_port_by_remote_mac_address",
    "get_vrfs_by_overlay_id",
    "provision_vrf",
    "reconcile_spx_overlay_assignments",
    "remove_unmapped_device_vrfs",
]
